### ISSUE TITLE
Dimensional transceiver weird/impractical behavior with energy conduits.

### ISSUE THREAD

**Issue by 3ddyy** [SleepyTrousers/EnderIO#4664] opened 2018-05-29 18:21 UTC
#### What happens:

Dimensional transceiver does not output energy to conduits if the setting is set to input and extract (works fine with only extract)

#### What you expected to happen:

I expected the transceiver to take power from its send/receive buffer and output it into the conduit

#### Steps to reproduce:

1. Place a creative capbank and a dimensional transceiver [A], and connect them with any energy conduit.
2. Place another dimensional transceiver [B] and a vibrant capbank elsewhere and connect those two with energy conduits as well.
3. Create a power transceiver channel where [A] will send and [B] will receive.
4. [B]'s power bar and buffer should fill up, and they are not affected by the capacitor bank, which will not fill up at all.
5. If the conduit pointing into [B] is set to extract only, it will send power to the capacitor bank as expected.
(the reason i'd like to have insert checked as well is so that the transceiver can send power to other connected transceivers without having to rely on the inputted power coming from yet another transceiver)

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.25
- EnderCore: 0.5.30
- Minecraft: 1.12.2
- Forge: 14.23.3.2673

#### Your most recent log file where the issue was present: 

N/A

**Comment by EpicSquid** [comment] 2018-08-15 01:00
Closing this as this works as intended. Conduits store energy internally, so if in/out is enabled the dim trans will push to the conduit then pull the energy right back in.

**Closed by EpicSquid** 2018-08-15 01:00 UTC
Labels: 1.12
