### ISSUE TITLE
Light goes through conduit facades

### ISSUE THREAD

**Issue by PapiDimmi** [SleepyTrousers/EnderIO#4143] opened 2017-04-08 16:56 UTC
* **[Minecraft](https://minecraft.net) version**: [1.10.2](https://minecraft.gamepedia.com/1.10.2)
* **[Forge](https://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.10.2.html) version**: [12.18.3.2272](https://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.10.2.html) (latest for 1.10.2)
* **[Ender IO](https://minecraft.curseforge.com/projects/ender-io) version**: [3.1.179](https://minecraft.curseforge.com/projects/ender-io/files/2392869) (latest for 1.10.2)
* **[EnderCore](https://minecraft.curseforge.com/projects/endercore) version**: [0.4.1.65-beta](https://minecraft.curseforge.com/projects/endercore/files/2370656) (latest for 1.10.2)

**Comment by Alex-hawks** [comment] 2017-04-09 07:40
Duplicate of #4076 and related to #4134

**Comment by PapiDimmi** [comment] 2017-04-09 07:42
>Duplicate of #4076

That’s about conduit facades having black sides, which is not the bug that I’m reporting.

>and related to #4134

How is that related? This is about light passing through facades, and #4134 is about water flowing next to facades.

**Closed** 2017-04-09 08:23 UTC
Labels: Duplicate

**Comment by Alex-hawks** [comment] 2017-04-09 10:09
related to because both are probably cause by the fact that "conduit bundles" even with facades on them are transparent blocks. and check the edit
