### ISSUE TITLE
Teleport Crash (Nether Portal)

### ISSUE THREAD

**Issue by ShaCraft** [SleepyTrousers/EnderIO#3626] opened 2016-08-20 13:07 UTC
After removing mods and adding them back in a few at a time and removing a few till Only one was left that resolved the crash. Without enderIO/core no crash.

#### Issue Description:
Modded FTB Unstable 1.10 pack and All the mods. 

#### What happens:
When returning from Nether to over world the server crashes. When returning from AromaCore mining dim the server crashes. I have not tried other teleport systems. Player is also teleported to a spot under ground and suffocated to death.

#### What you expected to happen:
Not to crash :D

#### Steps to reproduce:

1. make a portal 
2. go in the portal
3. try to return to the over world and crash 
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.10.2-3.0.1.81_beta
- EnderCore: EnderCore-1.10.2-0.4.1.46-beta
- Minecraft: 1.10.2
- Forge: forge-1.10.2-12.18.1.2046-universal

#### Your most recent log file where the issue was present: 

http://pastebin.com/Sy8CXPAn

**Comment by ShaCraft** [comment] 2016-08-20 13:18
More info. I am able to port over 100 times as to make sure the sample is valid (with no EnderIO). add the mod and core back in and crash 70-80% of the time (tried 15+ times ((sorry got tired and lost count))).

**Comment by ShaCraft** [comment] 2016-08-20 13:36
Test 1: IO/core only. No crash (10 portals in new chunks with 150+ teleports). 
Test 2: testing update IO/Core with full pack:

**Comment by HenryLoenwind** [comment] 2016-08-20 13:40
yes, please. This isn't eio on its own.

**Comment by ShaCraft** [comment] 2016-08-20 15:18
We have a winner! err I found the conflict. deepresonance-1.10-1.2.1beta38.
Going to do some more testing just to make sure this is not a false positive.. or would it be a false negative?

**Comment by ShaCraft** [comment] 2016-08-20 17:10
More testing. So loading the world with only EnderIO/Core, mcjtylib, rftools/dim and deepresonance will not cause the crash. So... it looks like there is another mod(s) involved in the crash. 

More testing on the way. Going to start adding the mods back in a few at a time till we get the crash again (and test with a few new portals in new chunks and old). Each test I will do 20-30 teleports/portals.

**Comment by McJty** [comment] 2016-08-20 18:35
The Deep Resonance you use is outdated. Please update and test if this occurs again. The tank/fluid system was rewritten there

**Comment by ShaCraft** [comment] 2016-08-20 21:20
reread the post ^ there. #3 Test 3: Updated All mods; same crash

**Comment by ShaCraft** [comment] 2016-08-20 21:34
http://pastebin.com/YgFfLTfM

**Comment by ShaCraft** [comment] 2016-08-20 23:42
""
 UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack] (minecraft.jar)
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.1.2068-universal.jar)
    UCHIJAAAA   Forge{12.18.1.2068} [Minecraft Forge] (forge-1.10.2-12.18.1.2068-universal.jar)
    UCHIJAAAA   ElecCore{1.5.303} [ElecCore] (ElecCore-1.9.4-1.5.303.jar)
    UCHIJAAAA   deepresonance{1.2.1beta38} [DeepResonance] (deepresonance-1.10-1.2.1beta38.jar)
    UCHIJAAAA   endercore{1.10.2-0.4.1.48-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.48-beta.jar)
    UCHIJAAAA   EnderIO{1.10.2-3.0.1.92_beta} [Ender IO] (EnderIO-1.10.2-3.0.1.92_beta.jar)
    UCHIJAAAA   rftools{5.16} [RFTools] (rftools-1.10-5.16.jar)
    UCHIJAAAA   rftoolsdim{4.30beta47} [RFTools Dimensions] (rftoolsdim-1.10-4.30beta47.jar) 
""
http://pastebin.com/LsqLfAYA

**Comment by ShaCraft** [comment] 2016-08-21 14:57
Can't get a new world to crash today. maybe EnderCore-1.10.2-0.4.1.49-beta fixed the issue?
My original world is still borked, I just opted to make a new world load all my stuff into chest and on to disk in Refined Storage. I just copied the player files to the new server and seams well. 

If the crashes pop back up I'll just set up RFtools teleports to/from the nether (High Tech Nether Portal could be a thing?!! :D). 

If there is anything more for testing I can do let me know id be happy to help.

**Comment by ShaCraft** [comment] 2016-08-22 18:01
So anther observation; The crash can happen with E/IO or RFTools without the other being present. The common link is ElecCore.

**Comment by DietmarKrause** [comment] 2016-08-23 14:38
probaby the same problem with other modpack: https://github.com/whatthedrunk/allthemods/issues/95
 crash when returning to overworld this time via nether portal. i only want to link it here

**Comment by ZiggyAdventures** [comment] 2016-09-02 21:02
I was doing my own testing and narrowed it down to EnderCore. Testing on an older world that has the problem. New world gen does not cause this issue. Also removing ElecCore did not effect the crashes in anyway for me. Hopefully this info can be of help. Also the Mekanism crash has been completely separate from this one for me, one is loading or unloading chunks caused by teleporting and has a fixed pipe location. This one is just teleporting I to the over world without any mekanism pipes.

**Comment by ShaCraft** [comment] 2016-09-02 22:55
Yea same here my new world I am using in my lets play has not crashed the server yet. I have been Discoed a few time but the server stayed up. Ziggy can I ask what world gen type you used on the affected server/client? Was it Quarks by chance?

**Comment by ZiggyAdventures** [comment] 2016-09-03 09:39
It was normal BoP generation on All the Mods pack. As the world wasn't mine, I was just using it for testing the gripe, I do not know what version the world was generated on.

**Comment by CrazyPants** [comment] 2016-09-09 13:05
Is it still possible to reproduce this issue with a new world and the latest versions of each mod?

If not, it seems like a bug in one of the mods somehow 'broke' worlds in a way that isnt resolved by updating, but using the latest versions worls will no longer get 'broken'.

If this is the case I would close this issue.

**Comment by CrazyPants** [comment] 2016-09-12 14:16
If this occurs again using the most recent versions of the mods then please re-raise the issue with a new log. Thanks

**Closed by CrazyPants** 2016-09-12 14:16 UTC
Labels: 1.10, bug, Waiting For Feedback
