### ISSUE TITLE
[Feature Request] Exact Copy Powered Spawner

### ISSUE THREAD

**Issue by agowa338** [SleepyTrousers/EnderIO#2775] opened 2015-09-06 12:31 UTC
I would enjoy having a feature similar to the MineFactoryReloaded "Exact Copy" mode.
So, that sheep always have the same color or wither skeletons spawn dimension independent as such (keep NBT Data).

**Comment by tterrag1098** [comment] 2015-09-06 15:46
Duplicate of #2651

**Closed by tterrag1098** 2015-09-06 15:46 UTC
