### ISSUE TITLE
Bundled Conduit visual issue

### ISSUE THREAD

**Issue by BuckitHead** [SleepyTrousers/EnderIO#2812] opened 2015-09-14 20:07 UTC
After update to 415, When you walk up on bundled conduits they vanish visually. 
![2015-09-14_13 03 56](https://cloud.githubusercontent.com/assets/10180530/9860523/7feb0e04-5ae1-11e5-983f-182efc2f1927.png)

**Comment by BuckitHead** [comment] 2015-09-14 20:13
Person on the server mentioned that its not just bundled. it all works fine just visual

**Comment by Sandriell** [comment] 2015-09-15 09:54
Are you using Optifine? I got this when using it, and had to remove it.

**Comment by BuckitHead** [comment] 2015-09-15 12:18
No Optifine.

**Comment by CrazyCodeUK** [comment] 2015-09-19 09:26
I can also confirm this bug with 415 and no optifine. The conduits with disapear then reapear sometime when viewed from different angle or face away and back

**Comment by tterrag1098** [comment] 2015-09-23 19:49
For reference later this might have been broken here https://github.com/SleepyTrousers/EnderIO/commit/dfff76c0d7b240d95ff45929958f7a1d9add89ed#diff-ab2849483359c85b2ca5204960267ed3R117

**Comment by tterrag1098** [comment] 2015-10-06 03:58
I can't seem to reproduce this :/

**Comment by BuckitHead** [comment] 2015-10-06 19:42
I just updated to 416 on that sever and it's still happening... Let's me test and get back to you


Tom

**Comment by BuckitHead** [comment] 2015-10-06 20:12
ok so tried to create in single player and could not reproduce myself.  I did download the server world and tried it in single player, got the same thing so that makes this strange. Seems like the world has issues maybe. As soon as I back it down to 414 issue goes away.  I have a new just forge server I brought up a week ago, so let me update it and see what happens.

**Comment by BuckitHead** [comment] 2015-10-08 02:39
Ok on the new server it is happening again.  It's in and out now on 416,  on the other server its stayed gone on 415. I'm not sure what to tell you to help out. sorry

**Comment by Reanmachine** [comment] 2015-10-16 06:35
Playing FTB Inifinity which has 415 currently. I recorded a quick video demoing the problem:

https://www.youtube.com/watch?v=9BdO5oGfBr0

**Comment by tterrag1098** [comment] 2015-10-16 07:18
I can't test with infinity in my dev environment. I need a reproduction case with no (or a small amount of) mods, which I can actually test with.

**Comment by Reanmachine** [comment] 2015-10-16 20:03
@tterrag1098 If I get a chance this weekend ill start collapsing the infinity pack one mod at a time until i find a combination that doesn't trip the behavior and then we can go from that smaller subset or perhaps determine if it's another mod breaking ender io's behavior.

**Comment by tterrag1098** [comment] 2015-10-17 05:10
That would be awesome, thank you :)

**Comment by BuckitHead** [comment] 2015-10-17 21:52
Just FYI Reanmachine reverting to EnderIO 414 and core 24 make this issue stop

**Comment by JasonMcRay** [comment] 2015-10-29 17:46
Would like to ask how is solving this issue comming? It is quite annoying to trying to locate my conduits because they are just visualy gone:(

**Comment by HenryLoenwind** [comment] 2015-10-29 17:57
Oops, we had 2 issues for this problem open. Didn't notice, so I only updated the other one.

**Comment by JasonMcRay** [comment] 2015-11-04 14:53
https://gyazo.com/281c39fb795be9f52c1124ee7c1051d7

Is this the same issue or something different? I just in case ask. I personally havent seen that flickering, only conduits disapearing.

**Comment by Teksid** [comment] 2015-11-04 17:46
@JasonMcRay I have some conduits that flicker, but not that quickly. In my case I have some conduits connected to a Mekanism Electrolytic Separator, and when it's active it emits light. It consumes brine much faster than I can produce, so its light flickers on and off. If I stand in a different chunk and look at it, the conduits will flicker on and off with the light.

I've also found what seems to be a 100% reproduction method of the general disappearing conduits. Seems to be related to Carpenter's Blocks. Place a few of any type of conduit across a chunk border. Then place any Carpenter's block along the same border, but in the chunk you're standing in. The conduits in the other chunk will disappear. Break the Carpenter's block and they will reappear. I took a few screenshots if that doesn't make sense: http://imgur.com/a/ye1aW

**Comment by HenryLoenwind** [comment] 2015-11-04 18:43
It might be interesting (but nothing more) to notify the authors of the mods that cause this that they are bleeding a te render pass. But from our side the bug has a fix that'll hopefully be in the next version. tterrag is just busy with Real Life(tm) and stuff.

For mod devs: ForgeHooksClient.get/setRenderPass() will get/set the (Tile)Entity render pass, not the block render pass. It also is mostly uninteresting. You want ForgeHooksClient.getWorldRenderPass(). And clean up after you set it! For both of them. (For more details read the Minecraft code. All IDEs have a way of showing you which code is calling some method, in Eclipse it's called "Open Call Hierarchy".)

**Comment by Teksid** [comment] 2015-11-07 19:51
Looks like this is indeed fixed in 418

**Comment by JasonMcRay** [comment] 2015-11-07 20:19
I can confirm it seems much much better. Will keep an eye on any oddities... Thanks @HenryLoenwind :)

**Closed** 2016-05-28 09:54 UTC
Labels: bug, Code Complete
