### ISSUE TITLE
Lag Spikes

### ISSUE THREAD

**Issue by yaxley** [SleepyTrousers/EnderIO#4875] opened 2018-09-20 18:07 UTC
#### Issue Description:

There are constant extreme lag spikes. Without the mod fps is mostly stable on 60 fps, sometimes dropping to 50. With the mod, the fps sometimes drops to 9 fps or less. 

#### Steps to reproduce:

It was a fresh world, so no machines where in the world.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO Base: 5.0.33
- EnderCore: 0.5.39
- Minecraft: 1.12.2
- Forge: 14.23.4.2760
- SpongeForge? no
- Optifine? /no
- Single Player

#### Other Mods

- MoVillages
- AbyssalCraft
Aether
AppleCore
AppleSkin
ArmorPlus
AstralSorcery
AutoRegLib
BetterSprinting
BiblioCraft
BloodMagic
Bloodmoon
Botania
Chameleon
ChiselsAndBits
CodeChickenLib
CoFHCore
CoFHWorld
CraftTweaker
Cucumber
DamageControl
DungeonTactics
Electroblob's Wizardry
EmbersRekendiled
EchantmentDescriptions
ExtendedCrafting
FastWorkbench
Fencejumper
GalacticraftCore
Galacticraft-Planets
GalacticraftTweaker
Gravestone
GrimoireOfGaia3
Guide API
HeroicArmory
HorsePower
HungerOverhaul
IceAndFire
ImmersiveEngineering
ImmersivePetroleum
InControl
JEI
JourneyMap
LootTweaker
Mantle
MaterialChanger
MCMultiPart
MicdoodleCore
ModTweaker
MTLib
NetherEx
NoRecipeBook
Nutrition
Orbis
Pam's Harvestcraft
Placebo
Quark
RedstoneFLux
Roguelike Dungeons
Rustic
SaltyMod
ScalingHealth
SilentLib
StorageDrawers
TConstruct
Thaumcraft
ThaumicJEI
Betweenlands
DragonLIb
OneProbe
ThermalDynamics
ThermalExpansion
ThermalFoundation
TinkersComplement
Toast Control
TwilightForest
ViesCraft
VillagerTrades
DefiledLands

**Comment by tyler489** [comment] 2018-09-20 18:16
Yeah.. its not enderio causing that if there are no machines... try a profiler mod to see what your culprit is.

**Comment by HenryLoenwind** [comment] 2018-09-20 18:27
Use the vanilla profiler (Shift+F3) to drill down to the source.

**Comment by yaxley** [comment] 2018-09-20 19:00
I did some more tests. The lag seems to be caused by ender io and some other mod. The lag is always there when I ad ender io to this mod pack, but in some other mod packs I use it does not exist. I tried to find the culprit, but so far no luck. Will try again tomorrow.

**Comment by JoellenTrollen** [comment] 2018-12-30 16:54
I could've searched for days and still haven't found a fix for this, thanks! I got the 5.0.36 version and it also produced the same solution. Still a downside since I'm missing most of the bug fixes in the latest versions but it's manageable.

**Comment by mrAppleXZ** [comment] 2018-12-30 17:53
Maybe the issue is somehow related to this one: https://github.com/SleepyTrousers/EnderIO/issues/4990?

**Closed** 2020-06-05 15:14 UTC
Labels: 1.12
