### ISSUE TITLE
conduit becomes invisible with redstone signal

### ISSUE THREAD

**Issue by jdratlif** [SleepyTrousers/EnderIO#3950] opened 2016-12-27 04:26 UTC
I have a clear dark glass façade on an insulated redstone conduit with a lever on top. If the lever is on, the conduit connector becomes invisible in the façade, unless you are holding the yeta wrench, but when the lever is off, the connector is rendered.

Forge 2185
MC 1.10.2
EnderIO 3.0.1.145
EnderCore 0.4.1.61

https://postimg.org/image/5lu2zhj61/ - Lever Off - Conduit Rendered
https://postimg.org/image/nsjtvr25r/ - Lever On - Conduit Invisible
https://postimg.org/image/45lz0t1c9/ - Lever On w/ Yeta - Conduit Rendered Again

**Comment by PapiDimmi** [comment] 2017-04-11 18:52
The screenshots are now unavailable.

**Comment by HenryLoenwind** [comment] 2017-04-11 21:12
This may be a dupe of another bug I fixed in the meantime. Please re-test with the current version, thx.

**Closed** 2018-06-20 18:32 UTC
Labels: 1.10, Waiting For Feedback
