### ISSUE TITLE
Include ComputerCraft Networking Cable

### ISSUE THREAD

**Issue by angelnc1989** [SleepyTrousers/EnderIO#46] opened 2013-09-06 11:22 UTC
I'm building my new base right now where I try to hide all cables and make everything as compact as possible. There I just realised, that there is no way to facade Networking Cables from ComputerCraft. So it would be really cool to have them added to this mod.

**Comment by beringtom** [comment] 2015-05-12 16:10
I'm bumping this just because the CC cables does not support Forge MultiParts right now.

**Comment by MatthiasMann** [comment] 2015-05-12 17:05
CC cables are very unlikely - but OC cables are on the road map.

**Comment by Vexatos** [comment] 2015-05-12 17:37
Duplicate of #2288, #725.

**Comment by Vexatos** [comment] 2015-05-12 17:38
It is virtually impossible to do anything with CC cables at all as there is no real way of properly accessing them, unfortunately.

**Closed** 2016-05-28 13:08 UTC
Labels: enhancement
