### ISSUE TITLE
Issue between Actually Additions Fermenting Barrel and EnderIO Conduits 1.10.2

### ISSUE THREAD

**Issue by Tylerun** [SleepyTrousers/EnderIO#4316] opened 2017-08-17 21:19 UTC
#### Issue Description:
Conflict between Actually Additions fermenting Barrel and Enderio Pipes. Server crashes upon login.

#### What happens:
When connecting to a server the server crashes.

#### What you expected to happen:
Login play have fun. 
____
#### Affected Versions (Do *not* use "latest"):
EnderIO: 1.10.2-3.1.193
EnderCore: 1.10.2-4.1.66
Minecraft: 1.10.2
Forge: 12.18.3.2422

#### Your most recent log file where the issue was present: 

http://prntscr.com/g9syyy
http://prntscr.com/g9t18k

**Comment by GuntherDW** [comment] 2017-08-17 21:28
Duplicate of #4315

**Closed** 2017-08-17 21:42 UTC
Labels: 1.10, Duplicate
