### ISSUE TITLE
conduits dont work correctly

### ISSUE THREAD

**Issue by bigpodgurc** [SleepyTrousers/EnderIO#3943] opened 2016-12-23 23:01 UTC
#### Issue Description:
some conduit connections work some dont

#### What happens:

i have conduit network for my farm and couple of item conduit do not wanna accept items to send them only one does im using farming station

#### What you expected to happen:

that all Will work

#### Steps to reproduce:
dont know how to reproduce it took me like couple of days to build this farm so networking is complex
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:1.1.0.2-3.0.1.145
- EnderCore:1.10.2-2.2.0.96
- Minecraft: 1.7.10
- Forge:12.18.3.2185

**Comment by UntouchedWagons** [comment] 2016-12-25 04:38
Are the item conduits crossing a chunk border? I'm having an issue with item conduits too.


* EnderIO:1.1.0.2-3.0.1.144
* EnderCore:1.10.2-0.4.1.61-beta
* Minecraft: 1.10.2
* Forge:12.18.3.2185

**Comment by VT-14** [comment] 2016-12-26 13:55
Neither report has the requested FML logs.  There's also not enough information to try to recreate the issue, or to point out potential mistakes.  Pictures would help a LOT in this case.

**Comment by UntouchedWagons** [comment] 2016-12-26 15:19
Well I'm playing on a server but I'll try to replicate it in single player

**Comment by MysticAura** [comment] 2016-12-27 14:01
I've had a really rough time with conduits lately as well. They're completely disregarding priority and I often have to break and replace them to get them to start functioning again at all. SSP and SMP, multiple different setups.  There is nothing in any of the logs concerning the issue at all. It's not a case of not being set up right when I can break replace and suddenly they're working again. However, even then the priority is getting ignored completely.

One of my tests last night was having a mod filter on an rftools storage, negative priority to catch overflow of vanilla items.. and an AA large crate set at high priority to take all the golden armor.  The armor goes into the rftools storage first every time.

**Comment by aaronmallen** [comment] 2016-12-28 01:23
What I am seeing is item conduit completely stop working when chunks are loaded. 

Steps to reproduce:
1. Setup an Actually Additions empowerer
2. Configure empower to accept crystalized canola seeds, configure display stands to accept canola seeds
3. Unload the chunk by going to another dimension or logging off
4. Come back and try to feed the empower the appropriate seed products.

Result: display stands or empowerer (its kind of random) will not be fed seeds from the chest/source.

you can work around this simply by removing an item conduit and replacing it.

Another reporduction example:  
1. Setup a farming station
2. Setup a crafter to make hoes and axes
3. Feed the crafter and a drawer controller the output of the farming station with item conduit. The crafter should have a higher priority than the draw controller. The farming stations should output on the green channel and accept input from the crafter on the red channel
4. Unload the chunk by going to another dimension or logging off
5. Reload the chunk

Result: The farming station will not feed its output to the item conduit network
This can also be worked around simply by removing a single item conduit on the network and replacing it.

**Comment by davelien** [comment] 2016-12-28 03:15
I have experienced the same problem seen by @aaronmallen, with item conduits not passing items, randomly, with the Actually Additions empower setup.  I have also experienced a problem with the Actually Additions farmer not exporting items through conduits.  Breaking and replacing the conduit fixes the issue every time.  I had not associated chunk loading with the issue but have noticed the problem immediately after logging in to a game.  I too am willing to provide additional details.

I am using EnderIO - 1.10.2-3.0.1.147_beta

**Comment by DietmarKrause** [comment] 2016-12-28 08:34
@aaronmallen completly agreed and confirmed. Same problem here. I personly think it to be a problem of chunc loading. I simply break a single item conduit from my farm to the output chest and replace it then everything is fine. I havent tried a chunc loader though.

**Comment by MysticAura** [comment] 2016-12-28 14:20
I also believe it's tied to chunk loading in most cases. Botania is having a similar problem with mana spreader chains when in non chunk loaded areas. Have to break and replace in that instance as well.

**Comment by tgstyle** [comment] 2016-12-28 18:01
Can confirm when leaving an area and coming back, conduits disconnect across chunk borders, replacing a conduit in the line, any conduit seems to "reconnect" them all. Chunk loading does not appear to have an effect either way for me.

**Comment by Aulweas** [comment] 2016-12-28 19:44
I have started having the same issue with the DW20 pack.  It seems to have started with the 1.1.1-1.10.2 (beta) update.  I updated my pack originally and built an Actually Additions empowerer and used Enderio conduits for some basic automation.  I went AFK and when I came back the conduits under the empowerer were corrupt.  They were being represented by squares inside of squares.  I didn't screen shot it, nor could I break them or interact with them with the Yeta wrench. I had to revert to a previous save prior.  

I recreated the empowerer again, and this time it worked fine.  I am now experiencing other issues with SAG Mills, Alloy Smelters, and Farming Stations not extracting to EnderIO conduits.  Most of my conduits are attached to Refined Storage interfaces at some location.  Because of this layout some parts of my base work, while others don't. 

 I currently have a farming station that is connected directly into a vanilla chest.  It wont output the netherwart into the chest.  I have replaced the farming station 3x, and the conduits at the connection (As this has fixed similar issues) points multiple times.  This is maintained in a single chunk, that is not chunk loaded.  But doesn't work when I stand next to it.  Nothing is fixing it.  

Also I apologize, but if someone could explain how to post my logs I will be more than willing.

**Comment by davelien** [comment] 2016-12-30 02:26
An update.  I just now noticed the same issue with Redstone conduit, redstone signal was not being passed.  I broke and replaced a single piece of redstone conduit (Insulated Redstone Conduit) and was back up and running.

Ender IO 1.10.2-3.0.1.147_beta
Ender Core 1.10.2-0.4.1.61-beta

**Comment by HenryLoenwind** [comment] 2016-12-30 12:53
First, conduits are multi-blocks. And having one half of the multi-block in a loaded and the other half in an unleaded chunk will at very best load and unload the "unloaded" chunk once per tick. Worst case is that things break. That usually works fine at the edge of the loaded area (chunks here get loaded in and out all the time, even from vanilla blocks on the edge). But if you chunkload an area, always chunkload your conduit networks completly. (This is per conduit type.)

Second, I added some debugging code. Starting with the next build (3.0.1.150) you can create diagnostics data by right-clicking a conduit with a stick. Please do so with a couple of conduits that are dead and send me the output from your client logfile. Please also add a screenshot and give some info so I can map the lines to the conduits on the picture.

**Comment by Aulweas** [comment] 2016-12-30 17:48
First, thank you. I have had my base completely chunck loaded, and experienced issues, and now completely unloaded. I was always using the built in ftb system of claiming your chunks and chunk loading them. I have since reinstalled the DW20 pack, upgraded a majority of the mods to newer versions, and am still experiencing this issue, however it isnt nearly as finiky to resolve when i log in.

 In regards to helping debug, i will do anything you need. I am addicted to my EnderIO and im not sure i could play without them at this point.

**Comment by HenryLoenwind** [comment] 2017-01-02 13:31
@tgstyle Do I see this correctly: The fluid conduit network only consists of two conduits? Is that as it should be or should it connect to those other fluid conduits, too?

If it is as it should and just doesn't work:

Can you make it break "on command"? Meaning, does it break every time you leave and come back? In that case, I'd be interested in the log from the same conduit once before it breaks and then after it breaks. (Background: There is a valid network and I need to find out why it doesn't do anything.)

If the visual representation is in the same "broken" state:

Then I need to log diagnostics for something else. (Background: I need to find why the network is split.)

**Comment by tgstyle** [comment] 2017-01-02 16:39
Yes the 2 fluid conduits shown are the ones that are broken (this is just one representation of the many that break), the others are disconnected because they are not in use yet. I can make it break on command by leaving the area and coming back. I will do a before diagnostic and send that to you.

**Comment by tgstyle** [comment] 2017-01-02 17:26
Here is a log before it breaks https://gist.github.com/tgstyle/1aa45db9e0d2b77a3d669df90eb3bd19

I will try to get a before and after when I have more time.

**Comment by davelien** [comment] 2017-01-02 19:02
For what it is worth I have not seen had the problem reoccur since chunk loading my entire base.

**Comment by DietmarKrause** [comment] 2017-01-02 19:12
same here. But i have seen problems with the ftb chunk loading. I use chicken chunc chunc loader. Since the no problem.

**Comment by tgstyle** [comment] 2017-01-03 06:44
Took almost an hour for it to break this time, here are the outputs. This example just used the 2 fluid conduits, I removed the item conduit.

Working
https://gist.github.com/tgstyle/3971cb73fb42daa0184fa7e28385630d

Not Working
https://gist.github.com/tgstyle/c87ab56d9be15815eec3ba847a192103

**Comment by HenryLoenwind** [comment] 2017-01-03 06:56
Thanks, @tgstyle. Just to clarify, this was with the chunk not chunkloaded, so you left and the conduits should have been unloaded at least once between those logs?

**Comment by tgstyle** [comment] 2017-01-03 07:36
Yes, this time everything was not chunk loaded.

**Comment by Armitige** [comment] 2017-01-04 06:19
I'm having a similar issue, except it's not related to chunk borders. It concerns item conduits and Botania red stringed containers. When I initially place item conduits next to red stringed containers, they connect fine, and input/output as expected, but as soon as I log off and back on again almost all item conduit connections with the red stringed containers lose connection.

**Comment by MatthiasMann** [comment] 2017-01-04 07:25
@Armitige that sounds like the red string containers are not ready (eg don't expose an inventory) when the chunk gets loaded and do not issue a neighbor change event once they do. This is also a problem I have seen with some multi blocks of other mods.
Does that conduit connect once you place a block (eg dirt) next to it? If so  then best to report that to Botania too.

**Comment by Ricket** [comment] 2017-01-07 18:12
I recorded a video of the conduits not working, and then at the end I break and replace a random conduit piece and the whole thing starts working (just luck, I did not expect it). https://youtu.be/Yfy1w2d1788

**Comment by Armitige** [comment] 2017-01-10 17:06
@MatthiasMann no, the only thing that fixes it is breaking and replacing each conduit that connects to the red stringed containers.

**Comment by Aulweas** [comment] 2017-01-10 19:51
So I recently updated my DW20 pack to the 1.3.2 version.  The patch notes mention quark world gen has been disabled as a hotfix.  Ever since I updated my game I am no longer having issues with my ender io conduits, or my cursed earth spawn stopping.  I have only spent maybe 4 hours playing since updating, so I am curious if anyone else has had my good fortune?

**Comment by Ricket** [comment] 2017-01-10 23:25
My video was recorded with the 1.3.2 version of the pack. See the version numbers in #3978... I even hit this issue again earlier today, different section of conduit but it was not moving items, and when I broke & replaced one piece of conduit it started working.

**Comment by Elvarion** [comment] 2017-01-11 22:20
We are running the Resonant rise pack and also getting this issue from time to time.
So what I did as a "solution" was placing a Online Detector with my name in it, this triggers a block breaker and a block placer that breaks the conduit line that's misbehaving. So every time I login this will trigger. Then I got an Entity Detector from Draconic Evolution that is semi-centered around the conduit lines. This also will detect me, So whenever I leave the area and then come back it will break and replace a part of the conduit.

This has not failed me yet and been working for about 3 days now.
Not really a permanent solution, but it works for now for me ^^

**Comment by notacompletemoron** [comment] 2017-01-14 16:49
I'm having an issue where the item conduits aren't working past a chunk border.

I originally set it up with EnderIO-1.10.2-3.0.1.149_beta (working) then updated to EnderIO-1.10.2-3.1.156 (broken).

**Comment by fury0n** [comment] 2017-01-15 11:09
Much like notacompletemoron said, I am also experiencing issues with the item conduits past chunk borders.

Currently using EnderCore-1.10.2-0.4.1.62-beta.

This is however not anything that always has been an issue as I ran a previous version for ~3 weeks before the issues started, something triggered it. I've tried backtracing but have had no luck.

**Comment by duckzeus** [comment] 2017-01-17 20:39
Having the same issue.  All item conduits set to extract stop working when game is shut down and restarted.  

In my world all chunks with conduits are chunkloaded and no conduits cross chunk boundaries.

Happy to pull whatever info would help in this instance

**Comment by Aulweas** [comment] 2017-01-20 00:15
I did a fresh install roughly 11 days ago and it solved my problems.  I updated the DW20 pack tonight and introduced this issue once again in my world.  The issue was in place when I loaded into my world, I fixed it by braking a conduit and replacing it.  When I left the area and came back the problem existed again.  I am going to do another fresh install and migrate my save to see if that fixes it again.

**Comment by Ricket** [comment] 2017-01-20 01:19
When you say "fixed the issue" what do you mean? In my experience this issue is intermittent, are you reloading the world multiple times to test it?

**Comment by Aulweas** [comment] 2017-01-20 01:41
I had loaded up multiple times and teleported away from my base multiple times.  However, I just got back from mining and I noticed my power was off.  So it isn't fixed

**Comment by Aulweas** [comment] 2017-01-20 17:41
So I use the FTB chunk loading system to chunk load my base.  I just went into the system and unclaimed all my chunks and exited out of Minecraft.  I then copied my save and deleted the instance of Minecraft and did a fresh install (Most updated version of DW20 1.3.2). I entered the game and reclaimed and chunk loaded my base and now the conduits seem to be working....Well they were working as advertised when I logged into the game, and thats not typical.  I usually have to break a conduit (it doesn't matter what one) to get it to work.  I haven't extensively tested this yet (I've portaled away from my base for 20 minutes  and loaded into the game 3 times), but as of now it is working.  It would be beneficial to have more people look into and see if it is a temp solution, or I am just getting lucky.  This could be a corruption issue when updating mod packs and how FTB uses a team system and chunk loading work.  It may be as simple as entering console commands to delete and reform teams to fix the issue.  My knowledge is limited and would appreciate any input.

Again I jumped the gun earlier thinking I made some headway.  If anyone else is able to help debunk me again it would be greatly appreciated.

**Comment by Ricket** [comment] 2017-01-21 03:24
I think there needs to be some EnderIO change to fix it. However I've had better luck with using a Persistent Bits chunk loader. I disabled the FTButils chunk loading and use those instead.

**Comment by CharZinta** [comment] 2017-02-08 00:09
I can comment that we are experiencing this on our custom mod pack as well. I have an EIO farming station that is getting its power from simple generators: furnace generator. I'm using a RFTOOLS crafter to make axes and send them to the farming station. The farming station takes saplings and logs sending them down to be converted, saplings are secondary power and logs become planks. 

As long as the chunk is loaded everything works great if the chunk becomes unloaded for any reason I have to break each cable and replace it to get it to start working again.  I have to not place the advanced item filter back into the conduit or they won't work at all. 

After much testing I've managed to isolate the problem to the advanced item ducts. I setup a system with only 1 advanced item duct and separate paths for each process as much as I could. After 3 load/unloads and one server reboot things are still working.

Farming station sends saplings and logs down Item conduit, one advanced picks up the saplings and the logs go to the tier 1 crafter. The logs become planks which feed the furnace generator and go to another chest.  The second chest feed's planks to a tier 1 crafter for sticks, which has an item conduit feed for cobble stone as well. These max axe's which then feed the farming station. All this works unlike my other setup that is one solid line of EIO item conduit and a dozen furances, two crafters, two farming stations, and some other items to keep the "loop" working.

http://prntscr.com/e5veh9

http://prntscr.com/e5vf8r

**Comment by MatthiasMann** [comment] 2017-02-08 07:04
@CharZinta that image hosting site is the most terrible one available - it needs tons of javascripts from all over the internet before it displays anything.

**Comment by CharZinta** [comment] 2017-02-10 13:46
@MatthiasMann  Never had a problem but then I use a blocker to stop random javascript and ad's from ruining my browsing experience

 please provide a suggested alternative.

**Comment by Elvarion** [comment] 2017-02-10 17:27
@CharZinta Ive been using Gyazo since 2013 and its been working solid for me and the places I use my links for. Might be worth checking out

**Comment by ktole1999** [comment] 2017-02-15 18:29
is there any update on addressing this issue?

**Comment by HenryLoenwind** [comment] 2017-02-15 18:33
I think this may be the same as https://github.com/SleepyTrousers/EnderIO/issues/3873

And no, that debug output did not show anything that might help to find the problem.

**Comment by ktole1999** [comment] 2017-02-15 18:48
hope the resolution surfaces soon, thanks for all you do.

**Comment by neograymatter** [comment] 2017-03-12 12:07
I have been seeing this issue as well on my server. If a chunk containing conduits is unloaded then reloaded often all the conduits will "freeze" and stop working until broken and replaced. This can happen even if conduit system is constrained to a single chunk. A very similar fault is happening with IC2 cables and on my server both the ender IO conduits and ic2 cables in a chunk have been breaking at the same time. Related IC issue : http://bt.industrial-craft.net/view.php?id=1959

**Closed** 2017-05-05 17:44 UTC
Labels: 1.10, Waiting For Feedback
