### ISSUE TITLE
SAG Mill - Producing Gravel named "Invalid OreDictionary Tag"

### ISSUE THREAD

**Issue by JasonMcRay** [SleepyTrousers/EnderIO#2776] opened 2015-09-06 17:38 UTC
As Title says. When I process Cobblestone inside SAG Mill, it will give me:

1) Sand (with wierd meta as well - 32797 - it is shown also in the Recipes)
2) Gravel (with name Invalid OreDictionary Tag)

I made sure that I am not adding or changing anything related to this proccessing via user configs.

Tested with:
EnderIO: 2.3.0.413_beta
EnderCore: 0.1.0.23_beta
Inside InfiTech 2 modpack

**Comment by tterrag1098** [comment] 2015-09-06 17:44
Duplicate of #2751

**Comment by mmelvin0** [comment] 2015-09-06 20:15
FYI, not actually a duplicate. `sand` is in the ore dictionary, `gravel` is not.

**Comment by JasonMcRay** [comment] 2015-09-12 19:32
@tterrag1098 Why has it been flagged as duplicate? Its not a duplicate. Well not completely. #2751 is about the Sand with wierd metadata, but I have an issue with cobblestone making on top of that "Invalid Oredictionary TagL type of gravel.

Also just downloaded latest eIO (2.3.0.415) and #2751 is fixed but this is not.

**Comment by tterrag1098** [comment] 2015-09-12 20:43
I figured it was the same thing, but since it's not I'll reopen.

**Closed** 2016-05-28 12:37 UTC
Labels: Bug Mod integration
