### ISSUE TITLE
XP Obelisk not draining XP in survival on server

### ISSUE THREAD

**Issue by djpadbit** [SleepyTrousers/EnderIO#5487] opened 2020-12-03 23:23 UTC
#### Issue Description:

The XP Obelisk doesn't work when putting xp into it in multiplayer. It only does it in survival.

#### What happens:

Nothing

#### What you expected to happen:

It drains the XP from the player and puts it in the obelisk

#### Steps to reproduce:

1. Install EnderIO on a server
2. Place an XP Obelisk
3. Try to put XP into it in survival

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.2.66
- EnderCore: 0.5.76
- Minecraft: 1.12.2
- Forge: 14.23.5.2854
- SpongeForge? no
- Optifine? yes
- Single Player and/or Server? Server

#### Your most recent log file where the issue was present: 

[Snippet from the server i'm playing on](https://pastebin.com/3EQe4hmh)
[Snippet from a test server with only EnderIO](https://pastebin.com/LNiyzkdu)

**Comment by Feta** [comment] 2020-12-04 13:28
Error executing task
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
        at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_261]
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_261]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:310) [SpongeImplHooks.class:1.12.2-2838-7.3.0]
        at net.minecraft.server.MinecraftServer.redirect$zjg000$onRun(MinecraftServer.java:4682) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
        at crazypants.enderio.machines.machine.obelisk.xp.ContainerExperienceObelisk.doDrainXP(ContainerExperienceObelisk.java:66) ~[ContainerExperienceObelisk.class:?]
        at crazypants.enderio.machines.machine.obelisk.xp.ContainerExperienceObeliskProxy$doDrainXP.lambda$apply$1(ContainerExperienceObeliskProxy$doDrainXP.java:38) ~[ContainerExperienceObeliskProxy$doDrainXP.class:?]
        at crazypants.enderio.base.network.ExecPacket$Handler.onMessage(ExecPacket.java:78) ~[ExecPacket$Handler.class:?]
        at crazypants.enderio.base.network.ExecPacket$Handler.onMessage(ExecPacket.java:73) ~[ExecPacket$Handler.class:?]
        at com.enderio.core.common.network.ThreadedNetworkWrapper$Wrapper$Runner.run(ThreadedNetworkWrapper.java:119) ~[ThreadedNetworkWrapper$Wrapper$Runner.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_261]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_261]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 7 more
[08:27:13] [Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
        at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_261]
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_261]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:310) [SpongeImplHooks.class:1.12.2-2838-7.3.0]
        at net.minecraft.server.MinecraftServer.redirect$zjg000$onRun(MinecraftServer.java:4682) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
        at crazypants.enderio.machines.machine.obelisk.xp.ContainerExperienceObelisk.doDrainXP(ContainerExperienceObelisk.java:66) ~[ContainerExperienceObelisk.class:?]
        at crazypants.enderio.machines.machine.obelisk.xp.ContainerExperienceObeliskProxy$doDrainXP.lambda$apply$1(ContainerExperienceObeliskProxy$doDrainXP.java:38) ~[ContainerExperienceObeliskProxy$doDrainXP.class:?]
        at crazypants.enderio.base.network.ExecPacket$Handler.onMessage(ExecPacket.java:78) ~[ExecPacket$Handler.class:?]
        at crazypants.enderio.base.network.ExecPacket$Handler.onMessage(ExecPacket.java:73) ~[ExecPacket$Handler.class:?]
        at com.enderio.core.common.network.ThreadedNetworkWrapper$Wrapper$Runner.run(ThreadedNetworkWrapper.java:119) ~[ThreadedNetworkWrapper$Wrapper$Runner.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_261]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_261]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 7 more
[08:27:14] [Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
        at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_261]
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_261]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:310) [SpongeImplHooks.class:1.12.2-2838-7.3.0]
        at net.minecraft.server.MinecraftServer.redirect$zjg000$onRun(MinecraftServer.java:4682) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
        at crazypants.enderio.machines.machine.obelisk.xp.ContainerExperienceObelisk.doDrainXP(ContainerExperienceObelisk.java:66) ~[ContainerExperienceObelisk.class:?]
        at crazypants.enderio.machines.machine.obelisk.xp.ContainerExperienceObeliskProxy$doDrainXP.lambda$apply$1(ContainerExperienceObeliskProxy$doDrainXP.java:38) ~[ContainerExperienceObeliskProxy$doDrainXP.class:?]
        at crazypants.enderio.base.network.ExecPacket$Handler.onMessage(ExecPacket.java:78) ~[ExecPacket$Handler.class:?]
        at crazypants.enderio.base.network.ExecPacket$Handler.onMessage(ExecPacket.java:73) ~[ExecPacket$Handler.class:?]
        at com.enderio.core.common.network.ThreadedNetworkWrapper$Wrapper$Runner.run(ThreadedNetworkWrapper.java:119) ~[ThreadedNetworkWrapper$Wrapper$Runner.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_261]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_261]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 7 more

Same issue

**Comment by 811Alex** [comment] 2020-12-07 12:39
I can also confirm this, reproducible with just enderio (latest) on survival, tested on a server, the only thing that happens is that the server throws an exception every time you press the button on the gui, no xp gets transferred, here's mine:
```[13:32:46] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_191]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_191]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
	at crazypants.enderio.machines.machine.obelisk.xp.ContainerExperienceObelisk.doDrainXP(ContainerExperienceObelisk.java:66) ~[ContainerExperienceObelisk.class:?]
	at crazypants.enderio.machines.machine.obelisk.xp.ContainerExperienceObeliskProxy$doDrainXP.lambda$apply$1(ContainerExperienceObeliskProxy$doDrainXP.java:38) ~[ContainerExperienceObeliskProxy$doDrainXP.class:?]
	at crazypants.enderio.base.network.ExecPacket$Handler.onMessage(ExecPacket.java:78) ~[ExecPacket$Handler.class:?]
	at crazypants.enderio.base.network.ExecPacket$Handler.onMessage(ExecPacket.java:73) ~[ExecPacket$Handler.class:?]
	at com.enderio.core.common.network.ThreadedNetworkWrapper$Wrapper$Runner.run(ThreadedNetworkWrapper.java:119) ~[ThreadedNetworkWrapper$Wrapper$Runner.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_191]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more```

**Comment by RandomExplosion** [comment] 2021-01-05 01:28
@HenryLoenwind will the next release be for 1.12.2?

**Comment by Lordfirespeed** [comment] 2021-01-09 00:26
When is the new version of the mod including this fix going to be released?

**Comment by TaiyouAkira** [comment] 2021-01-17 15:19
Hello, have the same problem.
How do I fix this ?
Im playing on Infinity Evolved Reloaded :)

**Comment by bigenergy** [comment] 2021-03-19 15:20
Same problem

**Comment by ForcePush** [comment] 2021-03-30 13:16
As a workaround you can Shift+RMB the obelisk with an Experience Rod, it will put all your XP into the obelisk.

**Comment by Eden333** [comment] 2021-03-30 13:52
I just use the rod on a portable tank so i could put the liquid in the fluid transposer

**Comment by myoun** [comment] 2021-04-25 13:26
same issue

**Closed** 2021-05-24 19:28 UTC
Labels: 1.12, Code Complete, bug

**Comment by LMWafer** [comment] 2021-07-25 16:29
same problem
