### ISSUE TITLE
Ender io cap bank inventory re-sort bug

### ISSUE THREAD

**Issue by TheDCPlaya** [SleepyTrousers/EnderIO#4010] opened 2017-01-23 15:50 UTC
#### Issue Description:
EDIT- Right clicking a basic capacitor bank with an item in the players hand, rearrannges said inventory

#### What happens:
http://i.imgur.com/VrlgjFy.png

#### Steps to reproduce:

1.have item in hand
2.right click cap bank
3.open inv
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:1.10.2-3.1.156
- EnderCore:1.10.2-0.4.1.64-Beta
- Minecraft: 1.10.2
- Forge:12.18.3.2202

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment] 2017-01-23 16:51
Please describe shat happens exactly. There are some steps between right-clicking a capbank and having the player inventory open.

**Comment by choekstr** [comment] 2017-01-24 17:10
I had this same thing happen with just 1 vibrant cap in a set of 16 that seemed to be corrupted in SF3.  No amount of relogging would fix it but noticed that when I hit the baubles button things went back to normal.  I finally threw the cap away and cheated in another and all was back to normal.  It has been stated that the SimpleLabels quantum storage label causes corrupted chunks and screws up NBT data but I can't find anyone saying that; however this was indeed in a single chunk which is screwed up and has that label in it and most of the conduits are not rendering and working, missing EU2 pipes, etc.  I removed the label and replaced the Cap and it hasn't happened again (although the conduits are all still wireframe and not working until I break and replace but that is another issue).

**Comment by cha0s** [comment] 2017-01-26 08:17
Whoa, I'm getting a similar issue with corruption in sf3 in a single chunk where I have those labels. That's interesting. I wonder if that really is the cause. I'm getting ender IO conduits missing, smeltery rendering strange/desync inventory when interacting with it, crucibles not rendering, etc etc. I know this isn't related to ender IO but I was here looking to see if anything sounded like this bug. Thanks for sharing.

**Comment by cha0s** [comment] 2017-01-26 08:19
Breaking them immediately fixed it too. Wow.

**Comment by choekstr** [comment] 2017-01-26 15:10
The conduits are screwed up when you relog.  However, the SimpleLabels team has committed a fix on github but not sure if it has been compiled and pushed out yet.  The new SF beta 3.0.6 seems to have fixed my issues related to this so either the new simplelabels version has been pushed or me removing the label and upgrading server and client and restarting has removed the corruption in the chunk.

Regardless, I don't think this is caused by anything EnderIO, just a casualty of war.

**Comment by postal291** [comment] 2017-02-15 04:57
I am experiencing this bug as well.  With the Sky Factory 3 modpack (3.0.6), right clicking on a blank face of the capacitor bank (5 mil RF one) to try to get the RF bar indicator connected texture, instantly inventory resorts in messed up way, pickaxe (item 1) goes to offhand, mattock (item 2) goes to main hand, pants on head, wrench invisible, etc... end up having to close and reopen the client to fix.

**Closed** 2017-05-05 17:44 UTC
Labels: 1.10, Cannot reproduce
