### ISSUE TITLE
[1.7.10] Farming station and Growable ore Reeds

### ISSUE THREAD

**Issue by Keyarose** [SleepyTrousers/EnderIO#3360] opened 2016-06-01 22:50 UTC
#### Issue Description:
Updated EnderIO recently and the farming station is no longer planting the ore reeds from B0bGary's Growable Ores, nor is it harvesting any that grow in its range after manual planting.

#### Steps to reproduce:
Setup screenshots:
![2016-06-01_19 41 13](https://cloud.githubusercontent.com/assets/1906772/15728267/dc8644b2-2831-11e6-8585-73521c1cafbf.png)

![2016-06-01_19 41 19](https://cloud.githubusercontent.com/assets/1906772/15728269/dfae1750-2831-11e6-9ec6-b36e623634b1.png)

____
#### Affected Versions:

- EnderIO: 1.7.10-2.3.0.426_beta
- EnderCore: 1.7.10-0.2.0.35
- Minecraft: 1.7.10
- Forge:1566
- Growable Ores: 2.5.4

**Comment by HenryLoenwind** [comment] 2016-06-02 06:28
I read this as a general "farming station stops working", which I tried and failed to reproduce already.

**Comment by tgstyle** [comment] 2016-06-02 21:15
I am also seeing this with 1.7.10-2.3.0.426_beta. I have oak saplings in it and all it says is "No Seeds", I reverted back to 425 and the farming station works perfectly,

**Comment by go371211** [comment] 2016-06-05 19:14
Yah, farming station stops working in 426 beta

**Comment by HenryLoenwind** [comment] 2016-06-13 21:11
link in #3344 and closing as dupe

**Closed by HenryLoenwind** 2016-06-13 21:11 UTC
Labels: 1.7, Cannot reproduce
