### ISSUE TITLE
RF config doesn't update in GUI

### ISSUE THREAD

**Issue by cj89898** [SleepyTrousers/EnderIO#3445] opened 2016-06-24 15:58 UTC
#### Issue Description:
Doesn't update RF/t usage in GUI

#### What happens:
I open the alloy smeltery which i've custom set in the config to use 50 RF/t instead of 20 RF/t but it shows 20 RF/t

#### What you expected to happen:
Show 50 RF/t and scale for each capacitor upgrade.

#### Steps to reproduce:

1. Change config to use something other than 20 RF/t
2. Open GUI
3. Profit? (I joke I joke, but there is no step 3)
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.9.4-3.0.0.45_alpha
- EnderCore: 1.9.4-0.4.0.26_alpha
- Minecraft: 1.9.4
- Forge: 1.9.4-12.17.0.1968

#### Your most recent log file where the issue was present: 

http://paste.feed-the-beast.com/view/9bc90fe8

**Comment by HenryLoenwind** [comment] 2016-06-24 16:04
Please post details of what you've done to configure it and where it shows the wrong value.

**Comment by cj89898** [comment] 2016-06-24 16:21
I just configured the config. It does change the RF/t used, I checked on my capacitor bank. Here is my config: http://hastebin.com/yureloxuyi.vbs

It shows when you hover over the energy bar in the GUI.

**Comment by cj89898** [comment] 2016-06-24 16:25
I will mention this is on SMP. I completely forgot about that since it wasn't a question :L
So I've done some testing and it's issues with the server not syncing to the client. When hovering over the energy bar it uses the client's config.

**Comment by HenryLoenwind** [comment] 2016-06-24 16:29
there's no config syncing for all values, only for a very select few.

**Comment by cj89898** [comment] 2016-06-24 16:30
So this IS a bug? It should be showing the correct amount of RF/t usage on the client, correct?

**Comment by HenryLoenwind** [comment] 2016-06-24 16:32
No, not a bug. It works as intended---configs must match between client and server. There are just too many that are acted upon game start, so they cannot be changed when connecting to a server. This makes syncing very useless. The few we do sync are to prevent immediate crashes.

**Comment by cj89898** [comment] 2016-06-24 16:35
Okay so the visual is just something I have to deal with then. Is there any way you could implement this to be possible? I know it's a bit nitpicky, but it just makes sense that if a server wanted to customize the RF/t usage on their server that it would let the user know that they aren't really using 100 RF/t, but 1000 RF/t.

**Comment by HenryLoenwind** [comment] 2016-06-24 16:36
We could (and more syncing is even on the TODO list). but as I said, the moment the server changes one of the game-startup values, problems will happen.

**Comment by cj89898** [comment] 2016-06-24 16:38
I guess that does make sense. But so far no problems are happening for the config options of RF/t. Just the visual. I don't want to have something implemented that will break the game of course :)

**Comment by HenryLoenwind** [comment] 2016-06-24 17:19
ok, I'm closing this ticket as it's not a bug and the TODO item already exists

**Closed by HenryLoenwind** 2016-06-24 17:19 UTC
Labels: 1.9, Cannot reproduce
