### ISSUE TITLE
Redstone Conduits (Both Types) Don't cause Block Updates

### ISSUE THREAD

**Issue by kitsuneaerin** [SleepyTrousers/EnderIO#2740] opened 2015-08-26 01:13 UTC
The redstone conduits and insulated redstone conduits don't cause block update when they change state. This causes things such as the lights to not turn on or off when the redstone signal's state toggles.

**Comment by srs-bsns** [comment] 2015-08-29 18:30
Recently I have discovered that a similar situation is happening with the control of a Big Reactor.

In my current single player game (using endercore 20 + enderio 408) I have a power monitor set up between a Big Reactor and a capacitor bank, using insulated redstone conduit, to automatically control the reactor turning on and off, but this funtionality is no longer working.
The power monitor is correctly emitting a redstone signal, and the conduit is transferring that signal (visually confirmed by placing vanilla redstone beside the conduit, which lights up), but it will not trigger the reactor's redstone port to turn the reactor on or off.

**Comment by tterrag1098** [comment] 2015-08-29 20:56
What kind of lights? Redstone conduits definitely send out neighbor updates.

**Comment by srs-bsns** [comment] 2015-08-29 22:41
Here you can see a vanilla redstone lamp, and RedLogic lamps.
The redstone conduit will not update the blocks to turn the lamps on, though it does update vanilla redstone:
![](http://i61.tinypic.com/11rvpk3.jpg)

If another block update occurs, such as placing a block beside the lamp, then it will light up:
![](http://i60.tinypic.com/2yyz6ls.png)

**Comment by kitsuneaerin** [comment] 2015-08-30 17:49
This is the same behavior I was experiencing, though I didn't try with plain redstone. It also doesn't seem to matter what kind of light is used, or from what mod.

**Comment by mmelvin0** [comment] 2015-09-04 00:22
I just attempted to update my pack from EnderIO 2.2.8.381 to EnderCore 0.1.0.23_beta and 2.3.0.413_beta and immediately ran into this with my (nearly 100% EnderIO) Enderman farm.

I have a powered spawner and a killer joe on each wall all controlled by a single lever. Everything is EIO, no vanilla (or other kind) of redstone. Switching the lever usually had no effect on the powered spawner or the killer joes - they'd hit me despite turning the lever off and the spawner would keep spawning. As soon as I triggered any kind of block update manually next to a given EIO machine, it would enter the correct state.

**Comment by Liiw** [comment] 2015-09-04 07:43
I ran into the same problem when I updated my pack with "EnderIO-1.7.10-2.3.0.413_beta" and "EnderCore-1.7.10-0.1.0.23_beta.jar ". I had an EIO power meter controlling a Big Reactors reactor via it's redstone port. 

Power storage was measured from two vibrant capacitors. The power meter reads stored power correctly and outputs a redstone signal (I can see the conduit light up) when storage hits the indicated percentage, but the redstone port of the reactor does not activate. I observed that when I broke the conduit segment which is connected to the RS port, the port lights up and also activates the reactor  (probably because there was a conduit segment connected to the reactor wall next to the port by default). I also observed that when placing a section of vanilla redstone dust between the conduit and the reactors RS port, it will work as intended.

I also have a Galacticraft airlock in my base, which is opened with a redstone signal via EIO redstone conduits. Currently this functions as it should. The setup consists of two Project Red illumar buttons which transmit signal via PR red alloy wire to the PR redstone toggle latch. This latch transmits it's toggle signal to EIO redstone conduit which in turn activates the air lock controller.

I can get a workaround for my reactor problem using either MFR rednet cables or PR red alloy wires, but I hope this bug is resolved, because the EIO redstone conduits (and the mod in general) are extremely awesome :)

**Comment by mmelvin0** [comment] 2015-09-05 23:39
Huge thanks to HenryLoenwind for basically fixing this for me once I found the method with the problem.

Also, honestly, tterrag really found the method.

**Comment by MisterObvious25** [comment] 2016-05-20 15:54
I still have the problem where the redstone conduits are not updating properly. There are no other mods installed. Its a test world made especially to test. Versions of the mods are below.

Minecraft 1.7.10
Forge mod loader 10.13.4.1566-1.7.10
EnderIO 1.7.10-2.3.0.425
EnderCore 1.7.10-0.2.0.34

![2016-05-20_17 47 07](https://cloud.githubusercontent.com/assets/19491809/15433625/6425e7a2-1eb3-11e6-901c-f64de3e1813e.png)
![2016-05-20_17 47 17](https://cloud.githubusercontent.com/assets/19491809/15433624/6425be08-1eb3-11e6-980a-9faac517e891.png)
![2016-05-20_17 47 39](https://cloud.githubusercontent.com/assets/19491809/15433626/64261740-1eb3-11e6-82ac-01a423cf1afe.png)
![2016-05-20_17 47 51](https://cloud.githubusercontent.com/assets/19491809/15433627/64267b54-1eb3-11e6-91f0-12f4fabc55eb.png)

**Closed** 2016-05-28 09:54 UTC
Labels: bug, Code Complete
