### ISSUE TITLE
Shift-clicking item stack into invalid/full machine inventory results in the stack moving to different slot in player inventory

### ISSUE THREAD

**Issue by wlhlm** [SleepyTrousers/EnderIO#2997] opened 2015-11-14 00:24 UTC
This is just a minor annoyance, but when I try to shift-click an item stack from the player inventory into an EnderIO machine who's inventory is filled or invalid (as in it doesn't accept the item stack) results in the stack moving slots between hotbar and normal player inventory.

Here's a visualization:
![enderioinventorycut](https://cloud.githubusercontent.com/assets/1928113/11160567/d718e638-8a6b-11e5-8da1-4e89ef8fa809.gif)

The Alloy Smelter only has space left for 32 Gold Ore, when I now try to shift-click a 64-stack of Gold Ore from the hotbar, the remaining item stack gets placed into the player inventory. After that I shift-click a stack from the player inventory, which places the item stack into the hotbar.

This affects Slice'N'Splice, Omni Buffer, Item Buffer, Dimensional Transceiver, Farming Station, Vat, Crafter, Painting Machine, Soul Binder, Killer Joe, Stirling Generator, SAG Mill, Alloy Smelter, every Capacitor Bank.

Vacuum Chest works as expected (probably, because it's a "chest" and not an ISidedInventory).

__Expected Behaviour:__
Don't move the item stack when shift-clicking into a full/invalid inventory (as TE Machines do for example).

EnderIO 2.3.0_418_beta
EnderCore 0.2.0.30_beta
Forge 10.13.4.1558
Minecraft 1.7.10

**Comment by Badcholo** [comment] 2015-11-14 01:58
Isn't that Inventory Tweaks issue?

**Comment by HenryLoenwind** [comment] 2015-11-14 06:42
Nothing to do with invTweaks.

This is "working as intended", but not "as the user expects". However, the expected behavior is to only transfer into one kind of target slot and stop when only a partial stack could be transferred.

**Closed** 2016-06-21 12:49 UTC
Labels: enhancement
