### ISSUE TITLE
Graphic Glitch with Facades and Machines while using a shader

### ISSUE THREAD

**Issue by InvicTech** [SleepyTrousers/EnderIO#4323] opened 2017-08-27 19:11 UTC
#### Issue Description:
Bugged textures for machines and facades

#### What happens:
The machines and facades become reflective and scattered with fine lines of shadow, while using a shader. Seems to be dependent on the time of day.

![2017-08-27_20 52 10](https://user-images.githubusercontent.com/20909194/29753178-0a6c31cc-8b6c-11e7-85d2-5f4533da3836.png)

#### What you expected to happen:

Just render it like the rest

#### Steps to reproduce:

1. Select Seus v11 or Sildurs Extreme Shader with or without volumetric lighting
2. And see for yourself
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-2.3.1.193
- EnderCore: 1.10.2-0.4.1.66-beta
- Minecraft: 1.10.2
- Forge: 12.18.3.2422
- Using a NVIDIA GTX 1070

#### Your most recent log file where the issue was present: 

The Game doesn't crash so I figured that the log wouldn't help much...

**Comment by jacob814** [comment] 2017-12-11 02:03
Is there a fix for this yet? I would love if my machines didn't look like this :I

**Comment by HenryLoenwind** [comment] 2017-12-11 07:53
No idea what's happening there. Our machines are normal json models, we do not mess with the rendering.

**Closed** 2018-06-20 18:31 UTC
Labels: 1.10

**Comment by Pleune** [comment] 2018-11-13 03:17
The same thing happens in TE, [caused by disabled overlays for input/output](https://www.reddit.com/r/feedthebeast/comments/5ma3np/what_is_causing_seus_to_do_this/ddze3tg). Would it be possible and worth it to add an option to disable all overlays?

I tried to make a similar fix like in the link by making all of the overlay textures transparent, but I wasen't able to get it to work... Although I don't really understand what the TE fix actually does.

**Comment by HenryLoenwind** [comment] 2018-11-13 08:32
1. The issue with TE had completely different artifacts (z-fighting)
2. There are no IO-overlays in the pictures above. Also, the artifacts follow the bodies of the machines and are not in the plane of the overlays
3. the overlays are just a normal part of the json model, too. They are not rendered on the same plane as the bodies of the machines.

**Comment by legslikecinderella** [comment] 2019-06-11 21:21
Has this issue been analysed since @InvicTech originally posted it?

Here are 2 more screenshots of EnderIO 1.10.2-3.1.183 with Sildurs Vibrant Shaders 1.21 High (all types, Lite to Extreme, produce the same effect).

<img width="1842" alt="Screenshot 2019-06-11 at 23 14 20" src="https://user-images.githubusercontent.com/12115715/59307426-c89d8a80-8c9e-11e9-9b2f-cdbdd434bf9d.png">
<img width="1842" alt="Screenshot 2019-06-11 at 23 14 01" src="https://user-images.githubusercontent.com/12115715/59307428-c89d8a80-8c9e-11e9-83f2-0623057416fb.png">

**Comment by HenryLoenwind** [comment] 2019-06-11 22:03
> Our machines are normal json models, we do not mess with the rendering.

still true...

**Comment by legslikecinderella** [comment] 2019-06-11 22:08
What could be different in the EnderIO json models, compared to e.g. TE models, that would cause a shader to render like this?

By the way, I noticed some Extra Utilities 2 1.5.2 machines causes the same rendering issue.

**Comment by HenryLoenwind** [comment] 2019-06-11 22:40
I have absolutely no idea as I know nothing at all about shaders...

**Comment by InvicTech** [comment] 2019-06-13 16:12
@legslikecinderella 
If I were you, I'd just move onto 1.12.2. More or less all mods were updated for this version and work much better. And the render issues also stopped occurring in my case ;D

**Comment by legslikecinderella** [comment] 2019-06-14 10:01
Good advice, thanks
