### ISSUE TITLE
Mod conflict with Pams cooking tools

### ISSUE THREAD

**Issue by TLOU15** [SleepyTrousers/EnderIO#2604] opened 2015-06-24 03:42 UTC
EnderIO-1.7.10-2.2.8.381
Pam's HarvestCraft 1.7.10i

Um I don't have any sort of log for you unfortunately, when I have tried to put a recipe in the crafter that uses one of the cooking equipment from Pams Harvestcraft everything just freezes. 
I tried putting it in the right side directly, I tried putting in a chest to the right side configured to push/pull, in single item and in stack mode. 

The recipes I tried were to make salt from fresh water with the pot and to make dough with the mixing bowl. Each time what ever configuration I tried as soon as the pot or mixing bowl got into the crafter the sound system and animals would stop. I wouldn't be able to open any ender IO machines, vanilla furnaces or chests. I was able to open some of the machines from Pams mod but they were not working. My MultiMC console stopped updating and I could hit esc but I could not save and quit minecraft would simply go to not responding. I had to kill minecraft each time this happened.

**Comment by tterrag1098** [comment] 2015-06-24 03:46
Duplicate of #2552

**Closed by tterrag1098** 2015-06-24 03:46 UTC
