### ISSUE TITLE
AgriCraft crash on Ender IO

### ISSUE THREAD

**Issue by Mrorik1** [SleepyTrousers/EnderIO#5571] opened 2022-07-20 04:35 UTC
#### Steps to reproduce:

1.open Server
2.place enderio:block_farm_station and agricraft:crop_sticks
3.Plant crops on the agricraft:crop_sticks
4.Crop ripening. enderio:block_farm_station harvest it
5.Crash(Boom!)
____
#### Affected Versions (Do *not* use "latest"):
- EnderIO:EnderIO-1.12.2-5.3.70
- EnderCore:EnderCore-1.12.2-0.5.76.jar
- Minecraft:1.12.2
- Forge:[emm?Server have Forge?How can I check it?]
- SpongeForge? no
- Optifine? no
- Server

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]
[crash-2022-07-20_08.45.12-server.txt](https://github.com/SleepyTrousers/EnderIO/files/9146547/crash-2022-07-20_08.45.12-server.txt)

**Comment by LumberWizard** [comment] 2022-07-20 11:12
Duplicate of #5532.

**Closed as completed by LumberWizard** 2022-07-20 11:12 UTC
Labels: Bug in other software, 1.12
