### ISSUE TITLE
Redstone Conduit GUI shows an edit button with NOT Filter

### ISSUE THREAD

**Issue by terrapin47** [SleepyTrousers/EnderIO#4759] opened 2018-07-09 16:28 UTC
#### Issue Description:
Redstone Conduit GUI shows an edit button when slotted with a Redstone NOT Filter and an Item Conduit is in the same block.

![image](https://user-images.githubusercontent.com/13740412/42463221-7dc4a50a-8373-11e8-9ee2-e303af1fb981.png)

#### What happens:
There is an edit button present in the GUI, when clicked it closes the GUI and shifts your inventory around.

#### What you expected to happen:
There is no edit button, as there's no properties to be edited on a Redstone NOT Filter.

#### Steps to reproduce:

1. Place an Item Conduit
2. Place a Redstone Conduit
3. Insert a Redstone NOT Filter into the Redstone Conduit
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:  1.12.2-5.0.29
- EnderCore: 1.12.2-0.5.35
- Minecraft: 1.12.2

**Comment by Terrapin47** [comment] 2018-07-09 18:32
( also seems to happen with several/all the redstone filters )

**Comment by HenryLoenwind** [comment] 2018-07-31 10:29
@EpicSquid fixed?

**Comment by EpicSquid** [comment] 2018-08-15 00:36
Should be fixed now. Do let me know if it still isn't. I cannot reproduce this any more.

**Comment by Terrapin47** [comment] 2018-08-15 23:45
![image](https://user-images.githubusercontent.com/13740412/44179135-5f230e80-a0c3-11e8-9735-b9cc2a36db67.png)
Still getting this on 5.0.31 with no other mods ( besides JEI ) installed

**Comment by Gimpler** [comment] 2018-10-24 20:17
Still happening on 5.0.36

**Comment by tyler489** [comment] 2019-07-11 18:33
Confirmed Fix in .45

**Closed by tyler489** 2019-07-11 18:33 UTC
Labels: 1.12, bug

**Comment by SenojLuap** [comment] 2020-03-10 02:11
I'm still seeing this issue in 5.0.46

**Comment by MatthiasMann** [comment] 2020-03-10 07:11
@SenojLuap current EnderIO version is 5.1.55
