### ISSUE TITLE
EnderIO Crashes Game After Editing Thaumcraft Configs

### ISSUE THREAD

**Issue by princessbinas** [SleepyTrousers/EnderIO#4746] opened 2018-07-04 20:54 UTC
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unreleased version of Ender IO (e.g. for 1.8.9), please don't open an issue for features that have not been announced as "finished" or "working".

According to F9Alejandro in an issue I opened up for Thaumcraft, EnderIO is causing the crashes I was experiencing. The reason why is highly confusing. The Dark Magic Tech modpack author iamtpage already knows about this issue as I reported it to him via discord as it was happening. All I can do right now, to prevent it is to not make any changes in the Thaumcraft Config section.

The original issue post:

https://github.com/Azanor/thaumcraft-beta/issues/1070

#### What happens:

Upon editing any configs under Thaumcraft (especially minor ones such as "Show Tags"), the game will crash upon the next time you load minecraft, giving these crash reports:

https://github.com/Azanor/thaumcraft-beta/files/2143469/crash-2018-06-27_14.26.25-client.txt
https://github.com/Azanor/thaumcraft-beta/files/2143470/crash-2018-06-26_17.06.58-client.txt
https://github.com/Azanor/thaumcraft-beta/files/2143471/crash-2018-06-26_17.03.04-client.txt
https://github.com/Azanor/thaumcraft-beta/files/2143472/crash-2018-06-26_17.00.00-client.txt
https://github.com/Azanor/thaumcraft-beta/files/2143473/crash-2018-06-26_16.55.55-client.txt
https://github.com/Azanor/thaumcraft-beta/files/2143474/crash-2018-06-27_20.49.14-client.txt

#### What you expected to happen:

The game to load up normally without any issues.

#### Steps to reproduce:

1. Download and play the Dark Magic Tech modpack version 1.1.0.
2. Modify the Thaumcraft Configs such as turning "Show Tags" to true (this makes it so that holding shift is not needed to see the essentias in an item or block)
3. Save and quit the game
4. Reload the game and crash before reaching the main menu
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.0.26
- EnderCore: 1.12.2-0.5.31
- Minecraft: 1.12.2
- Forge: 14.23.4.2705

#### Your most recent log file where the issue was present: 

https://github.com/Azanor/thaumcraft-beta/files/2143474/crash-2018-06-27_20.49.14-client.txt

**Comment by bunnyman14** [comment] 2018-07-04 23:09
@Henry if this is a duplicate issue, mind showing us the one this is the duplicate of?

**Comment by princessbinas** [comment] 2018-07-05 00:29
I would like to know that too. Someone else examining the crashrepots spotted your code acting up.

**Comment by tterrag1098** [comment] 2018-07-05 01:57
https://github.com/SleepyTrousers/EnderIO/issues/4691

**Comment by princessbinas** [comment] 2018-07-05 20:10
I made an edit. Apparently I gave the wrong Dark Magic Tech modpack version as when I update versions, I try to keep the mods I use by downloading the modpack twice for the mods that need updating and such. I remember there being one or two updates before version 1.0.1.3.

**Closed** 2018-07-31 10:26 UTC
Labels: 1.12, Bug in other software, Duplicate
