### ISSUE TITLE
[EnderIO-1.9.4-3.0.0.32] Cross mod conflict with powders preventing smelting

### ISSUE THREAD

**Issue by Kazzamkablam** [SleepyTrousers/EnderIO#3336] opened 2016-05-29 07:11 UTC
#### Issue Description:
iron powder can't be smelted to iron ingots (worked before update)

Update: Seems to happen to any ender io made dusts

#### What happens:
JEI won't detect any way to turn iron powder to iron ingots

#### What you expected to happen:
iron powder->iron ingots

#### Steps to reproduce:

try put powder to any smelter.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.9.4-3.0.0.32
- EnderCore:  EnderCore-1.9.4-0.4.0.21-alpha.jar
- Minecraft: 1.9.4
- Forge: 1922

#### Your most recent log file where the issue was present: 

-

**Comment by CrazyPants** [comment] 2016-05-29 08:32
I cannot reproduce this. Could try deleting all the recipe XML files in config\enderio then restarting 
The key file is recipe_materials_core.xml, but you can safely delete everything in the folder unless you have modified the configs

**Comment by Kazzamkablam** [comment] 2016-05-29 08:37
already tried wiping config, it didn't fix it.

**Comment by b0bst3r** [comment] 2016-05-29 11:39
Just to clarify this Metals like Nickel, Platinum, Lead and Silver which are in my case and same as OP added by base metals are processed fine in sag mill (which produces base metal powders) and those are furnaced fine in the alloy smelter.

It is vanilla ores which are processed into Ender IOs own powder (gold, iron, copper) which cannot be smelted in the alloy smelter.

They do not smelt from powder to ingots in a vanilla furnace nor does the EIO powders have a recipe in JEI to allow them to be furnaced into ingots.  The only use I see for the dusts is to mix into other ingots (gold & silver into electrum powder for instance).

Seems the powder to ingot is missing for EIOs own powders.

**Comment by CrazyPants** [comment] 2016-05-29 13:04
I think I have found the issue. The recipe was changed on our side so that the output was ingotGold (ore dict) instead of minecraft:ingot_gold
This should work, and it does by itself, but it seems another mod must be messing with the ore dict. defition of 'ingotGold' so our recipe no longer has a valid output.
This should be fixed in which ever mod is breaking it but I have changed our recipes back to the vanilla items anyway. This change will be in the next build.

**Comment by HenryLoenwind** [comment] 2016-05-29 14:05
btw, we'd really like to know what that "other mod" is, but without a log posted, we have to chance to find out...

**Comment by b0bst3r** [comment] 2016-05-29 14:35
Base Metals - http://minecraft.curseforge.com/projects/base-metals

**Comment by HenryLoenwind** [comment] 2016-05-29 16:01
completely unrelated problem. fixed in latest build

**Closed by HenryLoenwind** 2016-05-29 16:01 UTC
Labels: bug, Bug in other software, Code Complete

**Comment by b0bst3r** [comment] 2016-05-29 16:03
So after all that it wasn't base metals, it was an error in the recipe building with Ender Nuggets which meant other stuff didn't get done.  Forge log would have shown that to the mod devs (which it did eventually).  Now Iron and gold powder are processed correctly but copper will not until Henry finishes the way it's being processed.
