### ISSUE TITLE
Suggestion / Feature implementation

### ISSUE THREAD

**Issue by dragonpc75** [SleepyTrousers/EnderIO#3312] opened 2016-05-20 21:59 UTC
Suggestion, 
EnderIO AE2 Implementation is incomplete and was really hoping to use it for some complex nextworks, but until it can connect directly to P2P tunnels it makes my design plans un-useable. is there an ETA on when this feature will be finished?

Feature Implementation:
In the event you wouldn't want to make the above doable i was also thinking a multipart block like the already existing P2P tunnels could be made for the use of Ender IO cabling. but this idea may be more work than just implementing it into the cable itself, but it would also allow you to make the Costs for making this block more expensive to compensate, like adding a P2P tunnel in the recipe like so.
P2P tunnel = P
Ender IO Data Cable (8channel)= D
Conduit Binding = B
BDB
DPD
BDB
EnderIO P2P Tunnels that attatch to EnderIO Dense Cables.

Thank you for all your Hard work and your making of this perfectly outstanding Mod.
DragonPC

**Comment by MatthiasMann** [comment] 2016-05-20 22:01
unclear or duplicate of #3008

**Closed by MatthiasMann** 2016-05-20 22:01 UTC
Labels: Duplicate
