### ISSUE TITLE
Nutrient Distillation Issue

### ISSUE THREAD

**Issue by IBeCrayZ** [SleepyTrousers/EnderIO#3566] opened 2016-07-31 01:28 UTC
Ok so I'm on the newest version of both Ender IO and Ender Core, and I figured this would be a good place to post this because I really can't figure this one out. I can't seem to place nutrient distillation into fluid tanks, inventory panels or killer joe via bucket. I'm sure it used to do this, am I not aware of a change? Im on the latest forge version, maybe that would help? 

Ok so with some further testing, I can use the Vat to transfer it to fluid tanks, however, I can't then take out the liquid with a bucket. I can do this with other liquids, such as water and lava. I'm so confused.

**Comment by HenryLoenwind** [comment] 2016-07-31 01:41
I'm guessing that you are using 1.94. or 1.10.2 and the Forge Bucket. The Forge Bucket is not registering itself as a bucket, so there's no way to convert a vanilla bucket into it by filling it. The water and lava registrations ere hardcoded in Forge's Bucket Registry and always work.

**Comment by IBeCrayZ** [comment] 2016-07-31 01:55
How are you supposed to disable the forge bucket? I've disabled the model in the forge.cfg, which for some reason, was forcing true even when disabling it in game, then restarting. I've done that but it still won't let me.

**Comment by IBeCrayZ** [comment] 2016-07-31 02:26
Ok, so after reinstalling minecraft, and using only Ender core and Ender IO at the latest Versions on 1.10.2 with the latest Forge, the issue still persists. (I've tested with other forge versions it still happens) I can place copper buckets from simple ores, and ender utilities buckets into the fluid tank, but not default mc empty buckets or any other EnderIO bucket that contains things other than water and lava.

**Comment by IBeCrayZ** [comment] 2016-07-31 03:01
Ok found the issue. I'm like 99% sure now it's because Ender Core was recently updated and added " "support for item stacks with fluid capabilities" in it's newest version. The version before that works perfectly. I'll go open an issue there, unless someone knows this is definitely not the issue.

**Comment by HenryLoenwind** [comment] 2016-07-31 03:30
Ok, I'd say that's caused by that EnderCore change, too.

**Comment by CrazyPants** [comment] 2016-07-31 09:30
This is fixed in ender core build 44

**Comment by RainbowGravity** [comment] 2016-07-31 23:04
Also have this issue, which thread should be focused?

**Comment by HenryLoenwind** [comment] 2016-08-15 23:52
Closing as this should be fixed with newer versions. Make a new ticket if something like this happens again.

**Closed by HenryLoenwind** 2016-08-15 23:52 UTC
Labels: 1.10, bug, Code Complete
