### ISSUE TITLE
Crash without Baubles installed (+ Extra Utilities & Fastcraft)

### ISSUE THREAD

**Issue by Cherry** [SleepyTrousers/EnderIO#2203] opened 2015-04-01 17:17 UTC
### No issues: 
EnderIO WITH Baubles and no Extra Utilities.
EnderIO WITHOUT Baubles and no Extra Utilities.
EnderIO WITH Baubles and Extra Utilities.
Extra Utilities WITH Baubles installed.
Extra Utilities WITHOUT Baubles installed.
All of the above both WITH and WITHOUT FastCraft.

### Crashes:
EnderIO, no Baubles, Extra Utilities and FastCraft. [Crash report](https://pastee.org/5xd44).

#### Versions utilised:
Baubles: 1.0.1.10
EnderIO: Build 365
Extra Utilities 1.2.2
Fastcraft: 1.21

---
x-posting this to the FastCraft thread as I believe the issue may reside there, but creating an issue here for reference also. Happy to provide further information if necessary.

**Comment by tterrag1098** [comment] 2015-04-01 17:22
So it only ever happens with Fastcraft installed? The stacktrace does not mention EnderIO or ExU or Baubles, so I don't see how it could be caused by them.

**Comment by Cherry** [comment] 2015-04-01 17:26
As far as I have been able to reproduce so far, yes. Here's [another crash report](https://pastee.org/5zp8w) from earlier testing with a few more mods installed that does mention ExU, as well as the baubles API (which I don't believe ExU implements).

**Comment by tterrag1098** [comment] 2015-04-01 17:28
I believe the crash in your original report is caused by Fastcraft shipping files it shouldn't be. This other report is more interesting.

**Comment by tterrag1098** [comment] 2015-04-01 17:29
Further still, EnderIO does not ship the Baubles API, so I fail to see how this could be our fault.

**Comment by Cherry** [comment] 2015-04-01 17:35
The crash doesn't appear to be happening with EnderIO build 363, which is why I created the issue here. I've x-posted to http://forum.industrial-craft.net/index.php?page=Thread&postID=183576#post183576 either way, just wanted to make you aware.

Build 364 (with ExU, no baubles, and Fastcraft) caused an instant crash in IConduitBundle (due to no Mekanism?): https://pastee.org/cxrj9
Build 363 loaded without issue (with ExU, no baubles, and Fastcraft)

**Comment by Cracks777** [comment] 2015-04-01 17:36
i dont use fastcraft and i still get this crash. extrautilites wont load without baubles installed

**Comment by sfPlayer1** [comment] 2015-04-01 22:49
I'm fairly convinced this isn't related to FastCraft, which btw. doesn't ship anything outside the fastcraft package.

The error means that something caused the system class loader to load the com/google/common/collect/HashMultimap class, which shouldn't ever happen. Most likely someone is messing with class loader contexts or accesses the system class loader directly.

**Comment by tterrag1098** [comment] 2015-04-02 20:52
@sfPlayer1 I can assure you we do none of that. This really can't be EnderIO's problem as we don't even ship baubles API, closing.

**Closed by tterrag1098** 2015-04-02 20:52 UTC

**Comment by Cherry** [comment] 2015-04-02 20:56
Any idea as to why the issue doesn't happen in build 363 then? https://github.com/SleepyTrousers/EnderIO/issues/2203#issuecomment-88568264

I'm happy to investigate other causes, but as switching out EnderIO versions appears to resolve it, and [another user also reported a similar issue above](https://github.com/SleepyTrousers/EnderIO/issues/2203#issuecomment-88568422), I'm inclined to believe there's definitely an issue here somewhere, be it an edge-case possibly.

**Comment by Cracks777** [comment] 2015-04-02 21:10
yes, ender io is calling for baubles to load, if not installed then it forces a crash, end of story, so of the code ender io used to add more baubles support is the cause, it didn't do it before you added that code so whats that tell us...

**Comment by blazedd** [comment] 2015-04-02 22:09
I too, can confirm that an older build of EnderIO works. Clearly this issue is caused by the current build.

**Comment by Cracks777** [comment] 2015-04-02 22:12
from the way it seems ender io is trying to import baubles api and if its not found it crashes.

**Comment by KlutzLament** [comment] 2015-04-02 23:29
I believe the problem is with Extra Utilities. I remember reading that there was an issue with it crashing if baubles wasn't installed. That also seems to be one of the few combinations you haven't tried, namely No EnderIO, No Baubles, with Extra Utilities.

**Comment by Cherry** [comment] 2015-04-02 23:35
Extra Utilities WITH Baubles installed.
Extra Utilities WITHOUT Baubles installed.

^ both work without fine without EnderIO, as in the original post, even with the new ExU 1.2.3 released today.

EnderIO is the key variable here. Removing it (or reverting to build 363 or lower) resolves the issue.

**Comment by tterrag1098** [comment] 2015-04-02 23:36
EnderIO works by itself, but not once you install ExU, and the stack trace starts in ExU code. How does this point to us again?

**Comment by Cherry** [comment] 2015-04-02 23:40
ExU also works by itself, and the two have worked fine together until build 365 of EnderIO.

Granted, the stack trace does start in ExU code, but the crash goes away when I use build 363 of EnderIO.

**Comment by Cherry** [comment] 2015-04-03 00:04
Build 365 seems to add "more baubles support" as per https://github.com/SleepyTrousers/EnderIO/commit/e8feb577b706000e38e0c22758bdb0336513346e so I don't feel that it's a huge jump to consider this may be affecting this issue.

My test environment generally doesn't contain Mekanism, so I haven't tested build 364 up to this point, but I have just done so, and build 364 also loads without any issue, using the same set of tests as originally dictated.

Build 365 is the only build that this issue occurs with.

**Comment by Cherry** [comment] 2015-04-03 01:01
I just compiled the latest source in Git, reverting solely commit https://github.com/SleepyTrousers/EnderIO/commit/e8feb577b706000e38e0c22758bdb0336513346e and this issue no longer occurs.

I hate to submit a pull request that removes features, but it completely resolves this issue.

**Comment by tterrag1098** [comment] 2015-04-03 02:13
Our code is fine, I'm not removing a feature because it somehow causes another mod to crash.

**Comment by sfPlayer1** [comment] 2015-04-03 02:15
While said commit seems to trigger the problem, it by no means verifies it being the cause. It's probably just affecting the load order or something similar.

Maybe extract all your mods and then search (grep) for getSystemClassLoader or HashMultimap.

Running java with -verbose:class may be suitable to log the loading of HashMultimap.

**Comment by blazedd** [comment] 2015-04-03 02:19
@tterrag1098 Wow, that's a pretty messed up mentality to take on an issue, especially in a mod compatibility issue with dozens of modpacks that use your modpack. You've done nothing but try to brush us off while we are only trying to provide you with tests that show the issue with the most recent build.

**Comment by Cracks777** [comment] 2015-04-03 02:33
Our code is fine my ass, this has got to be one of the worst mod authors there is, he blames everything but whats the problem, his code, removing the code fixes the issues, its not just one mod that its having problems with, this is what you get when someone else takes over someones mod, if crazypants were here im sure the issue would be fixed. and i agree 100% with @blazedd you keep brushing us off, closing things, and not providing any real support.

**Comment by tterrag1098** [comment] 2015-04-03 03:42
Brushing you off would be ceasing to respond to an issue which I've already determined is not my fault. EnderIO does *not* ship any Baubles classes, yet ExU crashes with a NoClassDefFoundError? That doesn't make sense.

**Comment by tterrag1098** [comment] 2015-04-03 03:43
If you point to me the part of our code that could possibly be causing this issue I will fix it, but until then I can see no such code.

**Comment by tterrag1098** [comment] 2015-04-03 04:10
Here, try this build, I've read through *all* baubles related code and cleaned up anything I thought suspicious. I severely doubt it will affect anything but it's worth a shot. http://ci.tterrag.com/job/EnderIO/368/

**Comment by Cherry** [comment] 2015-04-03 04:23
No need to bash anyone guys, we can all be amicable here :)

I very much appreciate the cleanup @tterrag1098, though as you expected, it hasn't changed anything. I've opened an ExU issue regarding this bug also, https://github.com/rwtema/extrautilities/issues/554 so I guess we'll see if @rwtema has any insight.

**Comment by MatthiasMann** [comment] 2015-04-03 06:15
As far as I can tell from the code - EIO only interacts with Baubles if FML tells us that baubles is installed. And I run EIO in my test world without Baubles without issues.
