### ISSUE TITLE
Constant Replacement of Conduits

### ISSUE THREAD

**Issue by DizzyDJW** [SleepyTrousers/EnderIO#5255] opened 2019-09-24 19:12 UTC
#### Issue Description:

I have the latest version of EnderIO and for some reason every now and again every single conduit stops functioning and the only way to fix this is by replacing each one individually.

#### What happens:

Every now and again every single conduit stops functioning and the only way to fix this is by replacing each one individually. I've checked to see if it is "server" lag (I'm on SP but I use COFH to check fps) and there is no issue there. Reloading the world changes nothing.

#### What you expected to happen:

The conduits to continue functioning normally.

#### Steps to reproduce:

1. Set up a large system of item conduits and fluid conduits constantly moving items and fluids.
2. Let run for long periods of time.
3. Check???
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.1.51
- EnderCore: 0.5.69
- Minecraft: 1.12.2
- Forge: 14.23.5.2846
- SpongeForge?: NO
- Optifine?: NO
- Single Player and/or Server?: Single Player

#### Your most recent log file where the issue was present: 
NO CRASH = NO LOG
[pastebin/gist/etc link here]

**Comment by weightmaker** [comment] 2019-10-20 10:28
this has always been an issue and will almost 100% only happen on chunk boundries. I have noticed it happens more often when the area is chunkloaded (especially with FTBUtils chunkloading).
pro tip: avoid to "Set up a large system of item conduits and fluid conduits constantly moving items and fluids.". make smaller individual setups and use ender chests or similar to move longer distances.

if not then try to avoid using connection in the outer most column in each chunk and you should be good

**Comment by tyler489** [comment] 2019-10-21 13:29
Weight is correct as this is commonly caused by bad chunkloading

**Closed** 2020-06-05 15:22 UTC
Labels: 1.12
