### ISSUE TITLE
Conduit/Facade visual problems with  EnderIO-1.7.10-2.3.0.415_beta

### ISSUE THREAD

**Issue by Mezzolan** [SleepyTrousers/EnderIO#2862] opened 2015-09-29 03:03 UTC
FTB Infinity just updated to  EnderIO-1.7.10-2.3.0.415_beta.jar  and I now am having issues with conduits and facades rendering properly. Conduits on their own will disappear from time to time depending on the angle of view and facades are almost completely broken - switching to and from a Yeta Wrench will usually cause them to be stuck transparent but not necessarily rendering the conduits inside. Moving from the area and returning or cycling through items repeatedly can sometimes fix the facades being stuck transparent:

![image](https://cloud.githubusercontent.com/assets/285093/10154283/fa835d34-662a-11e5-8d22-a9fdfa69de32.png) *See conduits inside facades from this angle...*

![image](https://cloud.githubusercontent.com/assets/285093/10154288/1359cfdc-662b-11e5-9b59-c331fb1bb0e2.png) *...but, turn a bit and this happens.*

![image](https://cloud.githubusercontent.com/assets/285093/10154304/29baebf8-662b-11e5-90b7-6c654f09ee03.png) *Cycling off of the Yeta Wrench in my hotbar and now it looks like this... those dark holes are actually facades over conduits like in the above images.*

Additionally, there are some anomalies with the arrows on item conduits and the like depending on the angle of viewing and whether I have the wrench out:

![image](https://cloud.githubusercontent.com/assets/285093/10154385/40aed2f6-662c-11e5-8293-d946b6393990.png) *Wrench in hand...*

![image](https://cloud.githubusercontent.com/assets/285093/10154420/a08dec70-662c-11e5-8a0b-154673022666.png) *...no wrench in hand*

FTB Infinity **does** include Fastcraft but I have the exact same issue with it active or removed from the active mods.

*(PS: The new textures look great, just can't wait for issues like this to be worked out, great job guys!)*

**Comment by cloakable** [comment] 2015-09-29 07:05
I am seeing the same problem in my modpack, no Fastcraft.

**Comment by HenryLoenwind** [comment] 2015-09-29 08:09
dupe #2812

(but thx for the screenshots, they look helpful)

**Comment by Mezzolan** [comment] 2015-09-30 01:14
No problem, hope it helps. If any more information might help feel free to ask.

**Comment by SolManX** [comment] 2015-10-12 17:32
A couple of people - including me - playing an ftb pack (infitech) are experiencing this problem. I'm on SSP but also reported on SMP.
EnderCore -> 0.1.0.24
EnderIO -> 2.3.0.415

**Comment by tterrag1098** [comment] 2015-10-12 17:48
I still cannot reproduce this myself. Any concrete reproduction method would be very nice.

**Comment by DeathOfTime** [comment] 2015-10-21 11:41
I am playing on the Infinity modpack v 1.11.2 using EnderIO-1.7.10-2.3.0.415_beta.jar. I found a thread referencing a similar bug on FTB's forums. It stated to come here with any reports. Also in it it was stated that the issue seemed to be with chunk borders. The conduits on the other side of chunk borders disappear and reappear at random. I was able to capture a image of the conduit while it was invisible. Should be noted I am playing MP. The server is on the same PC as the client.

![2015-10-21_06 20 08](https://cloud.githubusercontent.com/assets/15230368/10635453/7d85f95e-77be-11e5-9ebe-d84dd953c3d2.png)

**Comment by wlhlm** [comment] 2015-10-21 12:25
@DeathOfTime could it be a problem with Fastcraft?

**Comment by tterrag1098** [comment] 2015-10-21 20:08
@DeathOfTime Chunks are the boundaries of the render update, so it makes sense it would happen along chunk lines. My guess is some other mods are screwing with the render pass variable in a way I'm not expecting. I just need to know which one(s).

**Comment by mindforger** [comment] 2015-10-22 07:28
it must be more than one mod, i noticed this behaviour almost every time near a smeltery, near mariculture objects and sometimes near immersive engineering machinery

**Comment by wlhlm** [comment] 2015-10-22 08:12
> this makes me notice, i ALWAYS had iron chests around!

Sounds interesting! I noticed the bug in a similar environment near my Ender-quarry setup with EIO + JABBA + Iron Chests. I'll see if I can reproduce.

**Comment by mindforger** [comment] 2015-10-22 08:15
JABBA Barrels also did start suffering from Z-Fighting at some point when i had iron chests around or a smeltery

**Comment by DeathOfTime** [comment] 2015-10-22 08:27
>this makes me notice, i ALWAYS had iron chests around!
I never have iron chests around. Though I do use jabba barrels and thermal expansion stronboxs all over the place.

Tried using a mod set of just nei, enderio, their core mods, Fastcraft, and Fast Leaf Decay. None of those in combo seemed to do it. Tried putting lava nearby, in case that might be related. Still nothing. I can't really think of what mod, or mod combo might be doing this.

Tried completely disabling fastcraft in Infinity. Wasn't actually able to check the conduits though. My FPS the entire time never got above 5. Found it impossible to do anything in that modpack.

**Comment by wlhlm** [comment] 2015-10-22 09:35
OK, I was able to reproduce _a_ conduit rendering issue with a reduced list of mods. __But__ this seems to be different to what @DeathOfTime reported as it happens across multiple chunks and not just parts of the conduit.

My problem is clearly related to __Optifine__, so not a lot that can be done about it, unfortunately. This happens with just:

- Minecraft 1.7.10
- Forge 10.13.4.1448
- EnderCore 0.1.0.26_beta
- EnderIO 2.3.0.417_beta
- _OptiFine 1.7.10 HD U C1_

&nbsp;
- Optifine setting: Main Menu → Options → Video Settings... → Chunk Loading: Multi-Core

__How it looks:__
![2015-10-22_11 01 20](https://cloud.githubusercontent.com/assets/1928113/10661400/123ec16c-78ae-11e5-80c7-e0977ca18c34.png)

![2015-10-22_11 01 31](https://cloud.githubusercontent.com/assets/1928113/10661394/0537ac5e-78ae-11e5-8b1b-38b7c1726e12.png)
(it can usually be fixed by scrolling your hotbar)

__How to fix it:__

- Setting Chunk Loading to "Default"
 - (BTW, this is a good option to set for everyone using FTB Infinity with Optifine, as the upcoming version 1.12.1 includes [Chisel](https://github.com/Chisel-Team/Chisel) which has heavy rendering issues in combination with the Multi-Core Chunk Loading option)
- Uninstalling Optifine

- - - 

@mindforger Do you happen to have Optifine installed? It's usually the cause of heavy z-fighting and can be fixed by setting Performance... → Fast Render to OFF.

**Comment by mindforger** [comment] 2015-10-22 09:41
nope, only (coremod) that is in, is fastcraft, i may remove this for a bit and see whyt my conduits are saying :)
the issues happen only after a bit of time when something is messing with the rendering but i did never investigate this

**Comment by tterrag1098** [comment] 2015-10-22 14:04
@wlhlm Optifine was never a question, it is not supported and I have no doubt that threaded chunk rendering would break conduits.

@mindforger sounds like Tcon and IronChests might be good contenders to start with?

**Comment by SolManX** [comment] 2015-10-22 14:31
@tterrag1098 

Not sure if this is a helpful comment or not, but the pack I'm playing on doesn't have TCon, but does have IronChests.

**Comment by blarghhh** [comment] 2015-10-25 03:58
using the latest version EnderIO-1.7.10-2.3.0.417_beta.jar and the item conduits are still appearing and disappearing across chunk boundaries. i am using ftb infinity 1.11.2 with journeymap disabled and using mapwriter 2 instead. i just place the item conduits in the world without being connected to anything and they appear and disappear cross-chunk. i have tried with fastcraft disabled and enabled but no change. no resourcepacks or texturepacks used and also no optifine.

**Comment by HenryLoenwind** [comment] 2015-10-29 17:55
I'm closing this one because it's a dupe of #2812. See there.

**Closed by HenryLoenwind** 2015-10-29 17:55 UTC
Labels: Duplicate
