### ISSUE TITLE
EnderIO forces game to crash when extra utils. is installed

### ISSUE THREAD

**Issue by Ianaver** [SleepyTrousers/EnderIO#2215] opened 2015-04-03 05:11 UTC
crash:http://pastebin.com/qk4fHxe4

**Comment by SkySom** [comment] 2015-04-03 05:14
Pretty sure this is a dupe of #2203

**Comment by tterrag1098** [comment] 2015-04-03 05:24
Yes

**Closed by tterrag1098** 2015-04-03 05:24 UTC

**Comment by Ianaver** [comment] 2015-04-03 13:51
k
