### ISSUE TITLE
WAILA crash with painted facade

### ISSUE THREAD

**Issue by Watchful1** [SleepyTrousers/EnderIO#3307] opened 2016-05-18 03:56 UTC
#### Issue Description:
Game crashes when the player looks at a reinforced obsidian facade, either by itself placed in the world or placed on a conduit.

#### Steps to reproduce:

1. Paint facade with reinforced obsidian
2. Place on ground
3. Crash

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 2.3.0.424
- EnderCore: 0.2.0.32
- Minecraft: 1.7.10
- Forge:10.13.4.1614

#### Your most recent log file where the issue was present: 

http://pastebin.com/r9uqhfxd

**Comment by AnrDaemon** [comment] 2016-05-18 05:09
JFYI: EIO last beta 425 on curseforge.

**Comment by MatthiasMann** [comment] 2016-05-18 05:47
Duplicate of #3290

**Closed by MatthiasMann** 2016-05-18 05:47 UTC
Labels: Duplicate
