### ISSUE TITLE
Travel Anchor suggestion

### ISSUE THREAD

**Issue by psychicash** [SleepyTrousers/EnderIO#2718] opened 2015-08-16 09:00 UTC
Not sure this is the right place but...

I know that many of my friends as well as myself love the travel anchor.  However it can get downright cluttered trying to find the right angle to aim at the right one.  This is really because we tend to, probably over use them.  We wanted to make the suggestion that perhaps channels or color coding could be added so only those with a matching color/frequency would show up when you look around.  So if the one you're on is say red, then only other red ones would show.  If you wanted to get fancy you could even have color or frequency adjustable via redstone signal via sides or computercraft. etc.  Anyways just suggestion. Love the mod.

**Comment by tterrag1098** [comment] 2015-08-17 02:24
Duplicate of #1884

**Closed by tterrag1098** 2015-08-17 02:24 UTC
Labels: enhancement
