### ISSUE TITLE
[1.10.2] Capacitors won't allow items to attach directly

### ISSUE THREAD

**Issue by Nargath** [SleepyTrousers/EnderIO#3913] opened 2016-12-14 15:39 UTC
#### Issue Description:
Trouble adding items to the sides of capacitor banks, including over capacitors.

#### What happens:
When you right click on a side of a capacitor bank to either put an object next to (like another capacitor bank) or attacj an item to it (like a torch, or transformer from Immersive Engineering), the item doesn't attach and immediately pops back to your inventory.
It will place items in the required position if aimed at another surface, say a different block, and for other capacitors, this will form the multiblock structure. So its only when the capacitor itself is the focus block.

#### What you expected to happen:
With the capacitor as the focus block, the item will rest against the capacitor, form an appropriate multiblock, or mount like a torch does on other blocks.

#### Steps to reproduce:

1. Place capacitor in the world
2. Take another item (torch or capacitor for example)
3. With the capacitor in the crosshairs, shift right click to place.
4. Item will pop off
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.0.1.139_beta
- EnderCore: 0.4.1.61-beta
- Minecraft: 1.10.2
- Forge: 12.18.3.2185

#### Your most recent log file where the issue was present: 

https://gist.github.com/Nargath/589903674735047aadd2870c55d787c8

**Comment by bookerthegeek** [comment] 2016-12-14 22:23
Did you try setting the side to input or output first?

**Comment by VT-14** [comment] 2016-12-14 22:24
Sounds like an issue I had with the DW20 pack not too long ago.  Comments on YouTube said it was caused by having an Iron Backpack on your back.

Issue extends to all inventories if I recall correctly.  It should also be fixed in either the next or current Iron Backpacks update.

**Comment by Nargath** [comment] 2016-12-14 22:27
Bookerthegeek, surely input/output shouldn't impact torches being mounted though?

VT-14, I do have Iron Backpacks in the pack, and I believe my character has one equipped. I'll test that and report back when I'm in front of my PC

**Comment by Nargath** [comment] 2016-12-14 22:29
It is a bug within Iron Backpacks, as listed here:
https://github.com/gr8pefish/IronBackpacks/issues/121

**Closed** 2016-12-14 22:31 UTC

**Comment by gr8pefish** [comment] 2016-12-15 00:05
Fixed in the latest version of Iron Backpacks!
