### ISSUE TITLE
Crash, NoClassDefFoundError: crazypants/enderio/base/machine/base/te/AbstractMachineEntity

### ISSUE THREAD

**Issue by aaronhowser1** [SleepyTrousers/EnderIO#5455] opened 2020-10-12 12:14 UTC
#### Issue Description:

I updated EnderIO and Endergy from version 5.2.59 to 5.2.61, and now it crashes on startup.

[Crash Report](https://pastebin.com/TjKFprbB)
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.12.2-5.2.61, EnderIO-endergy-1.12.2-5.2.61
- EnderCore: EnderCore-1.12.2-0.5.76
- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- SpongeForge? no
- Optifine? no
- Single Player and/or Server? SP

#### Your most recent log file where the issue was present: 

[latest.log](https://pastebin.com/PX1u8P6g), [debug.log](https://github.com/SleepyTrousers/EnderIO/files/5365042/debug.log)

**Comment by hypherionmc** [comment] 2020-10-12 12:23
Duplicate of #5443 

Please try the suggestion in the referenced issue and if it does not solve your problem, please open a new issue

**Closed by hypherionmc** 2020-10-12 12:23 UTC

**Comment by aaronhowser1** [comment] 2020-10-12 12:26
What suggestion? That issue just says that it's TickCentral at fault. Do I just have to wait for TerminatorNL/TickCentral/issues/12 to be fixed, and TC to update?

**Comment by hypherionmc** [comment] 2020-10-12 12:27
Most probably yes. Try running your game without tickcentral and see if it resolves the problem

**Comment by aaronhowser1** [comment] 2020-10-12 12:34
That worked, thanks
