### ISSUE TITLE
[1.10.2]Item conduits randomly turning off

### ISSUE THREAD

**Issue by Gebcrafter** [SleepyTrousers/EnderIO#3873] opened 2016-12-03 04:06 UTC
#### Issue Description:
Item conduits randomly stop extracting after working fine for hours.

#### What happens:
Item conduits, after working fine for hours, stop extracting. I then have to break them, place them again, and set them to always on.

#### What you expected to happen:
Item conduits to stay on, hence the extraction setting 'always on'

#### Steps to reproduce:

1. Place an item conduit
2. Set it to extract from an inventory with items in it, always on
3. Wait a while
4. The item conduit will have stopped extracting automatically

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.0.1.138
- EnderCore: 0.4.1.60
- Minecraft: 1.10.2
- Forge: 12.18.2.2125

#### Your most recent log file where the issue was present: 

http://pastebin.com/kUSb6krv

**Comment by HenryLoenwind** [comment] 2016-12-03 09:28
Looking at your logfile, I see 2 issues:

1. RF Tools Dimensions and the McJty compat library don't seem to match in version

2. You game is overloaded and has to skip time to keep up. Please use one of the profiling tools available to see what's lagging the game---this looks like something we get reported for months but only as the final crash when the game gets so slow it stops completely. And those crash logs don't have any data on what's slowing the game down...

**Comment by Gebcrafter** [comment] 2016-12-03 16:10
1. I may have found the error in the mod version mismatch; rftoolsdim & rftools is for version 1.11 while mcjty compat is not. I downgraded rftools & rftoolsdim to 1.10. That may have fixed that issue, but as for the other problem:
2. I am a complete newb so i dont completely understand the result of the tickprofiler. I profiled for 30 seconds in all dimensions. For the results I do understand, the TPS was 19.997, which seems to indicate why the conduits work for so long but after a while they need to skip ticks. As for the specifics, i cant make out what the results mean. I did see some things in there like the enderio farming station, the mekanism digital miner (which was off at the time), and some animals.

**Comment by Gebcrafter** [comment] 2016-12-04 21:30
Also, if Minecraft is overloaded why does everything else in my world work correctly? The only thing not running properly (or at all for that matter) are the extraction conduits.

**Comment by RealGrep** [comment] 2016-12-05 22:54
Having the same problem, although it seems to happen every time I restart the server. I then have to go break the insert side of the item conduit and place it again. My McJty mods definitely all match the Compat library and McJtyLib. I just updated them in a batch with the first release versions, nor are there messages indicating they are not in sync.

The server is not at all overloaded except one single message right after it completes the startup sequence. Perhaps that blip causes it on restart. Would be hard to catch it with Sampler since the startup sampling stops right before, and it's over before I could do anything. There are no other overloaded messages.

**Comment by Gebcrafter** [comment] 2016-12-05 23:45
I now have reached the point where my world no longer loads, with enderio 'doUpdate' scattered all over the report.

**Comment by Gebcrafter** [comment] 2016-12-06 01:00
I can confirm that that is my problem, except substitute 'on server restart' to 'world load'.

**Comment by Gebcrafter** [comment] 2016-12-08 00:07
So... nothing? Well i guess modded minecraft has to wait.

**Comment by Arcanatias** [comment] 2016-12-08 07:24
I am also having the same issue, item conduits will randomly stop extracting and basically jam up my whole system. I can break a random conduit on the line that isn't even connected to an inventory and extracting will resume.

**Comment by HenryLoenwind** [comment] 2016-12-08 09:26
I haven't been able to reproduce this so far. As this only happens in long running instances, I will need to set up a debugging version that can give me data without being restarted all the time and let that run for a couple of hours. Weekend type stuff...

**Comment by RealGrep** [comment] 2016-12-08 09:38
Alright, thanks Henry. <3

**Comment by Gebcrafter** [comment] 2016-12-08 11:49
You're awesome Henry!

**Comment by Unatan63** [comment] 2016-12-16 15:33
This is happening also to me, I'm using Direwolf20's 1.10.2 pack only one of my garden's conduits won't work at all now (as of this morning), I removed the whole line (15 conduits) and replaced, still won't empty the Farming station, only thing connected in line with them are the energy conduits, not seen this happen before in all the years been using enderio conduits

**Comment by GeneralLeeInept** [comment] 2016-12-19 12:32
Experiencing the same issue on the DW20 1.10.2 pack, version 1.1.4. 

I haven't modified the pack in any way, just downloaded/installed using the curse launcher.

As others are reporting item conduits stop extracting after working perfectly okay, and require to be broken and replaced. 

Some additional info which doesn't perfectly match other reports:
* I rarely get to play for more than an hour or two and I seem to encounter this every time I play, so I'm not sure "long running" is a criteria for this occurring.
* In one spot where I have an item conduit extracting from a farming station, when it stops extracting if I remove the conduit with a yeta wrench it completely vanishes (does not go into my inventory, does not fall to the ground anywhere nearby, might be glitching through blocks). This has reproduced 3 or 4 times.
* For the same instance I've taken to breaking/replacing a conduit one down the line and that breaks normally (I get the item conduit in my inventory) and replacing it still seems to fix the issue.
* In a different spot where I just encountered the issue, when I tried to right-click the conduit with a cobweb to see where it should route to, the cobweb placed in the world. I broke it and tried again with string and again the string placed in the world. Happened twice more with the string before I broke and replaced the conduit then it all started working again.

**Comment by HenryLoenwind** [comment] 2017-01-05 22:14
for reference: https://www.reddit.com/r/feedthebeast/comments/5m8q0y/dw20_110_having_to_breakreplace_refined_storage/

**Comment by aaronmallen** [comment] 2017-01-17 16:43
likely related to #3943 ?

**Comment by Silvrus** [comment] 2017-01-21 18:49
Can confirm, the issue is occurring when the chunk they're in is unloaded, either through traveling far enough away to unload it if no chunkloader is used, or upon server/ssp restart. Breaking and replacing a piece of conduit resets the network to work again. Occurs with both item and fluid conduits.

**Comment by demethan** [comment] 2017-02-15 02:19
We are having the same issue as explained by @Silvrus . Our server restarts ever 12h. We load the chunk with FTB Utilities. 

Pack: [ALL the mods - expert]

**Comment by DietmarKrause** [comment] 2017-02-15 06:37
i personally only see the problem when something is exported via item counduit to a chest, not in other circumstances. So: build a system with at least 2 or 3 types of conduits on oh which is item conduit and export to a chest. You will see the issue on chunc reset on the server, probably not on single player if the chuncs are loaded.

**Comment by HenryLoenwind** [comment] 2017-02-15 08:04
One word: All this "me too"-ing (not just here) isn't really helpful unless it is a "me too on the current Ender IO version". I can "me too" any fixed bug if I use an Ender IO version from before it was fixed.

There were a couple of massive changes to conduits, block ticking, chunk loading avoidance, etc. at the end of December. So unless I either experience this myself (which would be ideal because I could then simply attach a debugger and see what's happening) or get a solid report of it happening with a current version, I am going to assume it was fixed with those changes.

**Comment by finnock** [comment] 2017-02-15 10:50
I still have the same issue on Direwolf 20's 1.10 pack (Version 1.4.1).
EnderIO Version: 1.10.2-3.1.156
EnderCore Version: 1.10.2-0.4.1.64-beta

I have a somewhat long conduit line (about 20 blocks). with multiple extraction and insertion points, criss crossing with a ender io power line. The problem occurs after a few hours (sometimes even less then an hour) and is fixed by replacing an arbitrary item conduit in the line. I cant confirm that is related to chunk loading, since it happened to me while i was only a few blocks around and the complete area of the conduit line is chunkloaded as well.

Do you need any more info on this?

**Comment by aaronmallen** [comment] 2017-02-15 13:25
Several words: @HenryLoenwind can you not close and lock the bug if it's fixed... If not I'm going to assume your assumptions on whether or not the bug was fixed are irrelevant.

**Comment by HenryLoenwind** [comment] 2017-02-15 14:29
@finnock you are 13 versions behind on Ender IO but do include the important Endercore change. Still, 157, 158, 160, 162 and 164 changed things with conduits.

@aaronmallen Did you miss some words or mistyped some letters? That doesn't really make sense to me.

**Comment by finnock** [comment] 2017-02-15 14:33
@HenryLoenwind well i was on the release version (stable). i updated to **164** and could reproduce the same error. i will try to make a minimal world save on a flatworld to try and reproduce the error.

**Comment by HenryLoenwind** [comment] 2017-02-15 18:18
that would be great. The only way I could reproduce it was on a server where I didn't have low level access.

**Comment by finnock** [comment] 2017-02-15 18:45
> The only way I could reproduce it was on a server where I didn't have low level access.

Can you generally not have low level access when it is on a server? Because i think it is not reproducible on single player.

**Comment by codeurge** [comment] 2017-02-24 15:01
I've been following this issue for a bit, and am still experiencing the issue as well using the direwolf20 1.10 (1.6.1) pack. In fact, having just watched the video uploaded this morning: you can observe him having the same problem at 5:51, where his refined storage system has no empowered seeds because the empowerer hooked up with EnderIO item conduits was unloaded when he previously harvesting Ender Draconium in The End; therefore stopping the refined storage system from auto-crafting the empowered seeds.

https://youtu.be/rnJjYyPkYtE?t=5m51s

I observe the same issue on my multiplayer server, with the exception that I usually have to break a block on the item conduit, and replace it in order to get things crafting again. Or, restarting the server will usually suffice as well.

Admittedly I'm new to debugging anything Minecraft, but I'm willing to help get whatever further info I can.

**Comment by Cobra1117** [comment] 2017-02-26 16:49
More (hopefully useful) info: I was able to stop this problem by using an IC2 chunkloader to load the entire network. The Extra Utils 2 Chunk Loading Ward did NOT solve this problem for some reason.

**Comment by Ricket** [comment] 2017-02-26 17:34
Yeah, it seems chunkloading is a "solution" but not all chunkloaders are equal. I experienced this bug even when the network was loaded using FTButil chunk loading. Experienced other odd behavior too. But since switching to loading using Persistent Bits, this and the other issues have not happened.

**Closed** 2017-05-05 17:44 UTC
Labels: 1.10, Waiting For Feedback
