### ISSUE TITLE
ME Conduits Color Channels

### ISSUE THREAD

**Issue by TonRZN** [SleepyTrousers/EnderIO#2701] opened 2015-08-06 22:33 UTC
Hi,
I have a request to add colored channels to the ME Conduits and the Dense ones if at all possible. Reason I ask such a thing is because I like having my base channels separated with colors for each room, to make my ME System more organized and Ender IO conduits are so clean, compact and easy to hide with facades. Thank you
(Sorry for my bad english, I'm not american)

**Comment by MatthiasMann** [comment] 2015-08-06 22:35
duplicate of #1777

**Closed by MatthiasMann** 2015-08-06 22:35 UTC
Labels: Duplicate
