### ISSUE TITLE
Ender IO and chests

### ISSUE THREAD

**Issue by eyeballcode** [SleepyTrousers/EnderIO#2477] opened 2015-05-16 03:13 UTC
If you have an Ender IO next to a chest and you open the chest through the Ender IO, even after closing the chest remains open. Using EnderIO 1.7.10-2.2.8.381 and latest Forge.

https://www.youtube.com/watch?v=L9O3O1NooBY&feature=youtu.be

**Comment by tterrag1098** [comment] 2015-05-22 04:32
Duplicate of #15 ...

**Closed by tterrag1098** 2015-05-22 04:32 UTC
