### ISSUE TITLE
Issues with machine rendering:

### ISSUE THREAD

**Issue by calmcacil** [SleepyTrousers/EnderIO#2624] opened 2015-07-02 10:27 UTC
Forge: 10.13.4.1481
EnderCore: 0.0.1.10_alpha
EnderIO: 2.3.0.398_beta

We are experiencing issues with what looks to be the state of the machines as far as rendering the physical machine block, and the Machine UI. It didn't update at all, but after a little while it started rendering the alloy smelter as "working" and progress 12% whilst its not actually working on anything. 

Works as expected in single player, but not in server. If i were to guess it has something to do with server/client syncing, because if you reconnect with a machine working its frozen in the state it was in upon you logging in.

**Comment by MatthiasMann** [comment] 2015-07-02 10:29
machine state is only send to players which are near the machine to save network traffic

**Comment by calmcacil** [comment] 2015-07-02 10:29
I'm standing on top of the machine, it also applies to the machine GUI.

**Comment by tjsd** [comment] 2015-07-02 11:32
I can confirm this is a problem. Have the same issue.

**Comment by tterrag1098** [comment] 2015-07-04 17:30
Confirmed, but this is an EnderCore issue. Unsure of the cause.

**Comment by tterrag1098** [comment] 2015-07-10 23:53
Fixed as of EnderCore build 11

**Closed by tterrag1098** 2015-07-10 23:53 UTC
Labels: bug, EnderCore
