### ISSUE TITLE
[TESLA] Crash 1.10.2

### ISSUE THREAD

**Issue by CitiesXL2815** [SleepyTrousers/EnderIO#3751] opened 2016-10-05 07:28 UTC
#### Issue Description:

Crash with Ender IO
#### What happens:

in creative clicking the ender io button crashes the game
#### What you expected to happen:

show all the items in creative GUI
#### Steps to reproduce:

1.
2.
3.
...

---
#### Affected Versions (Do _not_ use "latest"):
- EnderIO: 3.0.1.117_beta
- EnderCore:0.4.1.56_beta
- Minecraft: 1.10.2
- Forge: 12.18.1.2095
#### Your most recent log file where the issue was present:

[https://gist.github.com/88f90624f2b65c638db4e8dbea8bc472.git]

**Comment by iamomicron** [comment] 2016-10-05 10:04
This is the same issue as here: https://github.com/Darkhax-Minecraft/Tesla/issues/41

**Comment by HenryLoenwind** [comment] 2016-10-05 10:14
Seems I'll have to add a "which mod brings along which Tesla classes" diagnostics to the crash report like I did with RF...

**Comment by darkhax** [comment] 2016-10-05 19:29
The only mod which should be adding new classes is the primary Tesla library. If other mods are bundling Tesla or modified versions of it please ask them to stop.

**Comment by HenryLoenwind** [comment] 2016-10-05 21:19
The latest build will now list the location each Tesla class has been loaded from in the crash report, just like Ender IO has been doing for RF for a while now.

However, I believe this crash is caused by a class that loads a Tesla class being loaded when Forge loads the main Mod class. At this time Tesla may not yet be in the classpath, and this failed try will even blacklist that Tesla class from being ever loaded again.

The latest Ender IO build will try very hard to avoid this.

**Comment by iamomicron** [comment] 2016-10-05 21:53
The crash related to this post and the ones found at https://github.com/Darkhax-Minecraft/Tesla/issues/41 and from https://github.com/mezz/JustEnoughItems/issues/500 are now solved.

The forge log attached below is using the latest EnderIO (3.0.1.120) to help discover the root issue
https://dl.dropboxusercontent.com/u/76791645/fml-client-latest-eIO.log

**Comment by CitiesXL2815** [comment] 2016-10-05 22:15
Henry do you want me to close this now, it didn't crash?

**Comment by HenryLoenwind** [comment] 2016-10-05 22:38
Thanks for that great log, @iamomicron. Found 2 other (minor) issues with it.

**Comment by HenryLoenwind** [comment] 2016-10-05 22:39
@CitiesXL2815 We could close this, but I expect to get a couple of dupe reports for the next week. So I'll leave this open for a bit so I can find it more easily.

**Comment by CitiesXL2815** [comment] 2016-10-05 22:44
ok

**Closed** 2016-11-16 19:09 UTC
Labels: 1.10, bug, Code Complete
