### ISSUE TITLE
Dark boots energy dumping

### ISSUE THREAD

**Issue by Exy-mat** [SleepyTrousers/EnderIO#2266] opened 2015-04-09 15:49 UTC
I've observed something annoying with Dark boots upgraded with Empowered (with any level).
When using wings from extrautilities (and probably with all others stuff that can allow flying), sneaking to go down is dumping energy from the boots. 
Also, fall back on the ground is weird: wings negate fall damage, but it still use in priority boots power
That means I always reload my boot every time I want to fly, and travelling from place to place.

**Comment by eduardog3000** [comment] 2015-04-09 16:10
This is a duplicate of #2193.

**Comment by tterrag1098** [comment] 2015-04-09 16:35
Yes but this issue is actually testable, unlike the other. Tracking under this issue.

**Closed** 2016-05-28 09:54 UTC
Labels: bug, Code Complete
