### ISSUE TITLE
Any reference of Travel Staff Blacklisting causes dedicated server crash: java.lang.NoClassDefFoundError: net/minecraft/client/entity/EntityClientPlayerMP

### ISSUE THREAD

**Issue by ReikaKalseki** [SleepyTrousers/EnderIO#3298] opened 2016-05-11 02:23 UTC
This includes both calling the dedicated IMC (http://pastebin.com/s3nZ5Dy4) and reflectively injecting the entries directly.

At a glance, it looks like `onInput(EntityClientPlayerMP)` in `TravelController` does not have an @SideOnly, and this triggers the crash.

**Comment by MatthiasMann** [comment] 2016-05-11 05:36
Why did you not specify any version information and an incomplete log? The "new issue" template is there for a reason.

**Comment by ReikaKalseki** [comment] 2016-05-11 06:41
This is with the version uploaded yesterday (1.7.10). The rest of the log is loading info I doubt you will find helpful.

**Comment by SteelShot** [comment] 2016-05-11 11:43
I'm getting the exact same Error:

EnderIO:EnderIO-1.7.10-2.3.0.425_beta.jar
EnderCore-1.7.10-0.2.0.34_beta.jar
Forge: 1.7.10 - 10.13.4.1614

**Comment by notchriss** [comment] 2016-05-11 17:01
Same problem here http://pastebin.com/yRrYA8xW

**Comment by SteelShot** [comment] 2016-05-11 23:35
Dont mind the reference, wrong link sorry

**Comment by Zero5211** [comment] 2016-05-12 03:53
I am also experiencing this issue. http://pastebin.com/DLLs7QXg

Version 1.7.10-2.3.0.424_beta
Same thing. Reika's mods + EnderIO = crash during startup

**Comment by HenryLoenwind** [comment] 2016-05-12 06:36
ok, ok, let's call this "confirmed". No more "me too"s needed ;)

**Comment by dabaer** [comment] 2016-05-13 13:59
Please see #3301 for the client side to this issue.

**Comment by SteelShot** [comment] 2016-05-15 22:22
#3303 Seems to have fixed my issues, havent crashed as of yet, client or server

**Comment by Hiranus** [comment] 2016-05-17 08:30
@SteelShot could you tell me how/where did you get updated EIO that fixes this?

**Comment by HenryLoenwind** [comment] 2016-05-17 08:39
@Hiranus either by compiling it yourself or by nagging @tterrag1098 to pull that PR and release a new version

**Comment by Hiranus** [comment] 2016-05-17 09:15
I never compiled anything in java, and if I'm not mistaken ill need a lot of other libs etc to do this.... Could someone share compiled version with me? I will be very very grateful. :)  @tterrag1098 Could you please release new version with this fix?

**Comment by HenryLoenwind** [comment] 2016-05-17 12:35
because you asked nicely: http://loenwind.info/EnderIO-1.7.10-2.3.0.t3_beta.jar

**Comment by Hiranus** [comment] 2016-05-17 12:47
Thank you :)

**Comment by SteelShot** [comment] 2016-05-17 13:12
Is this just with #3303 changes or anything else has been done in the jar Henry?

**Comment by notchriss** [comment] 2016-05-17 17:16
Doesn't work:
Exception in server tick loop

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraft/client/entity/EntityClientPlayerMP

java.lang.NoClassDefFoundError: net/minecraft/client/entity/EntityClientPlayerMP
at crazypants.enderio.EnderIO.processImc(EnderIO.java:741)
at crazypants.enderio.EnderIO.onImc(EnderIO.java:723)

**Comment by HenryLoenwind** [comment] 2016-05-17 18:10
That is a clean compile from the branch that is PRed above. Only other difference from 425 is the build number ("t3").

**Comment by notchriss** [comment] 2016-05-17 18:16
Thank you, it works fine so far!

**Comment by Kataiser9** [comment] 2016-05-18 20:18
Thanks for the changed version - though I still get a crash when ChC is installed. Completely different crash message, but I'm not sure if it's related to this issue or not. I'd paste the log, but it looks like someone else already did so in https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/836 which was (perhaps erroneously) marked as a duplicate. (Sorry, not sure how to link issues from other repositories.)

**Comment by HenryLoenwind** [comment] 2016-05-18 20:44
that's a dupe of #3301, not if this one.

**Comment by Haggle1996** [comment] 2016-05-22 20:05
Using @HenryLoenwind's t3 build and v13b of DragonAPI, I'm still receiving this crash on the server side. Any ideas what I'm doing wrong?

**Comment by SteelShot** [comment] 2016-05-22 20:11
try this one, i've compiled this myself, tho nothing has been changed apart the #3303 pull request
https://goo.gl/hIBwhz

**Comment by Haggle1996** [comment] 2016-05-22 20:40
Thanks, @SteelShot, but no joy on my end. Exact same crash. I'll poke around some more on my end; regenerate some configs.

**Comment by notchriss** [comment] 2016-05-22 20:58
Just a wild guess, but is your EnderCore up to date as well?

**Comment by HenryLoenwind** [comment] 2016-05-22 21:02
Also, is it the exact same crash, same line numbers in the stack trace? If so, then you are not using the new jar. Those line numbers have changed. If not, please post the stack trace.

**Comment by Haggle1996** [comment] 2016-05-22 21:43
Figured out the issue...specifically, @ReikaKalseki hasn't yet released a v13c that fixes the issue (see his note on [#3301](https://github.com/SleepyTrousers/EnderIO/issues/3301#issuecomment-219120770), so I made a one-off Ender IO to correct the shielded block until he drops a permanent fix.

**Comment by ReikaKalseki** [comment] 2016-05-22 23:41
The OOB is triggered by CC, but the serverside crash is on EiO's end, and nothing will ever come from me to fix it.

**Comment by Haggle1996** [comment] 2016-05-22 23:47
@ReikaKalseki, the incoming shielded block from ChromatiCraft isn't correctly formatted with [modid]:[blockid]. Fixing this fixes the crash (after applying the pull request to EIO posted earlier). I noticed you've just commented out the line on your CrC github since v13b. There's two separate issues here, one on each side.

**Comment by ReikaKalseki** [comment] 2016-05-23 01:15
Yes, I know, and that is fixed.

**Comment by Morpheus1101** [comment] 2016-05-23 08:55
Unf, due to the fix in this EnderIO vers not being released to curse, im unable to use it in my modpack, so i'll wait for a proper release of either mods with a fix to occur since curse rejects the patched version.

**Comment by aking4125** [comment] 2016-05-27 00:45
None of the above jars worked for me. And creating them myself with that pull request did nothing. Does Endercore need updating? According to the Github it hasn't been touched in a while so I don't know.

**Comment by SteelShot** [comment] 2016-05-27 01:03
Crash log? Is it EXACTLY the same?

**Comment by aking4125** [comment] 2016-05-27 01:08
It's extremely close but pretty much yeah. 

[crash-2016-05-24_04.31.13-server.txt](https://github.com/SleepyTrousers/EnderIO/files/285614/crash-2016-05-24_04.31.13-server.txt)

[crash-2016-05-24_04.01.35-server.txt](https://github.com/SleepyTrousers/EnderIO/files/285615/crash-2016-05-24_04.01.35-server.txt)

**Comment by SteelShot** [comment] 2016-05-27 01:11
Do you see a difference?

Between this?
`cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraft/client/entity/EntityClientPlayerMP
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:744)
    at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97)
    at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:319)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:210)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)`

And this?
`cpw.mods.fml.common.LoaderException: java.lang.ExceptionInInitializerError
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:744)
	at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:319)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:210)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)`

**Comment by aking4125** [comment] 2016-05-27 01:14
Yes. I mean regardless, it's done with both those jars above. As you can see, they didn't work. 
Works on the client though.

**Comment by SteelShot** [comment] 2016-05-27 01:15
Give me your config, i think theres an error in black listing, there might be missing ":" somewhere

**Comment by aking4125** [comment] 2016-05-27 01:17
What config? The normal EnderIO.cfg? Those two jars are the ones that was posted above.

**Comment by SteelShot** [comment] 2016-05-27 01:17
the cfg file

**Comment by aking4125** [comment] 2016-05-27 01:20
Hopefully it's the correct one. Since I can upload it as is. I just .zipped it.
[EnderIO config.zip](https://github.com/SleepyTrousers/EnderIO/files/285623/EnderIO.config.zip)

**Comment by SteelShot** [comment] 2016-05-27 01:28
Try this [EnderIO.jar](https://www.dropbox.com/s/jskgexwll67mjde/EnderIO.cfg?dl=1), beware there is more changed here: Pull Requests #3309, #3303, #3287, #3289.

And try this [EnderIO.cfg](https://www.dropbox.com/s/jskgexwll67mjde/EnderIO.cfg?dl=1), it is default, nothing has been changed. Run without making changes if it works, do your changes then, if something breaks again revert changes back.

**Comment by aking4125** [comment] 2016-05-27 01:30
Alright. I don't remember doing any changes to the EnderIO config, maybe somebody else did here. And I can't get your jar, it just downloads the .cfg again.

**Comment by SteelShot** [comment] 2016-05-27 01:47
Is it working? Read the message above

**Comment by aking4125** [comment] 2016-05-27 02:31
I did read the message. Please don't treat me like a child. I was busying doing work related stuff. The server with your config and the jar file you created wayy before is loading.

**Comment by HenryLoenwind** [comment] 2016-05-27 11:48
now that you have finally posted your log, I can tell you that your are in the wrong ticket. That crash has nothing to do with this problem. Go to #3301

**Closed** 2016-05-28 17:38 UTC
Labels: bug, Code Complete
