### ISSUE TITLE
Recipes config file recipe_materials.xml is invalid: Rejecting crafting recipe without any items, only empty spaces in <grid>

### ISSUE THREAD

**Issue by mrjewel** [SleepyTrousers/EnderIO#3768] opened 2016-10-10 15:59 UTC
The first problem is about Iron Chests and Extra Utilites 2, their problem is about invalid item names such as it should be "iron" but it's "ıron".
I couldn't change these names and I removed these 2 mods.
Then a different problem has started:

java.lang.RuntimeException: Recipes config file recipe_materials.xml is invalid: Rejecting crafting recipe without any items, only empty spaces in <grid>
- EnderIO: EnderIO-1.10.2-3.0.1.107_beta
- EnderCore: EnderCore-1.10.2-0.4.1.54-beta
- Minecraft: 1.10.2
- Forge: 1.10.2-forge1.10.2-12.18.1.2094

http://pastebin.com/AH5hSZ1P

**Comment by MrNinja93** [comment] 2016-10-10 21:26
Duplicate of https://github.com/SleepyTrousers/EnderIO/issues/3762

Don't make multiple issues for the same problem just update the original, makes it easier for the devs.

**Comment by HenryLoenwind** [comment] 2016-10-10 22:34
About the "i": You're probably running with a Turkish locale, which will throw off many mods that expect that the lowercase of I always is i, not ı.

I am a bit surprised about the Ender IO config folder's name. We explicitly use Locale.US for the lowercasing.

You can try adding "-Duser.language=en -Duser.country=US" to the JVM startup parameters. In theory this should fix all those problems. Please report back if this also fixes the " Rejecting crafting recipe without any items" thingy.

**Comment by HenryLoenwind** [comment] 2016-10-10 22:38
PS: I think I found it. There's a toLowerCase() (without locale) in Forge itself...

**Comment by mrjewel** [comment] 2016-10-11 14:45
OK, thank you i will report back if something happens...

**Comment by HenryLoenwind** [comment] 2016-10-11 15:09
Oh, I forgot do add: when I set my environment to Turkish, I get the same error. And a whole lot of other (non-fatal) errors at startup that make it quite clear to me that the game would be unplayable if it could start up.

I'm contemplating adding code to force the game into an English locale if it detects Turkish as the system locale. For the player that'd mean that they'd have to select their language manually and that numbers would be formatted like "1,234.56". But it would fix all those problems at once, even for those other mods you had problems with. What do you think about that?

**Comment by mrjewel** [comment] 2016-10-11 15:11
Yeah, that would be very good, 2 targets with 1 shot. 
Also: I added the language thing to the JVM startup parameters, It doesn't crash after the forge loading screen 2/7.
But it stucks at 3/7 forever.

**Comment by mrjewel** [comment] 2016-10-11 18:09
EDIT: Crash problem has been fixed BUT my weak computer can't carry mods, It was carrying 1 year ago but can't carry mods now.

**Comment by mrjewel** [comment] 2016-10-12 18:50
Fixed the all problems! Just remade my modpack to 1.8.9 and I can play with the same mods but with a lower version but, I can play. My toaster isn't able for 1.10.2 +mods.

**Closed** 2016-11-05 18:04 UTC
Labels: 1.10, Logfile Missing
