### ISSUE TITLE
Random Crash and im hoping maybe you folks can help

### ISSUE THREAD

**Issue by Drakkon37** [SleepyTrousers/EnderIO#3281] opened 2016-04-25 00:06 UTC
#### Issue Description:
Random crash to desk top, 1.7.10 - 2.3.0.42_beta

Players are randomly getting crashed to desk top with the same error. Tping them to another location alows them to log back in but if they stay in the location that they crashed in the will crash again. Currently both the server and the client files for the wither and skeleton are set to false.

http://pastebin.com/Y86URF7e

One of many crash reports.

**Comment by AnrDaemon** [comment] 2016-04-25 00:09
You have well over 200 enabled mods.
What made you believe that it is an issue with EIO? (And do fix your pastebin URL, pretty please.)

**Comment by Drakkon37** [comment] 2016-04-25 00:30
Take two for the pastebin  
[http://pastebin.com/ZZzdqtZE](url)

**Comment by Drakkon37** [comment] 2016-04-25 00:31
http://pastebin.com/ZZzdqtZE

this link works

**Comment by VT-14** [comment] 2016-04-25 02:18
I don't see anything in that log pointing at EnderIO, though I don't see it pointing at anything in particular.  Only issue that I saw (apart from it being a crash log) is that EIO found an outdated RF API, but couldn't figure out which mod it was from.

Do the server logs say anything interesting when one of these players crashes?

**Comment by Drakkon37** [comment] 2016-04-25 02:59
Nothing of note, Back to the drawing board.... only thing i have been finding with the stacking error it shows put me near here thats why I tried here.

**Comment by tterrag1098** [comment] 2016-04-25 13:00
This error is usually caused by having different EnderZoo configs on the client and server.

**Comment by Drakkon37** [comment] 2016-04-25 13:07
Thank you I will start with that then!

**Comment by HenryLoenwind** [comment] 2016-05-04 01:16
9 days? closing. Hope you fixed your problem.

**Closed by HenryLoenwind** 2016-05-04 01:16 UTC
