### ISSUE TITLE
Spammed Explosion Sounds

### ISSUE THREAD

**Issue by Divertise** [SleepyTrousers/EnderIO#5124] opened 2019-05-05 04:34 UTC
#### Issue Description:

Endless explosion sounds with alloy smelter and slice'n'splice. I am not sure if the other machines did the same thing, but it was like that ALL THE TIME.

#### What happens:

When I placed down the Slice'N'Splice or the Alloy Smelter with any of the 3 required capacitors, there was never-ending explosion sounds going on behind either machine. It stopped when I relogged, but it still happens when I am trying to make something or smelt something.

#### What you expected to happen:

I expected the machine to regularly process the items and create it without the explosion sounds or anything.
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.12.2-5.0.43
- EnderCore: EnderCore-1.12.2-0.5.56
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.5.2825
- SpongeForge? No
- Optifine? Yes, manual placement of 1.12.2 HD U E3
- Single Player and/or Server? Server.

#### Your most recent log file where the issue was present: 
I don't believe there were any.

**Comment by Ommina** [comment] 2019-05-05 05:02
This feels a lot like #5107

**Comment by SplitInfinitive** [comment] 2019-05-05 09:30
duplicate of #5107

**Closed** 2019-05-05 10:47 UTC
Labels: 1.12, Duplicate

**Comment by tyler489** [comment] 2019-05-05 13:12
I'm going to say Mekanism power cables?
