### ISSUE TITLE
Conduit lag

### ISSUE THREAD

**Issue by sfPlayer1** [SleepyTrousers/EnderIO#1959] opened 2015-02-18 09:53 UTC
I've observed 3 issues with conduits (potentially) causing lag:

1. Every conduit tile entity ticks
The conduits are usually the primary single contributor to the amount of ticking tile entities as its pipes are used several thousand times on a server. Even an empty updateEntity() causes significant overhead in the quantities conduits are typically being used. Managing that many TEs during chunk load+unload also causes issues if something causes the chunks to flicker.

2. Redstone conduits cause lag spikes
From my observations redstone conduits are currently one of the more frequent sources of heavy lag spikes on modded servers besides Mekanism and world gen. See http://forum.industrial-craft.net/index.php?page=Thread&postID=180844#post180844 for a few VisualVM compatible nps files showing lag spikes of 1.2 seconds each. I've only looked at the last 3 which point to EnderIO.
Depth first search during network lookup/propagation (BFS is much better) and omnidirectional redstone settling issues as mentioned below may be the root cause of these.

3. Conduits are too aggressive at loading chunks for propagating connectivity. It's very beneficial to just run with what's loaded by checking blockExists or querying ChunkProviderServer.loadedChunkHashMap directly instead of trying to discover the network  into unloaded chunks. It's best practice in other mods to only load chunks if that'd actually cause items to be droped, which should never be the case since EIO conduits teleport items instantly as far as I'm aware.

**Comment by 6210classick** [comment] 2015-02-18 11:03
can you provide more information ? like what versions EIO & TE & Forge are you using ?

does the redstone conduit problem also occurs with the insulated redstone conduit ? have yo tried cover them up with conduit facades ?

**Comment by PsionicArchon** [comment] 2015-02-18 23:51
Out of pure curiosity, have any of you been experiencing poor frametate around redstone conduit bundles?

**Comment by sfPlayer1** [comment] 2015-02-19 10:57
I don't have any extra information since I don't use this mod myself or actually play much MC at all atm, I've only seen it several times in nps files sent to me for analysis. The issues mentioned appear to be not just minor oversights but architectural shortcomings, thus it's unlikely to be fixed. I quickly verified issue part 1 by looking at the source code.

From experience a good guess for the cause of the redstone conduit problems would be having less than vanilla's 1 loss/block, which is required to reach a steady state from omnidirectional propagation quickly. Not doing this requires significant extra care, which is easy to get wrong as soon as there's a connection back to some vanilla redstone for example.

This report may be the first of its kind due to the various issues being very difficult to track down to EnderIO although those performance problems are likely quite widespread. The spike heavy nature of the slowdowns combined with heavy inlining by the JVM makes it practically impossible to see in Opis and difficult to spot in Sampler while sampling normally. The lag spikes can usually be observed with Sampler's spike trigger, assuming there's a problematic setup in the world, which I don't know the conditions for. It may be required to disable the JVM's inlining or even run in interpreter only mode to see more, which of course has significant influence on the unit under test.

**Comment by tterrag1098** [comment] 2015-02-23 07:50
(1) should be at least somewhat resolved in this build: http://ci.tterrag.com/job/EnderIO/352/

**Comment by BakermanLP** [comment] 2015-03-06 07:30
Doesn't seem to be solved right now. Tested version is EnderIO-1.7.10-2.2.8.355.jar. This is a screenshot of JVisualVM of a spike file.

@sfPlayer1 Thanks for pointing me to the spiketrigger option in sampler.jar!

The NPS Spike File can be found here: http://solder.projectret.de/spike-159857-3235395417.nps

This tells me, that in about 160 seconds the server tries to do redstone conduit updates for about 159.8 seconds. 

![enderio-probs](https://cloud.githubusercontent.com/assets/3873443/6521629/6cc48a88-c3da-11e4-908f-e65ae9f0fd43.jpg)

Here are some pure numbers about the loaded chunks, entities and so on:
[08:28:32] [Server thread/INFO]: Overworld (0): 298 chunks, 6224 tes, 73103 ticking tes, 4621 entities
[08:28:32] [Server thread/INFO]: Nether (-1): 52 chunks, 9022 tes, 20 ticking tes, 5 entities
[08:28:32] [Server thread/INFO]: The End (1): 0 chunks, 0 tes, 0 ticking tes, 0 entities
[08:28:32] [Server thread/INFO]: CompactMachinesWorld (3): 3 chunks, 116 tes, 66 ticking tes, 0 entities
[08:28:32] [Server thread/INFO]: SpectreWorld (2): 0 chunks, 0 tes, 0 ticking tes, 0 entities
[08:28:32] [Server thread/INFO]: Overworld (12): 16 chunks, 2542 tes, 20 ticking tes, 6 entities
[08:28:32] [Server thread/INFO]: Underdark (-100): 0 chunks, 0 tes, 0 ticking tes, 0 entities
[08:28:32] [Server thread/INFO]: Total: 7 dimensions, 369 chunks, 17904 tes, 73209 ticking tes, 4632 entities

**Comment by krakel** [comment] 2015-03-06 09:05
If you follow these trace, you will find a big endless loop at crazypants.enderio.conduit.AbstractConduitNetwork.setNetwork(). These method produce a recursive call on itself to set some conduits as part of a bundle. What happens on big non intialized or damaged networks? The recursive call on each found conduit can produce a ping pong effect.

**Comment by c0nnex** [comment] 2015-03-07 17:27
I second this. 
crazypants.enderio.conduit.AbstractConduitNetwork.setNetwork()
causes massive lags on my server as well.
(small server only 4 people)
We are running EnderIO-1.7.10-2.2.8.349

![enderiolag](https://cloud.githubusercontent.com/assets/8324035/6542416/a05dfe74-c4f7-11e4-9b61-be165989731f.PNG)

**Comment by c0nnex** [comment] 2015-03-08 03:18
I spent a lot of time today to nail this issue down.
I turned out that the same network (437 nodes) is destroyed over and over again resulting in each update taking over 5 minutes!
The destroy of the network happens in 
crazypants.enderio.conduit.redstone.RedstoneConduit.updateEntity
caused by a walkthrough of the entities, destroying the newly created network. It ONLY happens for redstone networks.

A Enderio-Fork with debugoutput added ( search fro DBGCX in log) can be found https://github.com/c0nnex/EnderIO or the commit https://github.com/c0nnex/EnderIO/commit/8c28fc7b12f44a68605934b20f39e708211cb3dd

I'm unsure how to fix this ..... seems somehow related to chunkloaders.

**Comment by c0nnex** [comment] 2015-03-08 04:21
When changing 
RedstoneConduit.java:64
to
protected boolean neighbourDirty = false;

the startup is faster, but still the networks get destroyed every minute, causing a lag spike.
*sigh*

**Comment by tterrag1098** [comment] 2015-07-26 05:59
This is likely partially combated by #2672

**Comment by codewarrior0** [comment] 2015-12-14 11:52
Version 2.3.0.421_beta, as included with FTB Infinity.

I'm seeing something similar to https://github.com/SleepyTrousers/EnderIO/issues/1959#issuecomment-77518088

This began happening after I laid a few hundred insulated conduits to remote-control some digging machines. It gets much worse when I try to move away from my base. I am not using any chunkloaders. 

![image](https://cloud.githubusercontent.com/assets/307683/11780270/c7603a9c-a204-11e5-8aea-fa5b96cedb19.png)

**Comment by HenryLoenwind** [comment] 2015-12-14 16:04
@codewarrior0 What you are seeing here is the conduit network being destroyed and reforming itself over and over again because parts of it get unloaded when you move away. In addition, chunks at the border of loaded chunks tend to reload because a block in a still loaded chunk tries to access its unloaded neighbor. Half of that times goes into notifying other blocks about the changing redstone state of the network.

If anyone had a good suggestion on how to have a multi-block structure than can span dozens of chunks and handle partial loading and unloading instantly, your input would be welcome.

In the meantime, I'd recommend to keep (redstone) conduit networks as small as possible in regard to chunks. You can also try to segment your network be connection smaller segments with a piece of redstone dust at a chunk border (if you only use one channel).

**Comment by tterrag1098** [comment] 2015-12-14 19:05
@HenryLoenwind Actually no, redstone conduits recreate their network any time *anything* changes. It's quite a large issue and one that requires a rewrite of the entire thing to fix. I believe redstone conduits are at the heart of most of the conduit performance issues.

**Closed** 2016-05-28 13:16 UTC
Labels: bug
