### ISSUE TITLE
Cross-mod crash with Thermal Expansion

### ISSUE THREAD

**Issue by Cobra1117** [SleepyTrousers/EnderIO#2571] opened 2015-06-11 01:27 UTC
After updating to 2.2.8.381, my server has been occasionally crashing with this log:
http://pastebin.com/0b1E25fD

**Comment by tterrag1098** [comment] 2015-06-11 01:50
Update your TE

**Comment by Cobra1117** [comment] 2015-06-12 04:26
I'm running Thermal Expansion 4.0.1-182, which is the latest version available (as far as I can tell)

**Comment by MatthiasMann** [comment] 2015-06-12 05:51
This is a duplicate of #2166

**Closed by MatthiasMann** 2015-06-12 05:51 UTC
Labels: Duplicate
