### ISSUE TITLE
Incompatibility with Liteloader

### ISSUE THREAD

**Issue by ThatCynicalX** [SleepyTrousers/EnderIO#4754] opened 2018-07-06 19:43 UTC
#### Issue Description:
Bad recipe is reported when using EnderIO with Liteloader on 1.12.2, not allowing the player to go into the main menu after startup.

#### What happens:
Reports that recipes/items.xml is a "bad file" and that it could not find a crafting ingredient for 'blockHopper' in the Filter Basic recipe.

#### What you expected to happen:
Recipes/items.xml is not a bad file and the game would load.

#### Steps to reproduce:

1. Install Forge version 14.23.4.2705
2. Install Liteloader 1.12.2, EnderIO 5.0.26, and EnderCore 0.5.31
3. Open Minecraft

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.26
- EnderCore: 0.5.31
- Minecraft: 1.12.2
- Forge: 14.23.4.2705

#### Your most recent log file where the issue was present: 

https://paste.ee/p/SMKxf

**Comment by tterrag1098** [comment] 2018-07-06 20:35
This is caused by diethoppers, we don't know the exact reason but it's fixed by just removing it...

**Closed by tterrag1098** 2018-07-06 20:35 UTC

**Comment by CyanideX** [comment] 2018-07-06 21:04
WTF, @ThatCynicalX... why do you have my old avatar and a name that is basically a ripoff of mine? 😆

**Comment by ThatCynicalX** [comment] 2018-07-07 02:13
Omg, @CyanideX, I made the name on my own, and found this avatar searching it up xD

**Comment by ThatCynicalX** [comment] 2018-07-07 02:18
@tterrag1098 This does not occur without Liteloader, only when DietHoppers, Liteloader, and EnderIO are all installed

**Comment by Shadows-of-Fire** [comment] 2018-07-07 08:05
Liteloader doesn't play nice with registry replacements, which I believe diet hoppers currently does...

**Comment by mezz** [comment] 2018-07-09 06:34
Submitted an issue to LiteLoader here: http://develop.liteloader.com/liteloader/LiteLoader/issues/53
