### ISSUE TITLE
SAG Mill recipes for Certus Ore/Crystal broken

### ISSUE THREAD

**Issue by srs-bsns** [SleepyTrousers/EnderIO#2356] opened 2015-04-23 15:10 UTC
Pull request https://github.com/SleepyTrousers/EnderIO/pull/2276, that was merged, changed the SAGMillRecipes_Core.xml entries for Certus Quartz Ore and Certus Quartz Crystal with the reason "conform to the Nether Quartz recipes", but it isn't in line with EIO's Nether Quartz recipes at all, nor is it in conformity with any other recipe from other mods for processing Certus Ore/Crystals.

EIO SAG Mill after above commit (Certus Quartz, charged or regular):
1 ore -> 1 Crystals, 1 dust
2 crystals -> 10% chance of 1 dust

The Certus Quartz recipes should be the same as the Nether Quartz recipes, which remain unchanged:
1 ore -> __2__ crystals, __10% chance of__ 1 dust
__1__ crystal -> __~~10% chance of~~__ 1 dust

To be in PROPER conformity with EIO's Nether Quartz recipes:
```
    <recipe name="ChargedCertusQuartzOre" energyCost="2400">
      <input>
        <itemStack  modID="appliedenergistics2" itemName="tile.OreQuartzCharged"  />
      </input>
      <output>
        <itemStack modID="appliedenergistics2" itemName="item.ItemMultiMaterial" itemMeta="1" number="2" />
        <itemStack oreDictionary="dustCertusQuartz" chance="0.1" />
      </output>
    </recipe>

    <recipe name="CertusQuartzOre" energyCost="2400">
      <input>
        <itemStack oreDictionary="oreCertusQuartz" />
      </input>
      <output>
        <itemStack oreDictionary="crystalCertusQuartz" number="2" />
        <itemStack oreDictionary="dustCertusQuartz" chance="0.1" />
      </output>
    </recipe>

   	<recipe name="ChargedCertusQuartzCrystal" energyCost="2400">
      <input>
        <itemStack modID="appliedenergistics2" itemName="item.ItemMultiMaterial" itemMeta="1" />
      </input>
      <output>
        <itemStack oreDictionary="dustCertusQuartz" />
      </output>
    </recipe>

    <recipe name="CertusQuartzCrystal" energyCost="2400">
      <input>
        <itemStack oreDictionary="crystalCertusQuartz" />
      </input>
      <output>
        <itemStack oreDictionary="dustCertusQuartz" />
      </output>
    </recipe>
```

Regards,
~~Modding is srs bsns~~

**Comment by Lilylicious** [comment] 2015-04-23 15:41
There's a pull request up that fixes this from @Adaptivity 

(I may also be apologizing for doing a pull request while tired and fucking up certus quartz)

**Comment by Adaptivity** [comment] 2015-04-23 16:10
Everything fixed. Just waiting for @tterrag1098 merge.

**Comment by tterrag1098** [comment] 2015-04-23 20:18
Duplicate of #2252

**Closed by tterrag1098** 2015-04-23 20:18 UTC
