### ISSUE TITLE
Item conduit not pulling from Immersive Engineering Gardening Cloche.

### ISSUE THREAD

**Issue by zackeezy** [SleepyTrousers/EnderIO#4291] opened 2017-07-17 14:00 UTC
#### Issue Description:
When I try to use Item Conduits with an Immersive Engineering Garden Cloche, it doesn't extract the items as I expect. 

#### What happens:
The EIO conduits connect, but no items move from the Cloche to another inventory even when the cloche end is set to extract always and the inventory end is set to insert.  I tested with TD ducts and those work, without a servo, but conduits don't. 

#### What you expected to happen:
The EIO conduits to move the items from the cloche to the other inventory.

#### Steps to reproduce:

1. boot up a world with both Ender IO and Immersive Engineering
2. Grow plants in the Cloche
3. Try to move the items out using item conduits. 
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.1.193
- EnderCore: 0.4.1.66
- Minecraft: 1.10.2
- Forge: 12.18.3.2254

#### Your most recent log file where the issue was present: 

N/A

**Comment by MatthiasMann** [comment] 2017-07-17 17:25
If TD is "extracting" without a servo then the cloche is pushing items out. As EIO conduits work on any other inventory means that the issue is at IE's side.

**Comment by HenryLoenwind** [comment] 2017-07-17 18:21
Is this a dupe? I thin I remember having read the same stuff before...

It seems the Cloche is NOT an inventory, so items cannot be pulled out. Instead it pushes items out using an incompatible protocol.

**Comment by zackeezy** [comment] 2017-07-17 18:40
Interesting.  And the fact that ducts are inventories means they can push to them?

**Comment by HenryLoenwind** [comment] 2017-07-22 11:13
Fixed in IE

**Closed by HenryLoenwind** 2017-07-22 11:13 UTC
Labels: 1.10, Bug in other software
