### ISSUE TITLE
Hard to track bug. Crash when someone else (?jumping?) in water with Dark steel armor

### ISSUE THREAD

**Issue by Sakata-MC** [SleepyTrousers/EnderIO#4715] opened 2018-06-16 17:05 UTC
It appears to be related to dark steel armor, though it could just be that I've only found one armor type that acts in the way the armor does.

I haven't narrowed down the exact enchant, either.  its a pain to track due to the many minutes of mod loading (Currently in All the Mods 3, and FtB Revelations), along with the multiplayer bit.

So it does only occur in multiplayer. If the person has dark steel armor on, and jumps around near another player, it will intermittently hard-freeze the java process. No CPU usage, no errors in log, just a hard freeze.  This doesn't happen to the one with the armor, but anyone else who is around.  

This only happens on the client.  The server just sees no traffic and boots player after a while with a disconnect.  The client very rarely will recover within the period it takes for the connection to be still valid, but 99% of the time it doesn't recover for quite some time (I've left it for an hour just to test).

I've been tracking down the bug for a while, and only recently thought of dark steel armor due to noticing a *lack* of crashes when playing with another friend who was using FtB Revelations.  However as soon as I donned dark steel armor, enchanted it, and went diving around in water, my friend said his client froze.  He was using Botania armor at the time. We switched armors and I jumped around in the water for ~5 minutes with not even a peep.  Then he jumped a few times and I immediately froze.  I *think* it may have something to do with double jump.

I'm really sorry I don't have anything concrete with logs or anything, but there are no logs, and it's hard to find a friend that wants to spend loading times for 10 minutes every time to test this crash.  Hopefully someone with a stronger setup can test/help test.

**Comment by tyler489** [comment] 2018-06-16 17:18
1. Please use the format provided.
2. What version of enderio are you using
3. What version of forge are you using.
4. What enchantments are on the armor 
5. Is the armor upgraded/empowered. 

Ill do some testing with a friend and see if we can reproduce.

**Comment by Sakata-MC** [comment] 2018-06-16 19:57
@tyler489 
1. Didn't really seem to fit the normal format since I can't figure out why the heck it's crashing or what it's in relation to. I'll try to stick with it for any other posts though.
2. EnderIO-1.12.2-5.0.20 - EnderIO-1.12.2-5.0.26  are the ones I know for sure, there may be more.
3. forge 2641 - 2707
4. Any I could throw on it.  All of the EIO specific ones (Glider for the exclusive one), normally throw the enchant that repairs for XP on it as well, but that doesn't seem to apply.
5. Empowered, normally don't bother until I can get to empowered 4 since the armor degradation is meh.

Thanks for looking into it, it's been bugging me to distraction for a while now.

@HenryLoenwind tagging the issue with an asinine tag doesn't add to the ticket in any meaningful way.  If I didn't care, I'd just not post.  The fact that I went through the trouble to a) make a post at all, and b) tried to be as detailed as possible, indicates that I think devs would want to know what it is, as I'm sure there are others -- being affected and not realizing the cause, not having enough knowledge to know where to report the issue, or... not giving enough of a damn to report it.

**Comment by EpicSquid** [comment] 2018-06-16 21:54
We have a format for a reason. Your version of it provides us with little to no information to go off. Please use the specified format.

**Comment by Sakata-MC** [comment] 2018-06-17 03:13
All information is already provided.

**Comment by EpicSquid** [comment] 2018-06-17 03:39
We don't have a "steps to reproduce" or the logs that are always available with the current state of minecraft which may contain information. If you can test it in an ender io-only instance that could help, but I understand if you cannot. If there are no logs at all, then something is severely wrong with your minecraft. A list of mods may be helpful, especially core mods.

**Comment by Sakata-MC** [comment] 2018-06-17 04:05
@EpicSquid I'm guessing you didn't read the description.
Steps to reproduce, do stuff in water, or other liquids. (described in much more detail above)
Logs: No crash log because the game does not crash. It freezes hard. As in "java process borks and doesn't respond at all" hard.  So the logs look like a normal session aside from the sudden stop of logging. I also mentioned this above. I know how to read the logs fairly well, and would have included them if I had any crash logs or suspicious entries in the console.  However there are none.  which is why its baffling. 

At first I thought this was an issue only I experienced.  Narrowed it down to liquids, then after months of dealing with it, friend complained about it about every time we'd set out together. Then a few other peeps chimed in with same issue. Noticed it only happened when I wore EIO armor (or they did if I was crashing). So thinking it was a modpack issue, we tried another server/pack, cheated in armor, jumped in water for a few minutes and he crashed, said so just after a double jump while in water.

**Comment by EpicSquid** [comment] 2018-06-17 04:34
Okay, this unfortunately isn't enough info for me to really be able to reproduce it as there are too many variables. If you can test it with an enderio-only pack, or try and remove as many core mods as possible, then that would be good. Also considering it is only happening to one user maybe corrupted player data? Its really hard to tell. Can you please attach whatever logs you have regardless, and perhaps use players sampler to test what is going on with it? A mod list would help as well. Also try updating graphics drivers, that could be related.

RE the format issue: The format we have defined makes the issue clear and concise, I could not tell from your original report what the issue was as there was a lot of story and speculation. A clear and concise report is what the format is designed for, that is all. The format you chose is also hard to understand from a glance, which I will admit is a minor issue, but it is extremely helpful for debugging if I can look over and see what the issue was and how to reproduce it in numbered steps without having to read the whole comment again.

**Comment by ttamnedlog** [comment] 2018-06-27 02:41
I'm not sure if my chiming in is helpful (considering that at the moment I also have nothing concrete), but I believe I was experiencing this on my FTB Revelation 2.0 server. I didn't even get as far as narrowing it down to double jumping in liquids, but my friend crashed almost anytime I came near him. The only reason I even suspected EnderIO was because it was early enough in our world that I was only wearing my own crafted iron and some empowered dark boots I found in a dungeon chest. I thought, "This is a long shot, but I'll take these boots off." I did (and haven't bothered to craft any dark armor since) and he hasn't crashed again.

But after reading this and having something a bit more to work towards, I might do some further testing and chime back in with something concrete if I can find it.

**Comment by ttamnedlog** [comment] 2018-06-27 13:57
@tyler489

My friend had to force quit, so no crash report I believe (or does force quitting still provide a crash report)?

**Comment by tyler489** [comment] 2018-06-27 14:38
Force quit doest generate one.

**Comment by EpicSquid** [comment] 2018-06-28 05:32
@ttamnedlog I am closing this issue as there isn't any usable information for the bug. If you do have it occur again please report it to the issue tracker and follow the formatting guides.

**Closed by EpicSquid** 2018-06-28 05:32 UTC
Labels: 1.12, Cannot reproduce, you don't care - why should we?
