### ISSUE TITLE
Crafter with juicer freezing game

### ISSUE THREAD

**Issue by Slind14** [SleepyTrousers/EnderIO#2614] opened 2015-06-27 19:07 UTC
Hey,
simple to replicate:
![](http://i.imgur.com/zG2AIrM.png)

```
"Server thread" - Thread t@401
   java.lang.Thread.State: RUNNABLE
	at crazypants.enderio.machine.crafter.TileCrafter.craftRecipe(TileCrafter.java:178)
	at crazypants.enderio.machine.crafter.TileCrafter.processTasks(TileCrafter.java:109)
	at crazypants.enderio.machine.AbstractMachineEntity.func_145845_h(AbstractMachineEntity.java:276)
	at crazypants.enderio.machine.AbstractPoweredMachineEntity.func_145845_h(AbstractPoweredMachineEntity.java:31)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

   Locked ownable synchronizers:
	- None

```

**Comment by MatthiasMann** [comment] 2015-06-27 19:08
Duplicate of #2552

**Comment by Slind14** [comment] 2015-06-27 19:09
:+1:

**Closed by MatthiasMann** 2015-06-27 19:08 UTC
Labels: Duplicate
