### ISSUE TITLE
Item conduits stopped working. Broke and replaced a piece and they started working again.

### ISSUE THREAD

**Issue by Ricket** [SleepyTrousers/EnderIO#3978] opened 2017-01-07 17:29 UTC
#### Issue Description:

I made a 4 minute video demonstrating the issue: https://youtu.be/Yfy1w2d1788

I have an item conduit network connecting between a couple chests (on different channels), a trash can, a Pearl Injector, and a Storage Drawers Controller. The whole system stopped moving items around after I came back from a trip to a friend's base ~1000 blocks away. The area is fully chunkloaded via FTButil. Once I broke and replaced one random item conduit in the middle (not attached to anything), everything started working.

#### What happens:

Item conduit network stops functioning

#### What you expected to happen:

Conduit network should never just stop functioning

#### Steps to reproduce:

1. Set up network, chunkload it
2. Teleport far away, and come back
3. Come back and see that nothing is being moved around.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO-1.10.2-3.1.156.jar
- EnderCore-1.10.2-0.4.1.62-beta.jar
- Minecraft: 1.10.2
- Forge: 2185
- Direwolf20-1.10 pack version 1.3.2

#### Your most recent log file where the issue was present: 

https://youtu.be/Yfy1w2d1788

**Comment by MatthiasMann** [comment] 2017-01-07 17:32
Duplicate of #3943

**Closed by MatthiasMann** 2017-01-07 17:32 UTC
Labels: 1.10, Duplicate
