### ISSUE TITLE
Sag mill processing when items have no place to go

### ISSUE THREAD

**Issue by Zaflis** [SleepyTrousers/EnderIO#1700] opened 2015-01-17 10:33 UTC
When i process ores, for example Tin ore, it has some secondary outputs: iron dust and cobblestone. I'm then feeding them directly to the slower alloy smelter machine. Items build up in Sag mill buffers, until tin dust and cobblestone go max 64 stacks.

Now then the buggy behavior begins; tin dust is slowly taken into alloy smelter, but that 1 stack of cobblestone still remains in there. It cannot increase, and in fact i think any new cobblestone is getting vaporized. Any time that tin dust amount reduces to 61 (or 62? i can't tell because it's moving 3 at the time), it processes another tin ore, regardless of what is in the secondary output slots.

What i'm expecting to happen is that eventually tin dust is all burned away and the secondary output slots will be smelted too.

Edit: What happens to the other secondary output, iron dust never reaches the 64 stack but remains 49 for me, after few hours of running all machines with octadic capacitor. So i assume if cobblestone has no place to go, it vaporizes all secondary outputs.

EnderIO-1.7.10-2.2.5.311

**Comment by 6210classick** [comment] 2015-01-17 12:08
you are using older version there is newer one 2.2.6 317 also update your FORGE to the latest

you were probably using dark steel balls as modifiers those have a problem in some old version it should be fixed now , also you might want to set an item conduit on a different side and filter it to extract only cobble stone with some speed upgrades to move cobblestone into it's own furnace a vanilla one with a chest as a buffer should be enough

or simply set an item conduit to extract everything that outputs from the sagmill to chest then connect that chest to 2 different alloy smelters one in alloys only mode and one in furnace only mode

**Comment by Zaflis** [comment] 2015-01-17 12:29
I'm not using darksteel balls or flint. There was 4 updates since the version i use, and at least i didn't see any mention related to this problem in any of the change logs. I'm playing a ftb pack and on principle not manually updating any mods or forge. If it bugs, it bugs (this is a minor bug) and i'll report it since it wasn't already. http://minecraft.curseforge.com/mc-mods/64578-ender-io/files

**Comment by tterrag1098** [comment] 2015-01-20 01:17
This is technically intended behavior, though I do see the issue you are describing. The SAG mill is happy to process any recipe even if it does not have enough slots to fit *all* the results. Marking this as an enhancement.

**Closed** 2016-05-28 13:04 UTC
Labels: enhancement
