### ISSUE TITLE
Reinforced Obsidian crash

### ISSUE THREAD

**Issue by flintnsteel** [SleepyTrousers/EnderIO#3304] opened 2016-05-15 04:40 UTC
#### Steps to reproduce:

1. Look at Reinforced Obsidian placed block, can reproduce easily
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):
Running Infinity 2.5.0
- EnderIO: 2.3.0424_beta
- EnderCore: 0.2.0.32_beta
- Minecraft: 1.7.10
- Forge: 10.13.4.1614

#### Your most recent log file where the issue was present: 

http://pastebin.com/nnHRxnt0

**Comment by MatthiasMann** [comment] 2016-05-15 06:17
Duplicate of #3290

Also - why did you not fill out the EnderCore version?

**Closed by MatthiasMann** 2016-05-15 06:17 UTC
Labels: Duplicate

**Comment by flintnsteel** [comment] 2016-05-15 16:32
Im sorry I thought I added it. Also, I saw that bug thread and I figured this was separate because I don't had a thaumometer.

 Anyways looks this there's a fix, so thanks for the reply.

**Comment by HenryLoenwind** [comment] 2016-05-17 08:37
everything that does "pickBlock" will trigger this crash. middle mouse button in create mode, thaumometer, maybe even WAILA...
