### ISSUE TITLE
Insulated redstone conduit and advanced computer from computercraft

### ISSUE THREAD

**Issue by blarghhh** [SleepyTrousers/EnderIO#2811] opened 2015-09-14 04:55 UTC
i am using an extended version of dw20's reactor program which allows 16 turbines (due to redstone color api limitation). however, the insulated redstone conduit always exhibit 2 problems.

1. after i restart my server (private with friends), the conduit always outputs a high signal level from the advanced computer,
2. it always fails to transmit a redstone signal on a 4th color. 

ref:http://www.computercraft.info/forums2/index.php?/topic/24495-bigreactors-control-script-up-to-16-turbines-extension-of-direwolf20s-script/

info:i am using tesseracts to control the steam flow instead of using the railcraft tanks. so the conduits are attached to the tesseracts to control whether they turn on or not.

**Comment by tterrag1098** [comment] 2015-09-14 04:56
Duplicate of #2658

**Closed by tterrag1098** 2015-09-14 04:56 UTC
