### ISSUE TITLE
Item Conduits stop working

### ISSUE THREAD

**Issue by calloatti** [SleepyTrousers/EnderIO#4155] opened 2017-04-12 12:11 UTC
#### Issue Description:

Item conduits stop working. I know this has been reported before:

#3978
#3873
#3943

#### What happens:

Item conduits stop working

#### What you expected to happen:

Item conduits should not stop working

#### Steps to reproduce:

I have a saved game where this happens everytime you load the map. You have to break and replace a counduit to make it work again. Then it randomly stops working again for who knows what reasons.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:EnderIO-1.10.2-3.1.180
- EnderCore:EnderCore-1.10.2-0.4.1.65-beta
- Minecraft: 1.10.2
- Forge:forge-1.10.2-12.18.3.2281-universal.jar

#### Your most recent log file where the issue was present: 

I will add screenshots, logs, stick right click diagnostics in a comment.

Anything else you need to solve this I will try to provide. I can even post the MultiMC Minecraft instance and the saved map to reproduce the problem.

Images of general setup:

http://imgur.com/a/258T6

**Comment by calloatti** [comment] 2017-04-12 12:21
Full log.

When the world is loaded only some conduits are working. After break and replace all conduits start working again. Check bottom of log for before and after conduit right click with hand.

**Comment by calloatti** [comment] 2017-04-12 12:24
This is what the setup looks like. There are nine farming stations all connected to an RS interface.

http://i.imgur.com/JkJDVkG.png

851,112 is the interface. The nine chunks are the farming stations.

**Comment by calloatti** [comment] 2017-04-12 12:34
Stick right click after loading world: https://paste.ee/p/jN4mJ

Stick right click after break and replace: https://paste.ee/p/hKEfV

**Comment by PapiDimmi** [comment] 2017-04-12 14:45
Firstly, if you know that this has been posted before (and three times before at that), why post it again?

Secondly, can you please use [Pastebin](https://pastebin.com/) or [Hastebin](https://hastebin.com/) for logs to prevent large walls of text?

Lastly, please edit your comments and posts rather than posting thrice in a row.

**Comment by L3thal1ty** [comment] 2017-04-13 06:23
Well, let me jump on the bandwagon here instead of starting yet another issue.

I am playing Age of Engineering 1.10.2
Forge: 12.18.3.2254
Ender IO: 1.10.2-2.2.1.103
EnderCore: 1.10.2-0.4.1.65-beta

This issue happens for me when an item conduit crosses a chunk border, but not randomly. I am based in the mining dimension, and when I travel to the overworld and then teleport to a wp far away, that distance seems to break the conduits ability to read each other. I have tried FTB utils chunk loading, and even added in persistent bits, but neither seems to solve the issue. Breaking and replacing any conduit in the line will fix the issue.

**Comment by HenryLoenwind** [comment] 2017-04-13 06:39
um, FTB utils chunk loading is one of the known causes for this...

**Comment by L3thal1ty** [comment] 2017-04-13 06:43
Ok, so if I turn off FTB utils chunk loading, and rely on just persistent bits, might that resolve the issue? or will I have to uninstall FTB utils completely? I am not sure what the dependencies are associated with it.

**Comment by HenryLoenwind** [comment] 2017-04-13 06:47
I'm not sure, I just know that disabling the loaded chunks in the GUI does not work. Disabling the chunkloading feature in the config may...

And if this issue wasn't spread out over 20 tickets, you might have noticed that this: https://github.com/LatvianModder/FTBUtilities/issues/360 is linked in quite recently.

**Comment by L3thal1ty** [comment] 2017-04-13 07:06
An interesting read. Sorry to have bothered everyone since it's clearly not an EIO bug. If I knew how to disable the chunkloading feature completely, I would try that, however, I am not that skilled with things like that.

**Comment by calloatti** [comment] 2017-04-13 11:02
I am not using FTB utils chunk loading. In fact no FTB anything, all the mods have been downloaded one by one by myself. 

I added the Persistent Bits mod and added a Persistent Bits chunkloader to see if this would solve the issue, no change.

**Comment by HenryLoenwind** [comment] 2017-04-13 18:26
ok, can you give me a stick-click of the conduits that are not connecting? I'm interested in the "getExternalConnections" value they have server side. I'd also like to see if the network ID is the same as on those conduits that do work.

This is the first trace that actually shows some anomaly. While the list of conduits coordinates is the same in both broken and working states and the conduits still visually connect, the insert/extract list does differ. The problem with this problem is that we neither do know what happens, nor which state the game is after it happens. Usually we have one or even both of them...

**Comment by calloatti** [comment] 2017-04-13 20:46
Great. 

Bad news: my son was playing on the map. He just added conduit facades everywhere and removed blocks to make it easier to navigate the conduits maze. He did not touch the conduits themselves at all. 

Now no conduit works after loading game, before we had some working after game load, now no one works.

stick-click of all connections after loading game, none works:

https://paste.ee/p/unz4J

stick click after break-replace one conduit, everything works:

part 1: https://paste.ee/p/sw1Ld
part 2: https://paste.ee/p/83iP6

I guess the former situation where some worked and some did not was a better scenario to work with.

**If it helps I can revert to a backup where some work and some don´t and post the stick clicks. If you need that just ask.**

**Comment by calloatti** [comment] 2017-04-13 22:15
I just went ahead and restored a backup. On game load we have 5 broken and 4 working connectors:

http://imgur.com/a/hb2J7

stick-clicks:

https://paste.ee/p/bJUbD

After breaking and replacing one conduit evrything works.

stick-clicks:

https://paste.ee/p/ERG7T

Hope all this helps. Anything else you need just ask.

**Comment by HenryLoenwind** [comment] 2017-04-14 07:25
Thank you.

So to me it looks like the network forms correctly and it even picks up the external connections---they just don't work. I added code to force refresh the external connections on the first tick after the conduit is loaded from the save file. Maybe that'll help. Could you try it out, please? It is in this build: http://ci.tterrag.com/job/EnderIO-1.10/182/

**Comment by calloatti** [comment] 2017-04-14 18:33
It seems to be working. Tested with 180 and 182

180 keeps failing, 182 connectors work on game load. I will keep you updated if connectors fail randomply or fail on load again. Thanks!

EnderIO is great by the way. Thank you for so many hours of fun.

**Comment by HenryLoenwind** [comment] 2017-04-14 20:34
Thx. Without those logs I'd never found a solution.

(yes, "a", not "the". This is like a door that doesn't latch right. You close it and then press against it for the latch to take. That's "a" solution, a better one would be to have the door fixed...)

**Comment by ChaoticTabris** [comment] 2017-04-18 14:04
Similar problem happening to me. Tried removing FTBUtils since some people mentioned that could be causing the problem but didn't fix. There is a small video to show what happened: https://gfycat.com/LightAridBubblefish

**Comment by ChaoticTabris** [comment] 2017-04-18 15:10
Was suspecting my problem could be related to TE instead of this bug but KingLemming says the problem is not on TE's side: https://github.com/CoFH/Feedback/issues/169#issuecomment-294871013

**Comment by calloatti** [comment] 2017-04-18 21:18
@ChaoticTabris did you try the version posted here: https://github.com/SleepyTrousers/EnderIO/issues/4155#issuecomment-294106779

**Comment by ChaoticTabris** [comment] 2017-04-18 21:18
@calloatti I did. Still having the same problem =/

**Comment by ktole1999** [comment] 2017-04-19 12:13
any idea when this version might be released to Curse for pack updates?
http://ci.tterrag.com/job/EnderIO-1.10/182/

**Comment by HenryLoenwind** [comment] 2017-04-19 16:06
@ktole1999 12 hours ago

**Comment by ktole1999** [comment] 2017-04-19 18:02
awesome. thanks.

**Closed** 2017-05-05 17:51 UTC
Labels: 1.10, Code Complete, Duplicate

**Comment by Musouka42** [comment] 2019-07-01 15:28
Hello!

This problem still seems to be occurring.

Modpack: Project Ozone 3 (Version 3.0.40)
EnderCore: 0.5.57
EnderIO: 5.0.43
EnderIO-endergy: 5.0.43

I have also tested with the latest release versions of the EnderIO files:

EnderCore: 0.5.59
EnderIO: 5.0.46
EnderIO-endergy: 5.0.46

I have attached my debug.log, though I'm not sure if it will be much help since it doesn't seem to include any info about the conduit connections.

[debug.log](https://github.com/SleepyTrousers/EnderIO/files/3345951/debug.log)

I have seen, and completely read all of the previous reports of this problem I could find:

[#3873](https://github.com/SleepyTrousers/EnderIO/issues/3873)
[#3943](https://github.com/SleepyTrousers/EnderIO/issues/3943)
[#3978](https://github.com/SleepyTrousers/EnderIO/issues/3978)

Unfortunately, none of those reports seemed to end with the source of the problem being identified or fixed.  This thread is the closest I have seen to a solution, since you implemented code to force refresh the external connections on the first tick after the conduit is loaded from the save file.  Is this code still included in the 1.12.2 versions?  If not, can it be re-added?

I tried stick-clicking one of the conduits, but it didn't appear to do anything.  Is that functionality still in the 1.12.2 releases?

Here are the steps I have tried so far, none of which seemed to make any difference:

-Removed FTB Utilities and FTBLib from the pack.
-Updated to the latest release version of EnderIO. (versions noted above)
-Tested with, and without, chunk loading. (Using ChickenChunks)
-Completely deconstructing, and rebuilding, the conduit network.

None of these steps have solved the issue.  Without fail, every time I restart the game and load my world, the conduits lose their connection.  As with the other reports, breaking and replacing any conduit in the network fixes the issue until the next time the chunk is unloaded/reloaded.

My setup is in a SSP world and includes item, energy, and fluid conduits.  However, so far only the energy conduits seem to be losing their connection on every world load.  At least, as far as I've noticed.  I have had the item conduits lose connection once that I noticed.  I will include a screenshot to give you a visual.

![2019-07-01_09 44 42](https://user-images.githubusercontent.com/52415191/60447706-9c17c700-9be9-11e9-81b5-317dfa583529.png)

I really want to see this issue figured out, and fixed, once and for all.  So I am happy to provide any additional information you may need to accomplish that.  I would even be happy to upload my world save so you can use it for testing, if that would help.
