### ISSUE TITLE
Large amount of wither skeletons spwaning

### ISSUE THREAD

**Issue by SirKastros** [SleepyTrousers/EnderIO#1899] opened 2015-02-11 02:47 UTC
I have notice that my game was running low on fps and went to the neither because I have chunk loader and seen a frozen wither skeleton there with the Ender IO tag in walla. clear the neither out by going to peaceful. That was a couple days ago. Went there today found the wither skeletons frozen again and this time I notice I had 5000 + entities in the neither. I went to peaceful and this removed them again.

**Comment by blwilli12** [comment] 2015-02-11 02:51
I keep getting this error in the log
	
[20:39:35] [Server thread/ERROR]: "Silently" catching entity tracking error.
net.minecraft.util.ReportedException: Adding entity to track
	at net.minecraft.entity.EntityTracker.func_72785_a(EntityTracker.java:230) [mn.class:?]
	at cpw.mods.fml.common.registry.EntityRegistry.tryTrackingEntity(EntityRegistry.java:364) [EntityRegistry.class:?]
	at net.minecraft.entity.EntityTracker.func_72786_a(EntityTracker.java:61) [mn.class:?]
	at net.minecraft.world.WorldManager.func_72703_a(SourceFile:31) [mp.class:?]
	at net.minecraft.world.World.func_72923_a(World.java:1347) [ahb.class:?]
	at net.minecraft.world.WorldServer.func_72923_a(WorldServer.java:844) [mt.class:?]
	at net.minecraft.world.World.func_72868_a(World.java:3304) [ahb.class:?]
	at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:921) [apx.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:46) [ChunkIOProvider.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12) [ChunkIOProvider.class:?]
	at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344) [AsynchronousExecutor.class:?]
	at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302) [AsynchronousExecutor.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12) [ChunkIOExecutor.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) [ms.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:419) [ahb.class:?]
	at net.minecraft.world.World.func_147439_a(World.java:345) [ahb.class:?]
	at buildcraft.core.utils.BlockUtils.drainBlock(BlockUtils.java:175) [BlockUtils.class:?]
	at buildcraft.factory.TilePump.func_145845_h(TilePump.java:109) [TilePump.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1939) [ahb.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) [bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
Caused by: java.lang.IllegalStateException: Entity is already tracked!
	at net.minecraft.entity.EntityTracker.func_72785_a(EntityTracker.java:196) ~[mn.class:?]
	... 26 more

**Comment by shortybsd** [comment] 2015-02-11 14:53
Same issue, the earlier version made them spawn tons of white skeletons named Wither skeletons yet always dropped regular bones. Confirming the newer version v2.2.8.344 is spawning correct wither skellies but tons of them. 50 - 80 within minutes of being there. Also that error you keep getting spammed to server console is a named mob (guessing from Thaumcraft) running in and out of a loaded and unloaded chunk.

**Comment by tterrag1098** [comment] 2015-02-13 04:56
I wonder if something funky is going on with interaction between EIO and Thaumcraft... @Azanor what might cause this? Do you replace entities on the spawn event with your own (for the naming stuff)?

EIO currently replaces the vanilla wither skeleton with a unique entity.

**Comment by Azanor** [comment] 2015-02-13 06:14
I don't touch or replace any vanilla entities or alter the way they spawn at all. The champion mob system works completely through entity attributes so I don't alter the original spawns. I doubt this is TC related.

**Comment by Robijnvogel** [comment] 2015-02-18 10:36
I have about the same problem. I have some mods in my pack that generate their own spawners in the overworld. It seems like the EnderIO Wither Skeleton is overriding the rule: "if there are more than x hostile mobs nearby, spawner should stop spawning."
As a result of this I get a ticking entity error, followed by a list of forced entities containing "EntityWitherSkeleton['Wither Skeleton'/122885, l='MpServer', x=-37.30, y=-5002.36, z=0.15]," repeated hundreds of times.

Note the coordinates.

This may be another issue, but it is related.

**Comment by blwilli12** [comment] 2015-02-28 03:22
I went to the nether in my world and this issue happened again so I remove the chunk loader and BC pump I had there and deleted the Region files and reloaded the nether and everything seems to be fine for now. I am using version 2.2.8.349 of Ender IO when testing it this last time.

**Comment by blwilli12** [comment] 2015-02-28 03:29
Also I did not have Thaumcraft in my mod pack when this issue was going on. I had it at one time but removed it because I was not using it.

**Comment by RenEvo** [comment] 2015-03-03 20:22
Just had this issue happen last night, no Thaumcraft, and about 300 wither skeletons without any players around.

**Comment by shortybsd** [comment] 2015-03-04 10:29
Even with latest version when using a safari net & MFR auto-spawner using exact copy mode it will spawn a wither yet only drops bones and sometimes coal, making the only way to get wither skulls or necrotic bones you have to manually kill them. Will this be fixed?

**Comment by 1Darco1** [comment] 2015-03-10 17:54
Having the same problem on a Server running the Direwolf20 1.7.10 Pack. We have a nether fortress directly next to our nether hub and were wondering why the Tickrate in the nether was at 4.5 TPS... Then we saw the thousands of wither skeletons deriping around. Changing to Peaceful did help, but a Commandblock-Clock changing the difficulty to Peaceful and then back every now and then is obviously not going to be the permanent solution.

IllegalStateExceptions and Thread-ERRORs are also thrown constantly. 
"IllegalStateException: Entity is already tracked!
thread/ERROR: "Silently" catching entity tracking error.
entity to track"

As Robijnvogel said, the vanilla mob cap seems to be ignored completely. One thing I found which confused me is the following extract of the WitherSkeleton class in the EnderIO source:

[...] boolean isWitherSkele(Entity entity) {
    return entity.getClass() == EntitySkeleton.class && [...];
}

However, that may have a purpose which I don't know. I didn't write the code, of course. Just wanted to point that out.

Modpack Version: 1.0.4
EnderIO Version: 1.7.10-2.2.8.349
Thaumcraft Version: 4.2.3.4

**Comment by blwilli12** [comment] 2015-03-10 18:51
I use MFR in my world and I use the auto spawner to spawn wither skeleton and to kill them I use the killer Joe with The Ender from Ender IO to kill them and I have been able to getting Wither skeleton skulls and necrotic bones. This issue is with the MFR Grinder that is not getting the right drops from them because of the way MFR grinders is coded to only work with vanilla mobs and drops unless coded in the mod to work on other mod's mobs. This is more of a cross mod issue with the grinder not working to get the drops from Ender IO version of the Wither Skeleton.

**Comment by HenryLoenwind** [comment] 2015-03-10 19:24
@1Darco1 That code is in in the SkeletonHandler, not the WitherSkeleton class. It is called every time a new entity is spawned and check if it is a Vanilla Wither Skeleton (that should be replaced).

Has someone who has this problem re-tested it with an Ender IO dev version that contains the fix for #2027 (2.2.8.354 or later)? (Note: Downgrading from build 255 or later will trash Farming Stations' contents.)

http://ci.tterrag.com/job/EnderIO/354/artifact/build/libs/EnderIO-1.7.10-2.2.8.354.jar

**Comment by 1Darco1** [comment] 2015-03-10 19:46
@HenryLoenwind You're right. But still, returning false from the function which should check if the entity is a WitherSkeleton (at least that is what the name indicates) although the entity is a WitherSkeleton, is confusing.

**Comment by HenryLoenwind** [comment] 2015-03-11 12:25
But it does exactly that: checks if an entity is a (vanilla) wither skeleton...

**Comment by 1Darco1** [comment] 2015-03-11 14:48
Got it. *facepalm*

**Comment by SirKastros** [comment] 2015-03-15 12:50
I have gone through the config for enderIO and there is a feature to separate wither skeletons and regular skeletons. If the drops are not working right for the wither skeletons with the MFR grinder set that feature to false and use the exact copy on the auto spawner to spawn them when you have a vanilla wither skeleton in a safari net.

**Comment by SirKastros** [comment] 2015-03-19 16:40
build 2.2.8.356 is giving this issue after updating to it.

**Comment by PlatinumEragong** [comment] 2015-03-22 11:16
on EnderIO-1.7.10-2.2.8.349.jar 
 Hello Wladislaw,

I have taken a look at your screen log and found this:

"http://paste.creeperhost.net/view/32e08b82"

I have tried investigating to what the issue and found this - https://github.com/SleepyTrousers/EnderIO/issues/1899

If the bug causes a mass spawn of mobs, then your server will be lagging and people will be getting timed out.

**Comment by Trayaurus** [comment] 2015-03-22 15:36
I seems to be having the same problem with the spawning of Wither skeletons in the wither with no limit. Everytime I leave the Nether and come back there is always at least ~10 wither skeletons after a few seconds in the same spot

Current modlist : http://pastebin.com/Zd3abw9k

EnderIO version : 2.2.8.349

**Comment by SirKastros** [comment] 2015-03-22 18:56
I have tested build 2.2.8.362 and it will correct the Silenty cache entity error but in the spawn of wither Skeletons in large numbers is lower in chance and will now fix it self.

**Comment by SirKastros** [comment] 2015-03-23 20:15
the Silently cache entity error is more active on a server then on single player. and now the neither has no entities in it after the spike of entities. This test was done on build 2.2.8.363

**Comment by braddr** [comment] 2015-03-26 10:00
I'm seeing this bug occur with 2.2.8.349 (current version in SkyFactory 2.3).  In my case, triggering the issue doesn't require a spawner at all.  My nether portal is fairly close to a large nether fortress, which is likely enough to trigger the behavior.  They spawn along a walkway in sufficient numbers to cause a rather cool waterfall like flood of falling bodies.

I tried the .354 version as indicated above with no obvious change in behavior.  I also tried .362 and .363 also with no noticeable difference.. still thousands and thousands of wither skeletons.  .364 failed to start with some missing class errors that I didn't spend the time to try to track down.

My record so far is 45k wither skeletons.  Thank &diety; that cofh comes with a rather handy killall command.

**Comment by SirKastros** [comment] 2015-03-26 12:39
the temporary fix I have found for this issue is to remove all chunk loader and pumps in the nether. Close the game and delete the region files in dim -1 folder. this will force the nether to re-spawn but using the same seed. Also make sure you are out of the nether before closing the game.

**Comment by Namikon** [comment] 2015-03-27 11:25
I just tested the massive entity-peak (F3-Screen) caused by skeleton spawners by myself, with a clean instance (only EIO) and in my full-modded version (private pack, 190+ mods). Version 354 seems to fix this issue. It now spawns EIO wither skels. Interesting enough, I never had any problems with massive amounts of withers in the nether, and I also had no such problems on my server (yet). The spawner I placed in the nether just spawned 2 skeletons after I placed it.

So, as this seems to fix the problem, I will "go live" with EIO v354 and I shall see if the nether is useable again this weekend.

**Comment by sww1235** [comment] 2015-04-11 05:57
This problem is fixed by disabling the separating of wither skeletons and skeletons in the config file.

**Comment by tterrag1098** [comment] 2015-04-11 07:01
@sww1235 Of course, but that doesn't solve the greater issue.

**Comment by tterrag1098** [comment] 2015-04-11 07:02
I can probably fix this with a more complex system...caching the entities to remove and then doing the action at the end of the tick. That will at least solve the tracking spam. Hopefully it also resolves the out of control spawning.

**Comment by nekojess** [comment] 2015-05-18 06:03
Caching the removal sounds like it'd help with the error (I have no idea), but I highly doubt it'd resolve the spawning issue.

I don't have the setup to test, but from looking at the code I'm pretty sure I can see the problem. The base Minecraft code for spawning skeletons of course doesn't check against EnderIO's EntityWitherSkeletons, so regardless for how many there are, it's always going to see that there aren't any vanilla skeletons around and will go ahead and keep spawning them... which EnderIO promptly removes to create EntityWitherSkeletons, ad infinitum.

The way to fix this would be to simply stop spawning in EntityWitherSkeletons upon some limit. While still preventing the vanilla ones from spawning (or rather, while still removing vanilla ones upon spawning).

Looking around, [here's how ChocoCraft limits spawning.](https://github.com/ArnoSaxena/chococraft/blob/master/src/main/java/chococraft/common/entities/spawner/ChocoboSpawner.java#L108-L114) (The countWildInChunkRadius() function is below on line 184)

**Comment by HenryLoenwind** [comment] 2015-05-18 06:10
@nekojess could you please point me at the vanilla code you're referring to? thx.

**Comment by nekojess** [comment] 2015-05-18 09:09
@HenryLoenwind Okay, I've looked about and it seems I misremembered bits about hostile mobs, oops. Nevermind.

But I did notice that [it's using setDead()](https://github.com/SleepyTrousers/EnderIO/blob/master/src/main/java/crazypants/enderio/entity/SkeletonHandler.java#L18), and it should probably use event.setResult(Result.DENY), which should actually prevent it from spawning... instead of just setting it to be dead so that it'll spawn and immediately despawn. Don't know if that would change anything though.

Maybe related, but awhile ago I checked on my animal pen and it had numerous stacks of eggs, feathers, (and chocobo feathers) sitting there. It was like they were still doing stuff but entities weren't despawning. I'm pretty sure they should have been unloaded too. Maybe it's a rare bug with a different mod, but EnderIO just does something which causes it to trigger it more than average. I don't know, it's quite weird.

**Comment by HenryLoenwind** [comment] 2015-05-18 11:16
The problem with cancelling the event (which is documented as not being cancel-able but actually is, btw) is that then the entity will not be counted and the code that limits how many entities are spawned in one spawning will not work.

Also, this problem does not happen all the time. I've tried a couple of times but I could not reproduce it. So it is definitely an interaction with some other mod.

**Comment by Robijnvogel** [comment] 2015-05-18 13:39
Special Mobs by Fathertoast may have the code you are looking for. It replaces Vanilla wither skeletons as well. It may have a totally different way of doing so though.

**Comment by chezpaul** [comment] 2015-12-27 19:28
So what is the fix to this error? No one really says what to do.
I clicked all over the web.
I'm running EnderIO-1.7.10-2.3.0.421_beta and still get this error.(Kcauldron 1492.152)
I've read to turn of Wither Skeletons in config but that's not an option in my ender config.
What should I do? My console is spammed every 30 seconds.
Thanks.

**Comment by SpitefulFox** [comment] 2016-04-28 08:30
Been having wither skeleton problems on the server I'm on too.  There's this 2x3 area underneath my house that will NOT let me place blocks in it.  Whenever the chunk is unloaded and reloaded, thousands of wither skeletons spawn from that area at once, each showing as being from "Ender IO" in WAILA.

**Comment by mindforger** [comment] 2016-04-28 09:05
@SpitefulFox you are missing crucial informations like 
used Forge version
used EIO version
other interferring mods
maybe a snapshot of that "space you can not place blocks on" .. (just as an idea, set spawnprotection in your server.properties to 0 or give yourself OP and test if you can place something there, if still not able to place anything, then sounds more like a broken world)

and finally `commented on 18 May 2015` why necro this one if making a new one with details and a reference to this one would be way more polite :)

**Comment by SpitefulFox** [comment] 2016-04-28 09:51
It's an issue that's still open and matches the problem I'm having, why would I want to open a new issue for the same thing?

**Comment by mindforger** [comment] 2016-04-28 10:04
@SpitefulFox you should have read the whole issue content and at least my post fully, I was hinting to do so because your issue seems not to fit fully into the described problem ... and you are still missing the informations requested

**Comment by SirKastros** [comment] 2016-04-28 12:33
@SpitefulFox The original post was for the Ender IO wither
skeletons natural spawning in the nether in large amounts and cause the
game to lag out when in the nether. this issue was with a 2.2.8 build of
EnderIO for MC 1.7.10. The only way you will have them spawning under your
base is if your base is in the nether without a power spawner. Like
mineforger said you are not giving all the details.

**Comment by tterrag1098** [comment] 2016-04-28 19:39
At this point the wither skeleton replacement is disabled by default and we recommend everyone against using it. If it is causing you issues, disable it in the config.

**Comment by SpitefulFox** [comment] 2016-04-28 20:06
Okay.  Sorry for offending you.

**Comment by HenryLoenwind** [comment] 2016-04-28 20:38
This has nothing to do with being offended. On the one hand (random) people are trying to help you by giving pointers how to better report your problem. On the other hand the maintainer is telling you that that functionality is broken beyond repair and should be disabled.

**Closed** 2016-05-28 13:22 UTC
Labels: Bug Mod integration
