### ISSUE TITLE
Inventory panel remotes (any) not opening GUI

### ISSUE THREAD

**Issue by siccaxe** [SleepyTrousers/EnderIO#4213] opened 2017-05-10 19:59 UTC
#### Issue Description:
Exactly the same as closed issue #3644 , Remote not opening GUI when used.

#### What happens:

Any inventory panel remote fails to open a connection to the target inventory panel, but uses it's fluid each time it is attempted. 

#### What you expected to happen:

Works as intended

#### Steps to reproduce:

1. craft or cheat in any inventory panel remote
2. crouch+right-click functioning inventory panel with remote to set target (prints "target set")
3. attempt to use the remote, note that fluid decreases with each attempt, but RF doesn't and GUI doesn't open
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.1.187
- EnderCore: 1.10.2-0.4.1.65-beta
- Minecraft: 1.10.2
- Forge: 1.10.2 - 12.18.3.2281

#### Your most recent log file where the issue was present: 

I read the closed issue and saw that there should be an error in the log (Unexpected failure to get tileentity at BlockPos), but it's not there. is there a flag I need to flip in the config to display this error in the minecraft log?

**Comment by HenryLoenwind** [comment] 2017-05-11 21:56
You most probably have a different problem than the original one. Let me check if there's a general problem caused by the latest cleanup. If not, I'd ask you to reproduce the problem with a minimal set of other mods installed (assuming it won't happen for you with just Ender IO).

**Comment by HenryLoenwind** [comment] 2017-05-11 22:44
Found it, it was a general problem. Fixed in next build.

**Closed** 2018-06-20 18:32 UTC
Labels: 1.10, Code Complete, bug
