### ISSUE TITLE
Conduit Probe Copy-paste not functioning for redstone conduits

### ISSUE THREAD

**Issue by LuciusV** [SleepyTrousers/EnderIO#5011] opened 2019-01-17 14:11 UTC
#### Issue Description:
I had 5 bioreactors + 32 biofuel generators from Industrial Foregoing, having decided to make them turnable on/off I connected redstone conduits to them.
Conduit probe does not change Redstone Conduit settings if copypasted in copypaste mode.

#### What happens:
Message that settings gave been copied appears, but in fact settings are intact

#### What you expected to happen:

Settings changed

#### Steps to reproduce:

1. Make something with redstone conduits and try to copypaste settings
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

  -  EnderIO: EnderIO-1.12.2-5.0.39
  -  EnderCore: EnderCore-1.12.2-0.5.43
  -  Forge: 1.12.2-14.23.5.2768

**Comment by zhykzhykzhyk** [comment] 2019-03-29 14:58
After go through the code and some test, I found the problem is coming from that the redstone conduit has not acctually connected to the target machine when placed, thus can’t the settings be pasted.

Work around: manually ensure the connect by check the output in the config UI, then paste the settings

**Comment by HenryLoenwind** [comment] 2019-03-29 15:01
I think no conduit can have its settings pasted when it does not have a connecting "arm"? Is that really the issue reported here?

**Comment by zhykzhykzhyk** [comment] 2019-03-29 15:03
Arm is created along with other conduit (like energy conduit or item conduit)

**Comment by zhykzhykzhyk** [comment] 2019-03-30 09:59
@HenryLoenwind Is it applicable to paste settings in all possible conduit besides of the already conntected? Like condition used in [here](https://github.com/SleepyTrousers/EnderIO/blob/62a18c8a8dbedd7b7827e8a171f3a03ba6bb1f3f/enderio-conduits/src/main/java/crazypants/enderio/conduits/gui/GuiExternalConnection.java#L72).

**Comment by HenryLoenwind** [comment] 2019-05-16 22:45
Ok, there are multiple issues here:

1. The check to only paste settings for conduits that can actually connect doesn't have the special "redstone can connect to everything" logic
2. The conduit gui for redstone conduits shows "input" as checked when the conduit is not connected at all

I'm on it.

**Comment by tyler489** [comment] 2019-07-11 19:04
Fixed in .46

**Closed by tyler489** 2019-07-11 19:04 UTC
Labels: 1.12, Code Complete, bug
