### ISSUE TITLE
AE2  P2P RF mode doesn't transfer power from enderIO energy banks

### ISSUE THREAD

**Issue by frenchiveruti** [SleepyTrousers/EnderIO#3161] opened 2016-01-26 04:07 UTC
I don't know if this you guys fault, or AE2 fault, as far as I know, this works with Thermal Expansion Energy cells, but it won't work with yours capacitor banks or dimensional transceivers.  
If you need further explanations on what I'm trying to achieve, check this short video:
https://www.youtube.com/watch?v=VuPxoqrCQ6M  
Thanks!

**Comment by Psithief** [comment] 2016-01-28 07:43
I was able to get an RF P2P tunnel to send from a Thermal Expansion cell to a Dimensional Transceiver. Can you replicate this?
![2016-01-28_15 41 09](https://cloud.githubusercontent.com/assets/1124846/12638138/c4dd4edc-c5d5-11e5-99a4-c7b7d633318d.png)

**Comment by HenryLoenwind** [comment] 2016-01-28 08:27
I'd need to look at the code of the P2P thingy, but most probably the reason is:

RF is a push-based protocol, meaning that a power source actively offers energy to all connected machines/pipes. But now more and more devs are discovering that they can actually pull energy from TE's cells---and are building their piping systems that way. And if their machines/pipes don't accept energy that is pushed into them but only work if they can pull the power from the energy sources themselves, they lose compatibility with half of the RF world.

**Comment by Psithief** [comment] 2016-01-28 08:48
@HenryLoenwind @frenchiveruti 

I believe I've found the actual problem.
RF can only travel from P2P tunnel **input** to **outputs**. It can't travel the other way. I believe this is by design, so you'll have to build your network to accommodate this.

[Unfortunately](/AppliedEnergistics/Applied-Energistics-2/issues/2110), Applied Energistics gives no visual feedback on the difference between the tunnel input compared to its outputs. (A tunnel can only have a single input.

For example, this setup can send from one cell to the other, but toggling the cell behaviour between input/output won't transfer the RF back.

![2016-01-28_16 45 04](https://cloud.githubusercontent.com/assets/1124846/12639293/82d15408-c5de-11e5-9ce7-d714af6f50e1.png)

Yes, those P2P buses _do_ look identical, you're not imagining it!

**Comment by Psithief** [comment] 2016-01-28 08:51
Keeping these limitations in mind, I just tried it with a capacitor and the transfer works fine.

**Comment by HenryLoenwind** [comment] 2016-01-28 12:57
Ok, so this seems to be a bad design decision (pun intended) on the tunnel mod.

Closing this ticket. Thanks for finding the root cause, @Psithief

**Closed by HenryLoenwind** 2016-01-28 12:57 UTC

**Comment by frenchiveruti** [comment] 2016-01-28 14:06
I tried both ways and It wasn't working, in the end the solution was entirely different, just add an energy conduit from the dimensional transceiver to the P2P port, and the same applies to the capacitor banks.  
As you can see here 
![ae2 p2p energy rf](https://cloud.githubusercontent.com/assets/1095997/12646485/28408ff6-c5af-11e5-920c-4c585f5d8c81.png)

**Comment by Psithief** [comment] 2016-01-28 15:33
@frenchiveruti 
What versions of AE2 and Ender IO are you running?

**Comment by frenchiveruti** [comment] 2016-01-28 15:35
Oh... hmmm, I'm running FTB Infinity Evolved, so now I'm starting to think that it might be an outdated version of the mod....

**Comment by Psithief** [comment] 2016-01-28 15:49
![2016-01-28_23 46 47](https://cloud.githubusercontent.com/assets/1124846/12649444/8cf679e6-c619-11e5-9198-d430abec0c4f.png)
![2016-01-28_23 47 09](https://cloud.githubusercontent.com/assets/1124846/12649449/90f305d2-c619-11e5-9693-852937502a28.png)
![2016-01-28_23 47 20](https://cloud.githubusercontent.com/assets/1124846/12649452/92f04980-c619-11e5-9e97-d3b7c120c2ce.png)

Could be, here's a time-lapse with just the latest versions of AE2 and Ender IO.

**Comment by XFactHD** [comment] 2016-01-28 16:21
If I understand the code correctly, the RF P2P is calling receive on the tile entity adjacent to the P2P, which sounds legitimate to me. Is that correct @yueh @thatsIch?

**Comment by tterrag1098** [comment] 2016-01-28 18:09
That's fine, the problem would be if they were calling extract. RF is meant to be push based, and capacitor banks do not allow extraction manually.
