### ISSUE TITLE
AutoCrafter Crashing the server/game

### ISSUE THREAD

**Issue by NassiC** [SleepyTrousers/EnderIO#2793] opened 2015-09-08 18:43 UTC
The autoCrafter is crashing the game when trying to craft with infusion stones from Magical Crops.
The infusion stone dont get used when crafting.

When putting in the infusion stone, or adding power to a autocrafter with an infusion stone in, the game hangs, you can move, but the world is frozen. (cant open chest etc.)
On the server it did the same, but then when trying to log on after, you got a time out. Ther server seemed to run fine, you just coulnt connect.

Im running
EnderIO v 2.2.8.381
forge 10.12.4.1492
Magical Crops:Core 4.0.0_public Beta_5

**Comment by MatthiasMann** [comment] 2015-09-08 18:54
duplicate of #2552

**Closed by MatthiasMann** 2015-09-08 18:54 UTC
Labels: Duplicate
