### ISSUE TITLE
1.10.2 - Conduits are weird and invisible and can crash you.

### ISSUE THREAD

**Issue by Peach774** [SleepyTrousers/EnderIO#3484] opened 2016-07-06 20:09 UTC
Conduits have gone invisible in the world. Some are visible others are not. If you right click the invisible ones they crash with this crash: http://pastebin.com/BxRpxSZU

![image](https://cloud.githubusercontent.com/assets/5171184/16632817/e1fcfe2c-437a-11e6-9b39-93fd16dc000e.jpg)

It looks the same without a wrench. can also be fixed by removing and replacing but happens again on login. In a lan world

**Comment by b0bst3r** [comment] 2016-07-10 00:14
This is a known issue caused by Calculator machines, don't ask me why I have no clue and neither does the modder, you can prove it quite simply by breaking all calculator machines and sticking them in a chest, undo the missing textures by doing a block update then it wont happen again.

https://github.com/SonarSonic/Calculator/issues/125

**Comment by HenryLoenwind** [comment] 2016-07-10 00:26
thx for finding the cause. closing this ticket

**Closed by HenryLoenwind** 2016-07-10 00:26 UTC
Labels: 1.10, Bug in other software, Report Incomplete
