### ISSUE TITLE
Client visual glitch after server update when looking at machines

### ISSUE THREAD

**Issue by DatenThielt** [SleepyTrousers/EnderIO#4727] opened 2018-06-24 18:00 UTC
#### Issue Description:
Modpack: Rev2 Version 2.1.0  (Reported to them also, but since this only involved ender, here too)

When trying to right click and look at any machines inventory,  The UI fails to appear, and on the client side it shuffles all inventory, and duplicates part of the inventory too.   This happens with All tiers of machines

This appears to be the case with machines that existed previously, we are currently setting up a test instance to see if it happens with newly placed machines. 

Side note when an admin did this is changed his inventory permanently (Client and server side) We are not sure why this is.

Additional!: We are experiencing this on both a Rev2 Modpack and ATM3 modpack

#### What happens: 
Right clicking an EnderIo Machine causes inventory to be jumbled, fixed most of the time on client login/logout

#### What you expected to happen: Machine 
UI to open and inventory to be untouched

#### Steps to reproduce:

1. Log into server
2. Right click EnderIO Machine
3. No UI appears, and inventory is jumbled
...

____
#### Affected Versions (Do *not* use "latest"):

ATM
EnderCore-1.12.2-0.5.31.jar
EnderIO-1.12.2-5.0.26.jar

Rev2.1
EnderCore-1.12.2-0.5.31.jar
EnderIO-1.12.2-5.0.26.jar

- Minecraft: 1.12.2
- Forge: 14.23.4.2705

#### Your most recent log file where the issue was present: 
https://gist.github.com/DatenThielt/feb3692e90f2038baaa1cee393154d0e

![after](https://user-images.githubusercontent.com/4466326/41821981-d30c55ec-77e0-11e8-8c63-24f00ed3d71b.png)
![before](https://user-images.githubusercontent.com/4466326/41821982-d32559f2-77e0-11e8-8017-b956789992f3.png)
![wierdness](https://user-images.githubusercontent.com/4466326/41821983-d33c8ed8-77e0-11e8-9337-5ce4f10209ad.png)

**Comment by bunnyman14** [comment] 2018-06-24 18:18
Sounds like #4723

Can you send a copy of the server log?

**Comment by DatenThielt** [comment] 2018-06-24 19:41
I am just asking about the server log now,  We can give you the server log of our ATM3 server which has the issue since we are still running that despite the issue if you think it would help

**Comment by DatenThielt** [comment] 2018-06-24 19:51
Here is the server log for Rev2

**Comment by tyler489** [comment] 2018-06-24 22:10
Out of curiosity does it happen with nucleus disabled?

**Comment by HenryLoenwind** [comment] 2018-06-24 22:39
Nothing obvious in there. Please run both server and client with "-DINDEV=1" and reproduce the issue. Please get the matching log segments.

**Comment by HenryLoenwind** [comment] 2018-06-24 22:57
Actually, I see one odd thing:

```
[18:43:22] [Netty Client IO #17/INFO] [FML]: Attempting connection with missing mods [controlling, ctgui, ctm, custommainmenu, defaultoptions, jehc, jeiintegration, jeresources, modnametooltip, moreoverlays, mousetweaks, rebornstorage, refinedstorage, refinedstorageaddons, resourceloader, thaumicjei, tipthescales, xray, reauth] at SERVER
```
While a couple of those are client-side mods (e.g. mousetweaks), a good number are not (e.g. refinedstorage). Having mods loaded on the client but not the server that do not specifically support that will mess things up.

**Comment by HenryLoenwind** [comment] 2018-06-24 23:57
see also https://github.com/AllTheMods/ATM-3/issues/635

**Comment by DatenThielt** [comment] 2018-06-26 16:41
So This is kind of resolved, I'm not sure if it needs looking at here, or probbaly refined storage,  But we re-enabled refined storage, and EnderIO started working great again!  

Its odd that disabling a mod would prevent EnderIO's GUI from coming up though?   Will let you decide what needs to happen here :)  Thanks everyone

**Comment by tobywf** [comment] 2018-06-29 07:07
#### Issue Description:

I get this issue in Direwolf20 modpack. I know the issue template says to report it to the modpack, but given it's exactly the same issue with exactly the same versions as #4723 and I have a log file, maybe it's appropriate to amend this issue? (If not, I'll repost on their issue tracker.)

#### What happens:

0. I crafted a tank, and filled it with lava (not sure if related, but it's the first thing I did with EnderIO)
1.  I crafted a Simple SAG Mill/Simple Alloy Smelter/Simple Stirling Generator
2. I placed them in world
3. I right clicked the Simple Stirling Generator
4. UI does not open
5. Inventory is scrambled, common items added to armour slots, sometimes items appear duped or disappear (until relog)
6. Also happens with other machines (Simple SAG Mill/Simple Alloy Smelter)

#### What you expected to happen:

UI opens and inventory is untouched.

#### Steps to reproduce:

See "What happens". Issue is not resolved by restarting server.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: mods/EnderIO-1.12.2-5.0.26.jar
- EnderCore: mods/EnderCore-1.12.2-0.5.31.jar
- Minecraft: 1.12.2
- Forge: 14.23.4.2709

(Confirmed client and server versions match)

#### Your most recent log file where the issue was present: 

The log file starts when I start progression towards EnderIO machines. Previously I crafted a tank, so let me know if you need previous logs, and I'll see if I still have them:

https://gist.github.com/tobywf/0dd1f6c85db9865b25412e52117ad36d

The log contains a NullPointerException, but having said that, restarting the server does not fix the issue, and  subsequent relogs have the same behaviour but do not cause the same exception:

https://gist.github.com/tobywf/f8cdc5bdcc99e6228b324daafe0ba113

Thanks!

**Comment by HenryLoenwind** [comment] 2018-06-29 07:44
```
Caused by: java.lang.NullPointerException: Null string not allowed
        at java.util.Objects.requireNonNull(Objects.java:228) ~[?:1.8.0_172]
        at net.minecraft.nbt.NBTTagString.<init>(NBTTagString.java:19) ~[gm.class:?]
        at net.minecraft.nbt.NBTTagCompound.func_74778_a(NBTTagCompound.java:137) ~[fy.class:?]
        at net.minecraftforge.fluids.FluidStack.writeToNBT(FluidStack.java:108) ~[FluidStack.class:?]
        at net.minecraftforge.fluids.FluidUtil.getFilledBucket(FluidUtil.java:750) ~[FluidUtil.class:?]
```

One of the other mods has a bad fluid.

**Comment by tobywf** [comment] 2018-06-29 10:43
Righto, it's not EnderIO. Sorry about that. I disabled a bunch of mods and confirmed it starts working again. Weirdly, when I re-enabled the mods, it didn't break. I'll forward this on to the modpack and do some more digging this weekend. Cheers!

**Closed** 2018-06-29 11:20 UTC
Labels: 1.12

**Comment by HenryLoenwind** [comment] 2018-06-29 15:12
probably a fluid that exists in multiple mods. One of the mods "wins" the selection and its fluid is then used. Minecraft then remembers which one that was. When you ran the game with the bad mod removed, another mod was selected and is now remembered.

**Comment by tyler489** [comment] 2018-06-29 20:40
did you happen to have Mekanism... i know they have a lot of fluids without buckets.

**Comment by tobywf** [comment] 2018-07-03 04:28
I don't have Mekanism. Sadly I was a bit impatient when I started disabling mods b/c server reboots take so long, so I don't know which mod it was. I disabled BrandonsCore/Draconic, DeepResonance/ElecCore, FastWorkbench, ImmersiveEngineering, IndustrialCraft 2/CompatSolars/SimplyJetpacks2, PneumaticCraft Repressurized, AE2, and maybe a few others that depended on those. Wasn't able to reproduce the issue using the backup. Hopefully if somebody hits the same issue, they'll know now from this thread what to do.
