### ISSUE TITLE
conduits are rendering invisible/not updating properly

### ISSUE THREAD

**Issue by xemnes** [SleepyTrousers/EnderIO#5470] opened 2020-11-02 07:14 UTC
#### Issue Description:

my conduits are rendering very weirdly, happens on both single player and multiplayer
https://gfycat.com/HalfDefenselessBudgie

#### What you expected to happen:
conduits should be rendering properly.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.2.61
- EnderCore: 0.5.76
- Minecraft: 1.12.2
- Forge: 2847
- SpongeForge? no
- Optifine? yes (happens without optifine too)
- Single Player and/or Server?

#### Your most recent log file where the issue was present: 

[latest.log](https://github.com/SleepyTrousers/EnderIO/files/5473266/latest.log)

**Comment by hypherionmc** [comment] 2020-11-02 07:17
Looking at the attached capture, it seems you have a graphical mod installed that modifies some rendering, in this case particles. So it's likely that this is interfering with the rendering of the conduits.

If you know what mod this is, try removing it and see if the issue persists

**Comment by xemnes** [comment] 2020-11-02 07:19
i have fancyblock particles, but im not aware of any incompatibilities?

**Comment by hypherionmc** [comment] 2020-11-02 07:22
Might not be known. The only time we know about an incompatibility is if someone reports it or one of us discover it by ourselves. I use the same forge version with EIO, so I doubt that's the issue, but anything is possible in the modding world xD

**Comment by xemnes** [comment] 2020-11-02 07:31
i removed fancy block particles and its still happening.

**Comment by hypherionmc** [comment] 2020-11-02 07:34
Hmmm then more investigation is required. Has this been happening since the beginning or started recently?

Could you also try reproducing this on a fresh world?

**Comment by xemnes** [comment] 2020-11-02 07:43
im not entirely sure to be honest, ive had enderio installed for a while now, ive been in the process of setting all my mods up one by one making sure they all work in the modpack before i release it, just got to enderio. i thought i had placed conduits before but i cant remember. i had 5.2.59 before upgrading to .61
tried on a fresh world with the same problem. 
i need to sleep, i will do some more testing tomorrow.

**Comment by xemnes** [comment] 2020-11-02 14:47
ok did some more investigation, i downgraded to 5.2.59 to test and its definitely something to do with .61 as the issue does not occur on .59 https://gfycat.com/HilariousBabyishImperatorangel

**Comment by hypherionmc** [comment] 2020-11-02 14:54
I will try to reproduce it on my side

**Comment by hypherionmc** [comment] 2020-11-02 16:20
Okay so I tried with Optifine and without and could not reproduce this at all. This sounds like a mod interfering. I also double checked, no rendering code changed between 59 and 61

**Comment by xemnes** [comment] 2020-11-02 16:29
so why would it be working fine on 59 on my end then if no code would have changed to introduce potential mod conflicts?

**Comment by Mario90900** [comment] 2020-11-05 01:06
I suspect this has to do with the TickCentral and LagGoggles issue that the recent version of EIO has run into. The one that causes EIO blocks to not tick on a server. I saw in your log you also have TickCentral 3.1 along with the most recent version of EIO when you were getting this, and I was getting this same issue with the conduits, along with a player not having their sterling generator tick. Removing both LagGoggles and TickCentral from the server fixes both of these issues, so I believe the conduits don't ever get ticked to render properly and they are actually stemming from the same original problem. It also seems to effect the clientside regardless of it being on the server, and it causes GUIs to bug out likely due to the same lack of ticking problem, so I'd recommend removing it until you actively need LagGoggles.

**Comment by HenryLoenwind** [comment] 2020-11-10 23:05
Thx Mario90900, that's a very good observation. Yes, conduits do need the tick to propagate the information that they need to be re-rendered.

This should then be fixed with the next release. Expect it within a couple of days.

**Comment by Mario90900** [comment] 2020-11-10 23:59
Oh awesome! I'm glad to hear the fix for this is coming soon, and glad I could help a little! Thanks for the hard work on this!

**Comment by xemnes** [comment] 2020-11-11 00:06
ah so its lag goggles, well i will keep enderio downgraded in the mean time until the fix rolls out. thanks.

**Comment by hypherionmc** [comment] 2020-11-23 14:01
The new release is out :) Be sure to give it a shot and let us know if this still persists

**Closed by hypherionmc** 2020-11-23 14:01 UTC
Labels: 1.12

**Comment by xemnes** [comment] 2020-11-23 14:24
can confirm conduits are now fixed.
