### ISSUE TITLE
Experiencing issue #1366 again in EnderIO-1.7.10-2.2.8.381

### ISSUE THREAD

**Issue by czaderak** [SleepyTrousers/EnderIO#3110] opened 2016-01-05 17:16 UTC
I'm experiencing this issue:
https://github.com/SleepyTrousers/EnderIO/issues/1366

I don't have spawners high in the clouds. It's just small zombie farm in my house with chunk loader next to it. It stops spawning when I leave the server.

I've checked the settings but "I:poweredSpawnerMaxPlayerDistance" is set to "0", which means player check should be turned off.

**Comment by wlhlm** [comment] 2016-01-05 17:17
Is this fixed with the most recent beta release (EIO 2.3)?

**Comment by czaderak** [comment] 2016-01-05 17:19
I'll check it in a moment.

**Comment by wlhlm** [comment] 2016-01-05 17:21
Make sure to make a backup beforehand.

**Comment by czaderak** [comment] 2016-01-05 17:23
Don't worry I'm testing it on local server ;)

**Comment by czaderak** [comment] 2016-01-05 17:25
I need later version of forge :/ I need a moment to set it up.

**Comment by HenryLoenwind** [comment] 2016-01-05 17:27
There's also a setting on how long to keep mobs from despawning, make sure that one's *not* 0.

**Comment by czaderak** [comment] 2016-01-05 17:35
Where can I find this option?

**Comment by HenryLoenwind** [comment] 2016-01-05 17:41
Oops, sry, it was already on the 2.3-branch. On the 2.2.8, the fix for 1366 was the last thing to be done to the powered spawner.

**Comment by czaderak** [comment] 2016-01-05 17:43
Will there be any fix for 2.2.8 then? Or will it be fixed only in later versions?

**Comment by HenryLoenwind** [comment] 2016-01-05 17:49
Depends on what the problem is, but it is quite unlikely that we'd do a new release for 2.2.8 with 2.3.0 nearly finished.If it's just something small, I could make you a private build with the fix.

**Comment by czaderak** [comment] 2016-01-05 17:56
That would be great. I tried to use the latest beta, but it's still asking
me for later version of minecraft :/
5 sty 2016 18:50 "Henry Loenwind" <notifications@github.com> napisał(a):

**Closed** 2016-05-28 09:42 UTC
