### ISSUE TITLE
Bug with Vacuum Chest [Important!]

### ISSUE THREAD

**Issue by Patrick15a** [SleepyTrousers/EnderIO#2752] opened 2015-08-29 19:59 UTC
The interface of Vacuum Chest is not closed during the break Vacuum Chest. Thus items can be doubled. Please this bug as soon as possible treat!

PS: Srry my english is bad!

**Comment by HenryLoenwind** [comment] 2015-08-29 20:07
Which version does this happen with? I ask because we already did some fixes to its GUI in v2.3.

**Comment by Patrick15a** [comment] 2015-08-29 20:08
EnderIO-1.7.10-2.2.8.381
In FTB Infinity

**Comment by tterrag1098** [comment] 2015-08-29 20:55
Duplicate of #2717 (same fix for that fixes this)

**Closed by tterrag1098** 2015-08-29 20:56 UTC
