### ISSUE TITLE
Mekanism and Ender IO

### ISSUE THREAD

**Issue by GabrielGamer66** [SleepyTrousers/EnderIO#2259] opened 2015-04-07 17:35 UTC
My game has Crashed with the gas conduct
http://pastebin.com/H5Rv0PNa

**Comment by eduardog3000** [comment] 2015-04-07 17:50
Please use the search bar before posting, this is a duplicate of #2257.

**Comment by tterrag1098** [comment] 2015-04-07 17:57
Also #2110

**Closed by tterrag1098** 2015-04-07 17:57 UTC
