### ISSUE TITLE
Charging the travel stuff

### ISSUE THREAD

**Issue by forestbat** [SleepyTrousers/EnderIO#4190] opened 2017-05-01 08:05 UTC
#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:1.10.2-3.1.186
- EnderCore:1.10.2-0.4.1.65-beta
- Minecraft: 1.10.2
- Forge:12.18.3.2281

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by MatthiasMann** [comment] 2017-05-01 08:52
Duplicate of #4072

**Closed by MatthiasMann** 2017-05-01 08:52 UTC
Labels: 1.10, Duplicate, Logfile Missing
