### ISSUE TITLE
Farming Station Not Working with 426Beta

### ISSUE THREAD

**Issue by Darkosto** [SleepyTrousers/EnderIO#3333] opened 2016-05-28 22:55 UTC
#### Issue Description:
The Farming Station does not work correctly.

#### What happens:

When placing down, the Farming Station will do 1-2 operations before it stops functioning. It will still continue to draw RF. This has been reproduced with only Forge, EnderCore, and EnderIO

#### What you expected to happen:

I expect it to work correctly.

#### Steps to reproduce:

1. Place Farming Station
2. Give tools/seeds
3. Watch it not work correctly
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.7.10-2.3.0.426_beta.jar
- EnderCore:EnderCore-1.7.10-0.2.0.35_beta.jar 
- Minecraft: 1.7.10
- Forge:1614

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by RabidDave** [comment] 2016-06-07 17:59
cross dupe of issue (other closed)

**Comment by Routhinator** [comment] 2016-06-10 15:09
Cross dupe of which issue? Please link.

Is this fixed?

**Comment by Joshwoo70** [comment] 2016-06-11 07:39
i might also add that this is broken in FTB inventions.

**Comment by HenryLoenwind** [comment] 2016-06-13 21:10
link in #3344

**Comment by HenryLoenwind** [comment] 2016-06-13 22:19
Fixed in latest build

**Closed by HenryLoenwind** 2016-06-13 22:19 UTC
Labels: 1.7, bug, Code Complete
