### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by ProthosMP** [SleepyTrousers/EnderIO#5123] opened 2019-05-04 14:22 UTC
#### Issue Description:

I have no clue what is going on. I was just happily jumping around.
See crash report. 

The thing that I can remember was that I jumped into Capacitor bank with a solar panel on it. 

#### What happens:

Game crashed, game crashes immediately upon reloading world. 

#### What you expected to happen:

Nothing

#### Steps to reproduce:

I dont know how I would recreate this. 

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.43
- EnderCore: 1.12.2-0.5.57 
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.5.2836
- SpongeForge? no
- Optifine? no
- Single Player and/or Server? Single Player

#### Your most recent log file where the issue was present: 

https://pastebin.com/P8g7r7Uu

**Comment by HenryLoenwind** [comment] 2019-05-04 14:23
#5097

**Comment by LumberWizard** [comment] 2019-05-04 14:24
Another duplicate of #5117, #5103, #5093, #5090, #5086, etc.

**Closed by HenryLoenwind** 2019-05-04 14:23 UTC
Labels: 1.12, Duplicate
