### ISSUE TITLE
Thaumcraft Conduits

### ISSUE THREAD

**Issue by Yusunoha** [SleepyTrousers/EnderIO#2171] opened 2015-03-28 18:23 UTC
seeing as Ender IO adds some conduits that add compatibility with other mods, how about adding conduits for Thaumcraft support aswell? these conduits would act like the pipes from Thaumcraft itself and will be able to transfer essentia through the conduits.

with these conduits you could perhaps also have the option of importing or exporting from the sides of jars, instead of only from the top as it is now with the thaumcraft pipes.

**Comment by Vexatos** [comment] 2015-03-28 18:25
The problem with this is that it's pretty much impossible to properly implement Thaumcraft's suction system and displaying issues the way Thaumcraft does...

**Comment by Kodos-Atoz** [comment] 2015-03-28 18:38
This is also a duplicate of #2167

**Comment by tterrag1098** [comment] 2015-03-31 14:42
#2167

**Closed by tterrag1098** 2015-03-31 14:42 UTC
